### ISSUE TITLE
Check out button 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#1]
![screen shot 2014-04-04 at 2 19 07 pm](https://cloud.githubusercontent.com/assets/4335901/2620470/e32a1642-bc3e-11e3-9222-2b2cf8400237.png)
All pages have Check Out button in the middle of page

**Comment by DeveloperRegistry** [comment]
Test update

**Comment by RealBerd** [comment]
Таня, в каком это браузере случилось? Спасибо

**Comment by Fetati** [comment]
÷ èÒÏÍÅ É óÁÆÁÒÉ

Best regards,
Tanya Fedorova

+1 (650) 296-0353
fedorova.tanya@gmail.com
skype: tanyafdrva
http://ru.linkedin.com/in/tatianafedorova
https://www.facebook.com/tatiana.fedorova
@fetati

See also:
SVOD Conference
www.svod.org

AmBAR
www.ambarclub.org

**Comment by RealBerd** [comment]
Где ты вязала браузер ÷ èÒÏÍÅ É óÁÆÁÒÉ ? :)

**Comment by Fetati** [comment]
Так, судя по всему гитхаб русский не любит)))
Safari and Chrome

Best regards,
Tanya Fedorova

+1 (650) 296-0353
fedorova.tanya@gmail.com
skype: tanyafdrva
http://ru.linkedin.com/in/tatianafedorova
https://www.facebook.com/tatiana.fedorova
@fetati

See also:
SVOD Conference
www.svod.org

AmBAR
www.ambarclub.org

**Comment by RealBerd** [comment]
![6ghblnq](https://cloud.githubusercontent.com/assets/2241165/2624160/4127948a-bd26-11e3-9502-9cba8f64b163.png)
Хитрый чекаут спртался под слоями!
FF28

Баг всё ещё жив.

**Comment by DmitrysIF** [comment]
Еще не исправлено. В процессе.

**Comment by DmitrysIF** [comment]
Исправлено. В деплое.

**Comment by DeveloperRegistry** [comment]
Tanya, please retest once the fix is deployed.

**Comment by Fetati** [comment]
Спасибо! Все отлично.
