### ISSUE TITLE
UX: Do we allow user to save, edit, create user name that has capital letters in it?

### ISSUE THREAD

**Issue by ghost** [Goodler/code#100]
I am able to change the handle/user name, but not create/change by using capital letters!
Are we allowing user to do so?

**Comment by DmitrysIF** [comment]
Заглавные буквы в юзернейме можно использовать при создании аккаунта? Я просто не помню.

**Comment by DmitrysIF** [comment]
Хорошо, я задеплою вариант, в котором можно использовать capital letters в username. Его нужно будет хорошо протестировать, протестировать все, что может быть связано с username
