### ISSUE TITLE
No image for project (was tested in Safari and Chrome at the same time) 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#101]
not sure what is the problem, maybe network and issue is temp, bcs it work before
Time: 3:15 - 3:20 Sat. April 19

**Comment by ghost** [comment]
![no profile for project](https://cloud.githubusercontent.com/assets/7193843/2749601/aa08c2b8-c810-11e3-9bcd-3bebd3699bf0.png)
![no project photo](https://cloud.githubusercontent.com/assets/7193843/2749602/aa09acf0-c810-11e3-8239-3c635e5a3837.png)

**Comment by DmitrysIF** [comment]
Проблемы с сервисом. Изучаем.

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/7193843/2749684/86a84042-c819-11e3-9a12-58276aced123.png)

**Comment by ghost** [comment]
hehe

**Comment by DmitrysIF** [comment]
Похоже, что все же проблемы именно с сервисом :(
Не понимаю пока - по какой причине он не дает доступа к нашим старым картинкам.
Новые картинки грузятся без проблем.

**Comment by DmitrysIF** [comment]
В общем - пока лечение состоит в следующем: 
Удалять нерабочие картинки и загружать новые.

**Comment by DmitrysIF** [comment]
Отставить... 
Картинки снова пропали. Очень грустно.
Ничего не делайте со старыми картинками, пока не решу вопрос с Никитой.

**Comment by DmitrysIF** [comment]
Так, я хочу попросить вас продолжать работать с картинками в обычном режиме. Неработающие картинки прошу заменить на работающие. Если это повторится, будем думать дальше.

**Comment by DmitrysIF** [comment]
Все, проблема решена! Старые картинки, к сожалению, уже не вернуть - но новые картинки больше не пропадут! :)
