### ISSUE TITLE
When user creates Donee and uploads picture, it shown in landscape mode, not a portrait

### ISSUE THREAD

**Issue by ghost** [Goodler/code#103]
I
![rotate option](https://cloud.githubusercontent.com/assets/7193843/2749666/271f40be-c817-11e3-96ea-5d98ebe87076.png)
s it possible to have the option to rotate or load in portrait mode?

**Comment by DmitrysIF** [comment]
Нет. С этим вопросом обращайтесь к Никите лично.

**Comment by ghost** [comment]
@RealBerd this issues is seen in Chrome. Safari, Firefox seems to work fine

**Comment by DmitrysIF** [comment]
Кстати - это уже дубль, вопрос такой был. Но там " и только мертвые с косами стоят"

**Comment by ghost** [comment]
hehe, got it, close if dupe, but we need to make sure we keep original and do not put in backlog, it uploads fine, but user will be confused if he sees this.

**Comment by DmitrysIF** [comment]
Закрывать пока не надо.

**Comment by DmitrysIF** [comment]
Предложено перенести это на следующий этап разработки - Release 2
