### ISSUE TITLE
If user signs out cart still has items- should be 0

### ISSUE THREAD

**Issue by ghost** [Goodler/code#104]
sing in, add items to your card, sign out

Bug: cart still has items listed
![sing in cart](https://cloud.githubusercontent.com/assets/7193843/2749761/a779e3ea-c821-11e3-947a-a39af77c6b5f.png)

**Comment by DmitrysIF** [comment]
Это не баг - такова задумка, которая позволит навыбирать позиций себе в корзину и когда он попытается купит это - пользователю предложат зарегистрироваться одновременно с оплатой. За дополнительными разъяснениями обращаться к Никите.

**Comment by ghost** [comment]
@Fetati can you resend me payment info so i can test with exp date and CVC code and card number

**Comment by DmitrysIF** [comment]
тестовые данные для тестовых платежей:
 4242 4242 4242 4242 
любая валидная дата и любой CVV из трех цифр

**Comment by DmitrysIF** [comment]
Еще актуально?

**Comment by ghost** [comment]
@Fetati @DmitrysIF I understand the flow if user is a guest and adds items to a cart and then click Check out and prompt to sign up and pay, but in this case user signed up, adds items, sign out, and cart still has items
Expected flow would be: sign up, add items, sign out -> cart goes to 0, and once that user sign in again -> cart should be updated (cart shoube remember the user) to whatever user had when sign out.

BUT i am not sure if this is the plan or if we have capacity to do that. @Fetati what do you think?

**Comment by Fetati** [comment]
Я согласна с Тамарой. Надо это исправить. Не должно быть так. Задумка была в том, что человек ДО регистрации может уже начать что-то бросать в корзину. Но ничего не должно оставаться видным, если человек sign out.

**Comment by DmitrysIF** [comment]
А вот тут зовите Никиту и обсуждайте это.
Если сделать так - как вы считаете нужным сейчас, то придется очень много переделывать.

**Comment by RealBerd** [comment]
Дима, можешь просто отчистить куку при SingOut?
