### ISSUE TITLE
user is still logged after signing out and tapping Check out

### ISSUE THREAD

**Issue by ghost** [Goodler/code#105]
Steps:
1. sign in ( u can add items to a cart if you want)
2. sign out
3. tap Check out btn

Bug: user redirected to to profile and logged in again
Expected: user should be redirected to sign in page for security purposes

Note : all web browsers have this issues. And password was not remembered by web as well . In all web browsers it was specified not to remember the p/w

**Comment by DmitrysIF** [comment]
Прошу ко всем дополнительным вопросам вызывать Никиту :)
Он сейчас не часто сюда смотрит.

**Comment by Fetati** [comment]
@DeveloperRegistry Антон, что думаешь по этому поводу?

**Comment by DeveloperRegistry** [comment]
Dima and Nikita, it is definitely a Security Defect. If I am signed out, I should not be automatically logged back in. We need to researched what variables are cached and why this happens. We need to reset all variables after signing out. Lets discuss when you have time.

**Comment by RealBerd** [comment]
Checkout достуен без сайнина.
Как воспроизвести баг?

**Comment by DmitrysIF** [comment]
@TShket баг не воспроизводится.
