### ISSUE TITLE
Очепятка

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#106]
http://gooddler.cloudapp.net/Admin/Donees
Текст кнопки - Createa a New Donee - должно быть Create, убрать A в конце
![screen shot 2014-04-21 at 11 30 10 am](https://cloud.githubusercontent.com/assets/4335901/2757290/16a7d292-c983-11e3-8522-9155ad266552.png)

**Comment by DmitrysIF** [comment]
Хорошо! Через несколько часов можно будет проверять правки.
