### ISSUE TITLE
Create Donee: Eror - should be red color

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#107]
Надо сделать заметным сообщение об ошибке - к примеру красным цветом и крупнее шрифт. 
И исправить текста на: Status Message: Error. Please fill in all fields required.

![screen shot 2014-04-21 at 11 39 59 am](https://cloud.githubusercontent.com/assets/4335901/2757445/97bd0784-c984-11e3-9d77-3387f1c9ec58.png)

И еще, там http:\ - должны быть палочки в другую сторону - http://

**Comment by DmitrysIF** [comment]
Исправлено.
