### ISSUE TITLE
Create Donee: Add Create Wishlist Button 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#108]
Примерно так (только без ошибки в тексте кнопки: Create a Wishlist)
![desktop5](https://cloud.githubusercontent.com/assets/4335901/2757777/094b218a-c988-11e3-9fdc-26437e046a17.jpg)

**Comment by DmitrysIF** [comment]
Сделать доступным только для участников дони и суперадминов?

**Comment by Fetati** [comment]
Äëÿ âñåõ àäìèíèñòðàòîðîâ/âëàäåëüöåâ donee.

**Comment by DmitrysIF** [comment]
Извиняюсь - вижу кракозяблы :)

**Comment by Fetati** [comment]
Sorry. :) 

Any donee administrator (super-  and lyuboy drugoy) should see this button.

**Comment by DmitrysIF** [comment]
Хорошо. Это можно будет "потрогать" сегодня.

**Comment by DmitrysIF** [comment]
Выполнено

**Comment by Fetati** [comment]
Куда-то пропала кнопка Create Wishlist. Точнее она есть, если подвести мышь в то место, где она была. Но ее не видно, если мышь не подводить. (Chrome) http://gooddler.cloudapp.net/Donee/30042

![screen shot 2014-04-24 at 2 17 49 pm](https://cloud.githubusercontent.com/assets/4335901/2795150/1bea2b0e-cbf6-11e3-998b-0f2cac4a78c9.png)

вот что видно, если мышь подвести:

![screen shot 2014-04-24 at 2 18 10 pm](https://cloud.githubusercontent.com/assets/4335901/2795156/2d11bd16-cbf6-11e3-824a-c3319532fd5b.png)

**Comment by DmitrysIF** [comment]
Исправлено.
