### ISSUE TITLE
Create Wishlist: не добавляется товар

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#109]
Товары не добавляются в вишлист (в Chrome). Попробовала два: http://www.amazon.com/dp/B00000IWDP/ref=wl_it_dp_v_nS_ttl?_encoding=UTF8&colid=1GD60SU1ZOIHM&coliid=I3IAAOB0NGH0JM

и http://www.amazon.com/dp/B004X0WBHS/ref=wl_it_dp_v_nS_ttl?_encoding=UTF8&colid=1GD60SU1ZOIHM&coliid=I2BAQ1RE3QH67R

**Comment by Fetati** [comment]
Эти товары были из амазоновского вишлиста. Когда просто скопировала название, и вставила в поиск на амазоне, а потом найденный линк вставила в Gooddler, то все заработало.

**Comment by DmitrysIF** [comment]
Есть проблема, которая заключается в том, что логика построения амазоновской ссылки различается и парсер не может выловить айдишник товара типа "B00000IWDP". Вопрос будет решен.

**Comment by DmitrysIF** [comment]
Исправил ошибку с amazon-urls (возможно, есть еще какой-нибудь амазон-адрес, который не обработается по текущим шаблонам - о таких прошу сообщать), проапрейдил показ ожидания обработки данных для добавления товара.
