### ISSUE TITLE
Wishlist: странный значок на фотке

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#110]
![wishlist_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2760759/9eacbdf6-c9bf-11e3-81f6-c87c73a338e4.png)

**Comment by DmitrysIF** [comment]
Да, я тоже его увидел - собирался исправлять :)

**Comment by DmitrysIF** [comment]
Исправил - проверьте, пожалуйста, стали ли нормально показываться серые иконки гуддлера?
