### ISSUE TITLE
Create Wishlist: Очепятка 2 и корректировка

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#111]
http://gooddler.cloudapp.net/Wishlist/Create/30042
Сейчас: Enter descriptiopn 
Надо: Enter Description

Сейчас: Enter Name
Надо: Enter Name of a Wishlist

Убрать знаки вопроса.

![screen shot 2014-04-21 at 6 22 37 pm](https://cloud.githubusercontent.com/assets/4335901/2760787/6427019a-c9c0-11e3-9f40-baa9f005eb13.png)

**Comment by DmitrysIF** [comment]
Fixed
