### ISSUE TITLE
"Delete Wishlist" Button: "Are you sure you want to delete this wishlist?"

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#112]
Обязательно надо сделать, чтобы ДО окончательного удаления вишлиста сайт переспрашивал, действительно ли я хочу это сделать. А то 2 кнопки Update Wishlist и Delete Wishlist рядом, очень просто промахнуться, и не возможно вернуть ошибку обратно.

Текст:
"Are you sure you want to delete this wishlist? You will not be able to retrieve it."

**Comment by Fetati** [comment]
Давайте изменим кнопку Delete Wishlist на бледный линк, типа как [sign out] линк. 
А то уже вот в который раз чуть не нажала на нее, вместо Update Wishlist при изменении вишлиста.

**Comment by DeveloperRegistry** [comment]
Dima, you can re-assign it to me if you do not have time.

**Comment by DmitrysIF** [comment]
*Давайте изменим кнопку Delete Wishlist на бледный линк, типа как [sign out] линк. *
Это будет быстро. Будет в следующем обновлении. Антон - я справлюсь.

**Comment by DeveloperRegistry** [comment]
Spasibo, Dima!

**Comment by DmitrysIF** [comment]
Переделано - надеюсь, вам понравится мое решение :)

**Comment by Fetati** [comment]
Не понравилось, сори, Дима.
Надо сделать точно также, как и Delete Donee. Смотри issue #149 
![screen shot 2014-04-27 at 5 59 27 pm png](https://cloud.githubusercontent.com/assets/4335901/2814046/54cdbfec-cea0-11e3-977f-a1d110b37bd8.jpg)

**Comment by DmitrysIF** [comment]
Исправлено.
