### ISSUE TITLE
Create Wishlist: Field for Amazon link

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#114]
При начале заполнения вишлиста нет поля для линка с амазона. А надо бы. Нелогично возвращаться в Edit Wishlist и не давать людям сразу заполнить список товаров. Давайте сделаем это поле сразу.
http://gooddler.cloudapp.net/Wishlist/Create/30042
![screen shot 2014-04-21 at 7 34 50 pm](https://cloud.githubusercontent.com/assets/4335901/2760993/ee3839d4-c9c6-11e3-9e20-a0d31fb1ed26.png)

**Comment by DmitrysIF** [comment]
Тут возникает проблема курицы и яйца:
Список товаров зависит от вишлиста (это отдельная таблица), но этот список должен иметь в своем составе айдишник вишлиста - но его еще нет, так как пользователь не создал вишлист.
Пришлось решить проблему таким образом.

**Comment by DmitrysIF** [comment]
В данный момент я предлагаю перенести эту доработку на будущий Release 2.

**Comment by Fetati** [comment]
согласна
