### ISSUE TITLE
Post: автоматически?

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#115]
Вот такие посты делаются автоматически? Надо тексты для автоматических постов?
![screen shot 2014-04-21 at 8 41 30 pm](https://cloud.githubusercontent.com/assets/4335901/2761270/2a218078-c9d0-11e3-99fb-9f5ced4cdd90.png)

**Comment by DmitrysIF** [comment]
Да, они делаются автоматически. Было бы очень хорошо получить тексты для автоматического поста и, я так думаю - будет очень здорово получить текст письма, который будет будет извещать пользователя, что о нем написали новый отличный пост.

**Comment by Fetati** [comment]
@DmitrysIF: Дим, какие типы постов у нас есть?
1) From Donor to Donee
2) From Donor to Wishlist
3) From Donee to Donor
4) From Wishlist to Donor
5) Абстрактный текс от любого юзера

Что еще?

**Comment by DeveloperRegistry** [comment]
What about General Announcements from Admin users?

**Comment by DmitrysIF** [comment]
1) From Donor to Donee
2) From Donor to Wishlist
Донор не может писать ни в чей адрес.
В адрес дони и вишлиста может писать только администратор и менеджеры дони.
А так же суперадмины.

**Comment by galinafed** [comment]
Dima, I didn't understand it:

You say Donor to Donee, but say that Donor can't write to anyone?

**Comment by Fetati** [comment]
По идее должно быть:
от Donee к Donor - donee пишет благодарность донору за помощь, отчет о доставке товаров, и пр
от Admin к Wishlist - администратор пишет спасибо всем донорам, что помогли собрать нужные товары, отчет о доставке (фотографии и пр). 
Что еще?

Насколько я понимаю, эти посты будут видны всем? Тогда главная цель постов - фидбек на сделанные пожертвования. Те, кто читают посты, должны знать, что товары доставляются по адресу и они приностя пользу.

**Comment by DmitrysIF** [comment]
В принципе так и есть, вы перечислили все текущие возможности адресации сообщения.
Эти сообщения видны всем.

**Comment by galinafed** [comment]
Donee to Donor makes total sense.

**Comment by galinafed** [comment]
I shared document with thank you posts. Anything else on this one?
