### ISSUE TITLE
How do we user Location information with Users, do we display it somewhere, why do we have it?

### ISSUE THREAD

**Issue by ghost** [Goodler/code#116]

**Comment by ghost** [comment]
edit profile flow

**Comment by DmitrysIF** [comment]
Я считаю это заделом на будущее. 
Не нужно стараться прямо сейчас сделать все на свете - для этого придумали разделение разработки на этапы :)
Возможно, мы в Release 2 решим, как это использовать.

**Comment by DmitrysIF** [comment]
В принципе - мы можем скрыть это поле до лучших времен.

**Comment by Fetati** [comment]
Надо не Location, а скорее адрес для подтверждения кредитной карты. @DeveloperRegistry, можешь помочь с этим вопросом, плиз.

**Comment by DeveloperRegistry** [comment]
Yes, I am going to add Name and Address to the credit card processing form. However, we probably do not want to store user data in Gooddler's database  to minimize impact from hacker attacks. Should we hide this field?

**Comment by Fetati** [comment]
Yes, let's hide it.

**Comment by DmitrysIF** [comment]
В следующем обновлении.

**Comment by DmitrysIF** [comment]
Убрано.
