### ISSUE TITLE
user unable to sign up- gives error 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#117]
![cant create user](https://cloud.githubusercontent.com/assets/7193843/2773540/0ea023da-ca9e-11e3-9b7d-155937f277aa.png)

**Comment by DmitrysIF** [comment]
как воспроизвести ошибку?

**Comment by DmitrysIF** [comment]
Ошибка еще есть?

**Comment by DmitrysIF** [comment]
Прошу хотя бы отвечать на мои реплики, а то складывается впечатление, что тут хоть шаром прокати)

**Comment by Fetati** [comment]
@TShket протестируй еще раз, плиз. Работает сейчас?

**Comment by Fetati** [comment]
В Safari работает.
Димочка, только убери знаки вопросов, плиз.

![screen shot 2014-04-27 at 6 51 13 pm](https://cloud.githubusercontent.com/assets/4335901/2812966/b2071664-ce77-11e3-8b89-9c99d6e98a1c.png)

**Comment by DmitrysIF** [comment]
Хорошо, сделаю.
Но я все же попытаюсь улучшить функцию, которая отвечает за sign up пользователей. 
Раз выстрелила ошибка - значит где-то что-то не так работает или может не так работать.

**Comment by DmitrysIF** [comment]
Закончил
