### ISSUE TITLE
Text: Correction 3

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#121]
Убрать слово Donator. 
И убрать все знаки вопроса. И так понятно, что это.

![screen shot 2014-04-22 at 9 53 23 pm](https://cloud.githubusercontent.com/assets/4335901/2773695/453db380-caa3-11e3-981a-51bbc5dc6fb1.png)

**Comment by DmitrysIF** [comment]
Почему убрать? Я считаю - это очень полезным, не дает забыть - в чей адрес пишется сообщение! Плюс, можно понять - кому пишешь (рядом с Донатором надписи еще могут быть): 
Просто пользователю, пользователю в ответ на конкретный донейшен, просто вишлисту, просто дони.
Сменить Donator на Donor - я согласен :)

**Comment by Fetati** [comment]
ладно, согласна. 
Смени на Donor. Какие тексты еще могут быть тут? Напиши по-русски, я пришлю тексты на английском.
Пользователь = donor?

**Comment by DmitrysIF** [comment]
Хм, может сделать так - если пишется просто пользователю, то просто вместо Donor писать "for User"?
Какие надписи еще могут быть В добавок к Donor:
Donee: ...;
Wishlist: ...;
Donation: ...;
Про donation пишется количество перечисленных денег, дата платежа.

**Comment by DmitrysIF** [comment]
Если все правки по этому таску завершены - закрываем :)

**Comment by Fetati** [comment]
Нет, не завершены еще, подожди, я протестирую
