### ISSUE TITLE
Donee Page: change a place for Wishlist description

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#122]
Дим, текст должен быть не под картинкой, а под заголовком. Должно не выпадать дальше картинки. Цель - заполнить пустое пространство у картинки. 
http://gooddler.cloudapp.net/Donee/10017

![screen shot 2014-04-24 at 1 05 16 pm](https://cloud.githubusercontent.com/assets/4335901/2794380/f851a76c-cbeb-11e3-9915-3737a1017901.png)

**Comment by DmitrysIF** [comment]
Завершено.
