### ISSUE TITLE
Стрелки прокрутки маленькие

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#124]
Дим, мы уже как-то это меняли, а опять выглядит так, что стрелки прокрутки из старого дизайна - они маленькие, и полоса прокрутки вверх-вниз браузера перекрывает правые стрелки так, что не возможно на них нажать. Таня Раш как-то уже меняла это. Проверь, пожалуйста:

![screen shot 2014-04-24 at 6 59 48 pm](https://cloud.githubusercontent.com/assets/4335901/2796960/bc20aebe-cc1d-11e3-837e-0bafb229752b.png)

**Comment by DmitrysIF** [comment]
Очень странно - насколько я помню, я с ними вообще ничего не делал с момента установки шаблона этой страницы. Я посмотрю.

**Comment by Fetati** [comment]
В том то и дело, что шаблон изначально вставили не тот. Поэтому и есть список корректировок, которые ты уже частично поправил.

Мы утверждали вот этот. Тут и стрелки, и меню, и посты, и все так, как нам надо:

![04_main](https://cloud.githubusercontent.com/assets/4335901/2805409/5be97f9e-ccb8-11e3-8e89-e03c3b7cb27f.jpg)

**Comment by RealBerd** [comment]
Дима, подключи, пожалуйста Колю для этого таска.

Нужно чтобы стрелочки были ровно посередине панели. И чтобы они были большие.

Спасибо!

**Comment by DmitrysIF** [comment]
Стрелки прокрутки заменены.
