### ISSUE TITLE
Donee Page: выглядит по-разному если sign-in и если нет

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#125]
Donee Page выглядит по-разному если sign-in и если нет. Оба варианта надо править - я писала об этом уже. Но в любом случае, должно быть одинаково. Дизайн не должен ехать в зависимости от того залогинен человек или нет.

Я залогинена (см. на вишлисты):

![screen shot 2014-04-24 at 7 30 48 pm](https://cloud.githubusercontent.com/assets/4335901/2797130/dcc78a12-cc21-11e3-83ef-509235fee71d.png)

Вот я не залогинена:

![screen shot 2014-04-24 at 7 30 29 pm](https://cloud.githubusercontent.com/assets/4335901/2797131/f1c02546-cc21-11e3-8dd1-8ed9359a06aa.png)

**Comment by DmitrysIF** [comment]
Я проверю.

**Comment by DmitrysIF** [comment]
Сделано.
