### ISSUE TITLE
Posts about particular Donee: change a title

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#128]
http://gooddler.cloudapp.net/Blog/Posts?doneeid=30042
В списке постов по конкретному Donee надо поменять название "Posts" на "Gooddlers are saying about ____(Donee Name):" (с линком на данного Donee)

![screen shot 2014-04-24 at 9 19 28 pm](https://cloud.githubusercontent.com/assets/4335901/2797527/e16c3144-cc30-11e3-9667-97a1aecac3f7.png)

**Comment by DmitrysIF** [comment]
Сделано.
