### ISSUE TITLE
Create New Post - wrong button, no sense

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#129]
http://gooddler.cloudapp.net/Admin/Posts

Menu/My Posts/Create New Post
В списке постов есть кнопка Create New Post, которая ни к чему не привязана (ни к донору, ни к donee, ни к вишлисту), возможно, что поэтому невозможно создать этот пост.

![screen shot 2014-04-24 at 9 26 28 pm](https://cloud.githubusercontent.com/assets/4335901/2797559/11200f72-cc32-11e3-8674-38523fa4ab2a.png)

**Comment by DmitrysIF** [comment]
Нам нужна эта кнопка? Или ее можно убрать, если нет фильтрации по конкретному дони, вишлисту?

**Comment by Fetati** [comment]
Я не вижу смысла в этой кнопке, тем более если она не работает. Убираем.

**Comment by DmitrysIF** [comment]
Работоспособность кнопки восстановлена.
