### ISSUE TITLE
"My GOODdler" Drop down menu overlaps the Gooddler icon (Safari, Chrome, Firefox)

### ISSUE THREAD

**Issue by ghost** [Goodler/code#13]
Steps:
1. tap the "My Gooddler" menu and observe the drop down menu 
2. Move sign in down so drop down menu does not overlap 
![screen shot 2014-04-06 at 4 57 51 pm](https://cloud.githubusercontent.com/assets/7193843/2626802/7d2c0db4-bde7-11e3-8240-26430b10c6be.png)

Bug: overlaps with main icon
![screen shot 2014-04-06 at 4 21 47 pm](https://cloud.githubusercontent.com/assets/7193843/2626797/fbccff1c-bde6-11e3-96fb-42e8e66d1b2b.png)

**Comment by DmitrysIF** [comment]
Подвинул.
