### ISSUE TITLE
" Good " , " Ok " should be aligned with password field

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#131]
![screen shot 2014-04-26 at 10 43 17 am](https://cloud.githubusercontent.com/assets/7408823/2809382/71fdf32e-cd6b-11e3-9154-13256867d10e.png)

check out as a guest flow

**Comment by DmitrysIF** [comment]
Так в чем проблема? Мне непонятно. Что значат Good/Ok?
В каких случаях они должны выводиться?

**Comment by Fetati** [comment]
Там съехало все, посмотри на картинку.

**Comment by RealBerd** [comment]
Дима, обратись к Коле по этому багу.

**Comment by DmitrysIF** [comment]
Съезжание поправлено.
