### ISSUE TITLE
When user taps FB,TW,G+, icon it gives error 

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#133]
![screen shot 2014-04-26 at 11 14 56 am](https://cloud.githubusercontent.com/assets/7408823/2809433/fe37fe86-cd6e-11e3-97ca-af71af0e65a2.png)

![screen shot 2014-04-26 at 11 18 05 am](https://cloud.githubusercontent.com/assets/7408823/2809439/27c533ae-cd6f-11e3-8f01-aa2635c2632f.png)

If link is not ready let QA know when it's ready for testing.Thank you.

**Comment by DmitrysIF** [comment]
Ссылочки, на которые должны вести эти кнопки - в студию! И они будут подключены :)

**Comment by Fetati** [comment]
Facebook: https://www.facebook.com/gooddler
Twitter: https://twitter.com/GOODDler
G+: https://plus.google.com/+Gooddler/

**Comment by DmitrysIF** [comment]
Нет ссылки на ютуб

**Comment by DmitrysIF** [comment]
Так же нету страницы "Help" - нужен текст

**Comment by Fetati** [comment]
We don't have YouTube.

**Comment by DmitrysIF** [comment]
Тогда я закомментирую эту иконку - когда будет ютуб у нас, то вернем на место.
