### ISSUE TITLE
Help info for FB,IN, TW link is misplaced

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#134]
Go to profile try to enter info in to FB,TW field and observe help info
1. FB link should be placed lower under the cell
2. IN and TW is misplaced

![screen shot 2014-04-26 at 11 31 47 am](https://cloud.githubusercontent.com/assets/7408823/2809539/bafc418a-cd74-11e3-8bc4-1f45ff9e5ca2.png)

![screen shot 2014-04-26 at 11 31 43 am](https://cloud.githubusercontent.com/assets/7408823/2809540/c19e776a-cd74-11e3-9c37-717346a23774.png)

**Comment by DmitrysIF** [comment]
Да, замечено - решается.

**Comment by DmitrysIF** [comment]
Исправлено.

**Comment by Elenarussian** [comment]
@DmitrysIF do we plan to change info under links?
because right now we see IN info under TW
TW under Linked in cell. 
FB is correct

**Comment by DmitrysIF** [comment]
Исправлено
