### ISSUE TITLE
User unable to delete a post

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#135]
![screen shot 2014-04-26 at 12 29 53 pm](https://cloud.githubusercontent.com/assets/7408823/2809619/470bccaa-cd79-11e3-9cb6-d1dc2c4b0312.png)
1. Create donee
2. Make a posts
3. Try to delete

**Comment by DeveloperRegistry** [comment]
Can you confirm that you tried to delete a post for the Donee that you own? The functionality definitely works if you have an Admin role (just tested). However, it can be different for regular users. Do you get any error messages?

**Comment by Elenarussian** [comment]
I don't get any error messages. When you click  a delete button it doesn't do anything at all.
What would be the other way to confirm?

**Comment by DeveloperRegistry** [comment]
I just created a new User Account (no Admin rights). Created a new Donee and Post. I was able to Delete it. The only check that code executes: your User Id need to be a Donee owner or you need to be an Admin. I used Chrome. What browser do you use? 

Try to create a New Donee, new post and delete one more time.

**Comment by Elenarussian** [comment]
Ok i will try.
I use Safari .

**Comment by Elenarussian** [comment]
i still can't delete posts

**Comment by DeveloperRegistry** [comment]
Fixed by Dima. Please note that you have to be the Post's Author to delete or have an Admin Role.
