### ISSUE TITLE
user unable to add picture to wishlist 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#136]
create Donee
create new wish list
upload picture for wishlist
picture uploads only till 98 or 96% 
Maybe network issues or picture size 
will re test later, but file anyway
![wishlist pics](https://cloud.githubusercontent.com/assets/7193843/2809658/ed9f3e20-cd7a-11e3-91e8-c944165510a8.png)

**Comment by DmitrysIF** [comment]
А что сделать-то нужно? Непонятна проблема.

**Comment by Fetati** [comment]
У меня все закачивается. @TShket Тамара, уточни проблему
