### ISSUE TITLE
is the Term, Help page ready?

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#137]
![screen shot 2014-04-26 at 12 53 15 pm](https://cloud.githubusercontent.com/assets/7408823/2809672/6f40b688-cd7c-11e3-8193-7ec49fe79b69.png)

![screen shot 2014-04-26 at 12 56 23 pm](https://cloud.githubusercontent.com/assets/7408823/2809683/119f4f0c-cd7d-11e3-9461-fd18f8ab13b7.png)

**Comment by Fetati** [comment]
Terms - сделано.
Help - not ready yet. I'll send a text soon.

**Comment by DeveloperRegistry** [comment]
How To page is implemented.
