### ISSUE TITLE
When user adds items "Count" area should be updated to "count" , currently it has number of previous item

### ISSUE THREAD

**Issue by ghost** [Goodler/code#138]
create Donee
Add items to wish list
observe the field where user enters the amount of items after  you added one item

Bug: number from previous
![count updated](https://cloud.githubusercontent.com/assets/7193843/2809722/b0584782-cd7f-11e3-80f1-d50fea40b847.png)
![count](https://cloud.githubusercontent.com/assets/7193843/2809723/b06bf5de-cd7f-11e3-9cfc-013465928a7d.png)

 item is shown
Expected: it should go back to "Count"

**Comment by DmitrysIF** [comment]
Понял - сейчас сделаю обнуление.

**Comment by DmitrysIF** [comment]
Переделал :)
