### ISSUE TITLE
Scroll down bar blocks user from scrolling projects

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#139]
![scroll bar](https://cloud.githubusercontent.com/assets/7408823/2809724/c6a20a96-cd7f-11e3-946d-ecb8ccc132df.png)

**Comment by Fetati** [comment]
Проблема описана в #124

**Comment by DmitrysIF** [comment]
Ввиду особенности операционной системы MacOS, которая накладывает скроллбары поверх страницы (а не рядом, как в других системах)- было принято решение чуть-чуть подвинуть кнопки, чтобы они не закрывались скроллбаром.
Если результат не устроит - открывать новый issue

**Comment by DmitrysIF** [comment]
Почему он снова открыт? В чем причина?
