### ISSUE TITLE
Price reflected incorrect (Amazon vs Gooddle) 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#141]
add items to wishlist from Amazon
notice
![price 31](https://cloud.githubusercontent.com/assets/7193843/2809762/b0f1a91a-cd82-11e3-9ede-35c5502fca47.png)
![price](https://cloud.githubusercontent.com/assets/7193843/2809763/b0f2a7e8-cd82-11e3-8408-fb6be5564ae4.png)

 the price on Amazon and then on Gooddler

**Comment by DmitrysIF** [comment]
Выбирается средняя амазоновская цена данного лота.
Нет возможности выбрать цену конкретного лота.
