### ISSUE TITLE
User shouldn't  be able to insert their own number into the cell

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#144]
![aaaaaaa](https://cloud.githubusercontent.com/assets/7408823/2809865/0c620172-cd89-11e3-88eb-9e33664fd264.png)

![screen shot 2014-04-26 at 2 23 05 pm](https://cloud.githubusercontent.com/assets/7408823/2809866/0f7cf362-cd89-11e3-8d53-9a8dd02c3b04.png)

**Comment by DmitrysIF** [comment]
Это сделано в целях совместимости с браузерами, которые не поддерживают Html5, в таком случае будет просто поле для ввода числа без кнопок больше-меньше.
Стоит защита от записи в корзину больше, чем доступно для пожертвования - просто выставится максимально доступное количество.

**Comment by DmitrysIF** [comment]
Убрал возможность редактирования с клавиатуры

**Comment by Elenarussian** [comment]
@DmitrysIF , Dima , can we keep the number in the cell and allow user to use only arrows ?
e.g. min would be 0 and max is whatever is set up by Donee. keeping the cell empty looks weird. Maybe we should not allow user to delete number, just keep it static with min 0. if possible, if its to much we can stick with whatever we have now.

**Comment by DmitrysIF** [comment]
Не понимаю - пользователь и так сейчас не может вручную вводить данные в эти ячейки!
Если вы по прежнему можете вводить данные с клавиатуры и вообще всячески редактировать их - сообщите название и версию вашего браузера.

**Comment by Elenarussian** [comment]
i can't enter - it works fine
but i can delete the number and the cell look empty - which is fine, but not the best
i was hoping we can keep the at least 0 and not allow user to delete it at all.
if its too much, we fine with what we have now
Thank you

**Comment by DmitrysIF** [comment]
@Elenarussian установлен полный запрет на ручное редактирование этих полей.
