### ISSUE TITLE
Complete project still has one item for donation

### ISSUE THREAD

**Issue by ghost** [Goodler/code#146]
![finished](https://cloud.githubusercontent.com/assets/7193843/2809913/45c346c6-cd8c-11e3-9d1e-9f30ef0ed074.png)

**Comment by RealBerd** [comment]
"Вот тут надо будет запретить уменьшать количество товара меньше закупленного уже"

Всё верно?

**Comment by DmitrysIF** [comment]
Исправлено - теперь нельзя задать количество необходимого "товара" при редактировании меньше, чем уже было "куплено". Чтобы не мозолило глаза то, что есть уже (я про неправильные показания куплено/необходимо) измените их вручную в режиме администратора при редактировании вишлиста.
