### ISSUE TITLE
Wording should be changed on Create Donee page

### ISSUE THREAD

**Issue by ghost** [Goodler/code#147]
" use a subdomain of goodler.com" is a very confusing phrase for regular users

i would change it to " Personalise your GOODdler webpage"
or something more simple.

@Fetati you call
![subdomane](https://cloud.githubusercontent.com/assets/7193843/2809969/38d37eaa-cd90-11e3-9cea-1e93a198d71b.png)

**Comment by Fetati** [comment]
It was taken from Wordpress or Weebly or something like this. If you think it is confusing, let's change it for something more appropriate.

**Comment by DmitrysIF** [comment]
Нужен утвержденный Title этой функции для замены.

**Comment by Fetati** [comment]
Предлагаю сделать так, как на Weebly:
![screen shot 2014-04-27 at 6 18 45 pm](https://cloud.githubusercontent.com/assets/4335901/2812861/1e71b32c-ce73-11e3-9620-45367177946e.png)

Title:
1 строка: Choose Your Website Domain - крупный шрифт, как заголовок у страницы

2 строка: Use a Subdomain of Gooddler.com - жирным
Hint: This is the address where people will find your website online

3 строка: 
http://  ____поле_____  gooddler.com
Дима, обрати внимание, как в картинке выше отцентрировано все. Пробелы, и пр.
У тебя тут // в другую сторону, и подвинь немного в сторону от бокса тексты
![screen shot 2014-04-27 at 6 27 30 pm](https://cloud.githubusercontent.com/assets/4335901/2812889/8569884c-ce74-11e3-98ba-826e365d1782.png)

Еще, исправь текст на Enter Description
У тебя очепятка (http://gooddler.cloudapp.net/Donee/Edit/10033):
![screen shot 2014-04-27 at 6 29 42 pm](https://cloud.githubusercontent.com/assets/4335901/2812897/b93ebce6-ce74-11e3-8d3a-2f094e3f310b.png)

**Comment by DmitrysIF** [comment]
Исправлено.
