### ISSUE TITLE
" List Wishlist " and " View Wishlist " shouldn't be opened in new window 

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#148]
1. click  " My Wishlist "
2. click  Wishlist name 
3. click " List Wishlist " or " View Wishlist "

Bug: opens new window (user ends up with lots of open windows) 
Expected: It should be opened in the same window

**Comment by DmitrysIF** [comment]
@Elenarussian  Так и должно быть, мы не должны уводить человека со страницы редактирования - он в этот момент может делать какие-то правки и кликнуть данные ссылки не применив изменения. Что обернется потерей измененных данных.
