### ISSUE TITLE
UI: IS there a way for users to delete their DOnees?

### ISSUE THREAD

**Issue by ghost** [Goodler/code#149]

**Comment by DeveloperRegistry** [comment]
Yes, you just need to have an admin role. I granted admin role to user 'hellot'. Log out and log back in. Let me know if Admin role needs to be granted to a different user. You should be able to Delete Donees, Wishlist and Posts.

**Comment by Fetati** [comment]
Мне не нравится, как реализовано Delete Donee сейчас
1) Текст должен быть серым, как у "How It Works" или "Sign Out"
2) Расположить этот линк надо под Update Donee. Примерно так:
![screen shot 2014-04-27 at 5 59 27 pm png](https://cloud.githubusercontent.com/assets/4335901/2812828/cdf47fe4-ce70-11e3-8e5b-6ec3732438f4.jpg)

3) Hint тут не нужен. Надо после нажатия на линк Delete Donee сделать pop-up - переспросить "Are you sure you want to delete this Donee? You will not be able to retrieve it."  Хинт - это подсказка, что значит данная кнопка.

**Comment by DmitrysIF** [comment]
Понятно, переделаем.

**Comment by DmitrysIF** [comment]
Заменил на полноценный pop-up
