### ISSUE TITLE
Texts: Create Donee page - To change fields

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#15]
http://gooddler.cloudapp.net/Donee/Create
1. Добавить текст на сером поле: Add a new address (hint: Shipping address); 

2 Вместо существующих полей надо следующие поля:
- Address Line1: (hint: Street address, P.O. box, Company Name, c/o
- Address Line2: (hint: Apartment, Suite, Unit, Building, Floor, etc)
- City: 
- State/Province/Region:
- ZIP:
- Country:
- Phone Number: (hint: +x(xxx)xxx-xxxx  )

Потом текстом:
Address Accuracy:
Make sure you get your stuff! If the address is not entered correctly, your package may be returned as undeliverable. You would then have to place a new order. Save time and avoid frustration by entering the address information in the appropriate boxes and double-checking for typos and other errors. Need help? 

И еще одно поле:
Status of organization (hint: 501(c)3, ect., nonprofit, no status, I don't know)

**Comment by DmitrysIF** [comment]
Будет, через одно-два обновления.

**Comment by DmitrysIF** [comment]
Fixed

**Comment by Fetati** [comment]
Create Donee page:
- В поле Enter description убрать знак вопроса. И так понятно.
- Enter Name исправить на Enter Donee Name и убрать знак вопроса
- После слов Need help? в тексте Accuracy, добавьте info@gooddler.com
- исправить текст Enter Donee Slug на вот так:
  ![screen_shot_2014-04-07_at_10_19_17_pm_png_and_new_issue__goodler_code](https://cloud.githubusercontent.com/assets/4335901/2704355/3a61a766-c46b-11e3-96d7-7fdf1de53b34.jpg)

**Comment by DmitrysIF** [comment]
Исправляется.

**Comment by DmitrysIF** [comment]
Полные исправления будут в следующем обновлении.
