### ISSUE TITLE
UI: why we have subdomain name and Donee name

### ISSUE THREAD

**Issue by ghost** [Goodler/code#151]
how is that used
can we ask users to create one Donee name and generate subdomain name based on that? 
unless there is a reason why we have it, i see a confusion for us in the future, because one user will have at least 2 type of identification  

the wording should be changed for Error msg as well
Should be "Username or Donee name already exist." NOT 
Sorry, this "Donee slug" is exist. Please - enter unique slug-name

**Comment by Fetati** [comment]
Sometimes donees already have domain names, that differ from our User Name. For example Humane Society Truckee Tahoe has their own domain hstt.com. They can use it for Gooddler - hstt.gooddler.com. It is easier to remember and give to their donors.
