### ISSUE TITLE
progress bar is misplaced on some projects

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#152]
![screen shot 2014-04-26 at 4 19 44 pm](https://cloud.githubusercontent.com/assets/7408823/2810081/74e4a852-cd99-11e3-9afd-ce5033eb38a0.png)

![screen shot 2014-04-26 at 4 19 35 pm](https://cloud.githubusercontent.com/assets/7408823/2810082/79c1d5d4-cd99-11e3-8e48-5604b38f444b.png)

![progress bar](https://cloud.githubusercontent.com/assets/7408823/2810084/b75f49e4-cd99-11e3-905d-caf72357ef89.png)

**Comment by DmitrysIF** [comment]
Чуть-чуть расширил границы, должно хватить.

**Comment by Elenarussian** [comment]
All projects are fine ,except this one

![screen shot 2014-04-30 at 7 35 54 pm](https://cloud.githubusercontent.com/assets/7408823/2849447/59456d8c-d0d9-11e3-9f9d-a10f839cdc62.png)

![screen shot 2014-04-30 at 7 36 04 pm](https://cloud.githubusercontent.com/assets/7408823/2849448/5cb4f366-d0d9-11e3-8a23-728990396dd6.png)

**Comment by Elenarussian** [comment]
seen in Safari , Chrome

**Comment by DmitrysIF** [comment]
Конкретнее пожалуйста :)
Что конкретно не так на скриншоте с главной страницы?

**Comment by Elenarussian** [comment]
For some reason , only this project with girls still has bar that is not aligned properly , only that one, the rest is fine

**Comment by DmitrysIF** [comment]
Если вы о том, что они чуть-чуть смещены относительно иконки "All Wishlists" (не по центру), то тут ничего не исправишь - таков скрипт галереи. Менять скрипт не будем - нет смысла ради 2-х пикселей смещения возиться несколько часов. Большинство посетителей даже внимания не обратят на это.
Но если сильно уж досаждает, то смену галереи переносите на Release 2.

**Comment by Elenarussian** [comment]
thank you
