### ISSUE TITLE
Implement Digital Certificate for the for the Checkout Page and Force to Switch to HTTPS

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#153]
Dima and Nikita, we need to make sure that gooddler.cloudapp.net/CheckOut/  page is always served from HTTPS. We need some kind of forced re-direct on the page. Presently, we do not have a digital certificate. We can buy them and configure Azure to use them. Please assist with the task. We cannot go live with users keying in credit card data on unprotected page. 

Thank you!

**Comment by RealBerd** [comment]
Купите сертификат. Настроим.

**Comment by DeveloperRegistry** [comment]
HTTPS implemented.
