### ISSUE TITLE
Wishlist: при добавлении товара появляется "Added", а в Cart в шапке страницы ничего не появляется.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#155]
Мы вроде это правили? - при добавлении товара в корзину, в списке появляется Added, а в Cart в шапке страницы ничего не появляется.

![screen shot 2014-04-27 at 6 57 27 pm](https://cloud.githubusercontent.com/assets/4335901/2812987/92619ba8-ce78-11e3-9018-b9ea40bd003a.png)

**Comment by DmitrysIF** [comment]
Добавляется, но не сразу- это отдельный механизм, который обновляется после добавления.

**Comment by Fetati** [comment]
Хм.. сейчас добавилось быстро. Был какой-то глюк. Закрываю issue, но еще попробую потестировать.

**Comment by DmitrysIF** [comment]
в этом-то и дело - время обновления будет варьироваться, так как после того, как добавляешь товары в корзину (это происходит очень быстро, поэтому так скоро выскакивает Added) - браузер обращается на сервер по сети (а это занимает некоторое время), чтобы отправить ему информацию о том, что находится в корзине и в ответ получить свежие данные о товарах в твоей корзине. В этих данных есть цена, количество и некоторые служебные данные - они используются для того, чтобы построить заново список MyCart в header страницы.
Так что это не баг) Это просто особенность работы данного модуля.
Кнопка Donate и корзина в хедере - это независимые механизмы. Так что не имеет смысла переживать, что информация обновляется неодновременно с нажатием.
