### ISSUE TITLE
My Cart: нестыковка в количестве items

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#157]
Я купила 2 штуки, а в подписи показано, что 1 штука. 

![my_cart_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2814088/475800d8-cea1-11e3-9042-521423304395.png)

**Comment by DmitrysIF** [comment]
Не баг. Это значит, что всего покупается Один лот.

**Comment by DmitrysIF** [comment]
Может пересмотрите варианты подписей? Кое-где было бы логичнее подписывать lot, вместо item

**Comment by DmitrysIF** [comment]
@Fetati Переделано.

**Comment by DeveloperRegistry** [comment]
Dima, I added 2 items two my cart. It shows 2 items everywhere except for the bottom on the checkout page: Your TOTAL is $45.48 1 item

![image](https://cloud.githubusercontent.com/assets/3822498/2873663/92f68464-d3b6-11e3-85eb-f792ae618bb8.png)

**Comment by DeveloperRegistry** [comment]
Updated JavaScript to show identical amounts of items everywhere. Also, changed "item's" to "items". Deployed. See screenshot for details.

![image](https://cloud.githubusercontent.com/assets/3822498/2873831/a11d5dd2-d3c1-11e3-8de3-49cf1dfa88b4.png)
