### ISSUE TITLE
Странная кнопка Check Out в конце вишлиста

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#158]
При выборе товара есть кнопка Donate, которая добавляет товар в корзину. И в конце вишлиста есть большая кнопка Check Out, которая сразу отправляет юзера на страницу ввода кредитной карты. При этом, не добавляя в корзину товар из вишлиста, на котором я эту кнопку нажала. 
Не вижу смысла в этой кнопке вообще. Вполне достаточно кнопки Check Out в шапке. @DeveloperRegistry Антон, что думаешь?

![screen shot 2014-04-27 at 11 51 32 pm](https://cloud.githubusercontent.com/assets/4335901/2814108/d2a0bcac-cea1-11e3-9776-980ec45b79a6.png)

![screen shot 2014-04-27 at 11 51 18 pm](https://cloud.githubusercontent.com/assets/4335901/2814128/26dd44d4-cea2-11e3-9904-6b55831f3a09.png)

**Comment by DeveloperRegistry** [comment]
Amazon has Check Out on Top (v shapke). We can try to Hide this button and only rely on Check Out on top. We can always change it later. 

PS: it is probably a good idea to ask several users not familiar with the site to go through Donation Flow and ask for feedback: what was easy, what was hard to find etc.

**Comment by DmitrysIF** [comment]
Кнопка скрыта.
