### ISSUE TITLE
Overlap of "My Cart" drop down menu 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#16]
Steps
1. Put cursor on "My cart" link 

Bug: Drop down menu overlaps the pictures and info about the cart
![screen shot 2014-04-06 at 8 32 11 pm](https://cloud.githubusercontent.com/assets/7193843/2627424/83a3f2fa-be06-11e3-8ea6-ec2b0b17558a.png)

**Comment by DmitrysIF** [comment]
А разве всплывающие картинки не должны перекрывать? Какой тогда в них смысл, если они ничего перекрывать не смогут?

**Comment by ghost** [comment]
i agree Dima, if we want to show pop-up window can we make sure it does not overlap the the "?" mark or the link. It is kind of under and overlaps something else but not initial link, see new screen shot. It either should be next to the link or under

**Comment by ghost** [comment]
![about you 2](https://cloud.githubusercontent.com/assets/7193843/2773242/5e2e63ee-ca94-11e3-94dc-48cb86dd587f.png)
![drop down](https://cloud.githubusercontent.com/assets/7193843/2773241/5e2dbff2-ca94-11e3-876b-d8f4b7400d94.png)

**Comment by ghost** [comment]
@DmitrysIF Can we add About You not About.

**Comment by ghost** [comment]
those changes should be made across all pages if possible to spread drop down menu/ pop up window we need to stretch it, not put all info in small square, if we have space to put it in wider screen it looks better

**Comment by DmitrysIF** [comment]
в таком случае предоставьте мне пример куда сдвинуть какое всплывающее окошко. У меня с такой фантазией сложности :)

**Comment by DmitrysIF** [comment]
По поводу My Cart - подвижки будут только после того, как предложите вариант расположения всплывающего окошка.

**Comment by Fetati** [comment]
![picasa_3](https://cloud.githubusercontent.com/assets/4335901/2814017/da91e5c8-ce9f-11e3-85cb-daa3347599c9.png)
