### ISSUE TITLE
Scrollbars bug

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#160]
@RealBerd: Никита, а не проще ли сделать дизайн, который мы утвердили изначально, чем переделывать элементы дизайна, который вы вставили по собственной инициативе? В первоначально утвержденном дизайне проблема с кнопками была решена куда более изящно. 

![screen shot 2014-04-30 at 11 58 33 am](https://cloud.githubusercontent.com/assets/4335901/2845729/bf0b83b2-d099-11e3-8a86-cc85fadd4840.png)

**Comment by RealBerd** [comment]
![04_main_cleaned](https://cloud.githubusercontent.com/assets/2241165/2846999/4dc435c2-d0a9-11e3-8936-1c20c5e5712a.jpg)
@DmitrysIF 
Дима, Коля, обратите внимание на стрелочки.

**Comment by DmitrysIF** [comment]
А что со стрелочками? Стрелочки я давно заменил с помощью Коли - если они остались старыми, то вам необходимо почистить кэш, чтобы не заменяло картинки ранее загруженными.
Если не нравится, что я их подвинул на 10 пиксель к центру - то так и скажите, здесь я мало что понял.

**Comment by Fetati** [comment]
Посмотри на картинке, как я вижу - рядом со стрелками куски кружочков не понятно откуда.

**Comment by DmitrysIF** [comment]
Понял - странно, у меня все было нормально (стояли новые картинки).
По всей видимости, он использует старую картинку (хоть я ее и менял)- сейчас проверю.

**Comment by DmitrysIF** [comment]
Все правильно - вам нужно в истории браузера удалить все, что относится к gooddler.cloudapp.net, если их удалить - браузер загрузит актуальные данные сервера и будет видно новые стрелки.
Вот что видно у меня, после того как я почистил историю в своем браузере:
![image](https://cloud.githubusercontent.com/assets/7186861/2848791/b684a2e2-d0c5-11e3-8761-a4c62c2bb6c7.png)

**Comment by Fetati** [comment]
Ок, сейчас проверю

**Comment by DmitrysIF** [comment]
gooddler.cloudapp.net - в предыдущем ответе сделал опечатку.

**Comment by Fetati** [comment]
Все в порядке сейчас.

**Comment by DmitrysIF** [comment]
Отлично :)
