### ISSUE TITLE
blog info should be corrected

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#163]
Go to Blog 
Observe the title 
"News alert" looks off
It would be nice to align text

![screen shot 2014-04-30 at 7 55 37 pm](https://cloud.githubusercontent.com/assets/7408823/2849507/407841dc-d0dc-11e3-86af-9db30bc30883.png)

**Comment by DmitrysIF** [comment]
Это не относится к моей компетенции и к сайту.

**Comment by Fetati** [comment]
Это не имеет никакого отношения к сайту - это сторонний вордпрессовский шаблон. Блоги можно не проверять. Спасибо!
