### ISSUE TITLE
picture link disappear 

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#164]
1. create a New user
2. go to Edit profile and add a pic link
3. Type all info till " Change my password "
4. go to " Change my password "
5. change password
6. go back to My profile 

BUG: picture profile dissaper

**Comment by DmitrysIF** [comment]
go to Edit profile and add a pic link
После добавления картинки изменения применялись? На кнопку "save changes" не нажимали?

**Comment by Elenarussian** [comment]
after step 6 I have  clicked " Save changes" and picture was not uploaded

**Comment by DmitrysIF** [comment]
Тогда почему линк должен сохраняться? Он и не должен сохраняться, так как вы используете страницу из кеша браузера, по всей видимости, скорее всего нажимали кнопку назад.
Не признаю это багом:).

**Comment by Elenarussian** [comment]
the reason we want link to be there so user does not go and search for  a picture again. UI wise it would be nice to have link still there. is it possible?

**Comment by DmitrysIF** [comment]
Нет. Оставьте это для Release 2/

**Comment by Elenarussian** [comment]
ok thank you
