### ISSUE TITLE
Can we add " Amazon URL " section  to the " Create a new Wishlist " flow  ?

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#166]
1. create " My donee "
2. create " My wish list "

Nice to have:  it would be nice to have " Amazon URL " section during  " Create a new Wishlist " flow.

right now: user have to make extra steps to add URL

![screen shot 2014-04-30 at 9 01 10 pm](https://cloud.githubusercontent.com/assets/7408823/2849719/410a6446-d0e5-11e3-9fa2-8af0df005a7e.png)

![screen shot 2014-04-30 at 8 56 03 pm](https://cloud.githubusercontent.com/assets/7408823/2849699/8e5521ce-d0e4-11e3-9ac7-46b493c9962a.png)

**Comment by DmitrysIF** [comment]
Нет. Технически этого вишлиста еще не существует, поэтому добавлять товары не к чему.

**Comment by Elenarussian** [comment]
@Fetati , Tatiana is that the flow we want? or we want to give users the option to add Amazon URL from the start , even though the list does not  exist yet?

**Comment by DmitrysIF** [comment]
Если уж и добавлять эту возможность - то в Release 2.
