### ISSUE TITLE
after user edit "Wish list" he should be taken to "My wish list " page

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#167]
1. edit  Wishlist
2. update Wishlist

right now after user click " Update Wishlist " he stays on the same page
 it would be good to redirect him to the list ( The list of XYZ)

![screen shot 2014-04-30 at 9 24 38 pm](https://cloud.githubusercontent.com/assets/7408823/2849804/8d6cf60c-d0e8-11e3-80bd-17a56d277bdc.png)

**Comment by DmitrysIF** [comment]
@Fetati Нужно ли нам перенаправлять на список после успешного update?

**Comment by Fetati** [comment]
Да, нужно. Я уже где-то об этом писала.
Мне не нравится, что после успешного update, Edit или Create пользователь остается в том же месте. Ощущение, что что-то не сработало. Куда логичнее отправить на ту страницу, которая подходит по логике. Например, после Create Wishlist или Create Donee надо переводить на страницу Wishlist или Donee.

**Comment by DmitrysIF** [comment]
Сделано перенаправление на страницу вишлиста.
