### ISSUE TITLE
Do we plan to have only one type of 501(c) organizations?

### ISSUE THREAD

**Issue by ghost** [Goodler/code#168]
if we have just one type - everything looks fine, but if several we need a drop down menu with types of  501 (c) so users will be accurate and make 0 mistakes in typing it.

**Comment by Fetati** [comment]
Типов non-profit организаций куча, drop down menu не думаю, что подойдет. Из этого поля надо убрать текст "501(с)3".
И это поле (Enter designation) переименовать в Type of Organization. 
В следующих полях (Federal Tax ID и Edit Galery) убрать знаки вопроса

**Comment by DmitrysIF** [comment]
Отлично! Это уберем :)

**Comment by ghost** [comment]
do we need a hint here for Type of Organizations? Do all users will understand what it means basically.

**Comment by Fetati** [comment]
Надо оставить тот hint, который есть сейчас

**Comment by DmitrysIF** [comment]
Исправлено.
