### ISSUE TITLE
User unable to change his profile picture

### ISSUE THREAD

**Issue by ghost** [Goodler/code#17]
Steps:
1. Create an account and download a picture
2. Go to main page and click the username link to bring up User profile
3. Click Edit my Profile and try to update photo 

Bug: user unable to see the change and update the picture.
NOTE: picture was changed but it took a while to see the change - will test more and see what is the problem

NOTE: Edit my profile could be changed to something like btn that says Edit Profile or just Edit instead of (Edit my Profile)
see below
![edit profile](https://cloud.githubusercontent.com/assets/7193843/2627467/fec7e7ce-be07-11e3-88f8-710c400f627a.png)

**Comment by DmitrysIF** [comment]
Да, проблема существует и пока непонятно - или это браузер отказывается загружать новую картинку по тому же адресу, показывая закэшированную картинку. Или же проблема в большой задержке обновления ссылки на картинку.

**Comment by ghost** [comment]
Please keep me posted when it can be tested again.
Thank you

**Comment by DmitrysIF** [comment]
Проблемы с фотографией исправил.
