### ISSUE TITLE
User gets an error when go to "My post"

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#170]
1. Sing Up ,Create new profile
2. Go to " My Post "

Bug : user gets an error in " My Post "

![screen shot 2014-05-01 at 11 14 21 am](https://cloud.githubusercontent.com/assets/7408823/2855437/72507988-d15c-11e3-8760-2353648c058f.png)

**Comment by DmitrysIF** [comment]
По скриншоту вы незалогинены. Что за ошибка? Она стабильно повторяется?

**Comment by Elenarussian** [comment]
Да постоянно и с разных акаунтов ,
Делала логин , как заходишь на мой пост выдает ошибку и выкидывает с акаунта

**Comment by DmitrysIF** [comment]
Проблема проявляется только на новых аккаунтах? На которых ни разу не создавали Donee?

**Comment by DmitrysIF** [comment]
Одну я ошибку нашел и исправил - теперь если у пользователя нет ни одного дони, то все обрабатывается нормально. Можно будет попробовать в следующем обновлении.

**Comment by Elenarussian** [comment]
most of the accounts were new

**Comment by Elenarussian** [comment]
следующем обновлении - is that new release or next code push?  Thank you

**Comment by DmitrysIF** [comment]
Это значит, что в течении нескольких часов я разверну версию сайта, в которой данные ошибки будут исправлены.

**Comment by DmitrysIF** [comment]
Есть Релиз, а есть применение мелких исправлений :)
До первого релиза мы еще не добрались - сейчас идет User testing

**Comment by DmitrysIF** [comment]
В деплое.
