### ISSUE TITLE
UI: after editing Donee i want to be taken to Donee list or Donee 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#171]
go to donee and edit 
click save

User stays on the same page
its better if we take user to the list (see attached) or to Donee directly (better choice )( see attached) 
![better take me here](https://cloud.githubusercontent.com/assets/7193843/2855728/331a98ee-d160-11e3-9bff-9244b349958c.png)
 so they can see changes, right now user do extra steps to see updates
![take me there](https://cloud.githubusercontent.com/assets/7193843/2855704/f34fcc66-d15f-11e3-808b-65a9361a308d.png)

**Comment by DmitrysIF** [comment]
Сделал перенаправление на страницу дони. Так же сделал подобные исправления для постов и для вишлистов.
