### ISSUE TITLE
If wishlist is empty - say empty (delete "wishlist not found)

### ISSUE THREAD

**Issue by ghost** [Goodler/code#172]
![empty](https://cloud.githubusercontent.com/assets/7193843/2855749/86062794-d160-11e3-9e7d-5a1d11291aef.png)

thank you

Samples
Wishlist is empty
Empty
 Please align it under words not under icon, icon should stand out by itself

**Comment by DmitrysIF** [comment]
Изменил текст и подвинул вправо.
