### ISSUE TITLE
got this server error 

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#173]
i was creating a post and got into that after 
to whom i should assign those issues in the future? 
thank you

![screen shot 2014-05-01 at 8 31 54 pm](https://cloud.githubusercontent.com/assets/7408823/2859587/4d08a80e-d1ab-11e3-9245-50c099784479.png)

**Comment by DmitrysIF** [comment]
Прошу сообщить о шагах, которые позволят воспроизвести ошибку.

**Comment by Elenarussian** [comment]
![screen shot 2014-05-01 at 8 29 01 pm](https://cloud.githubusercontent.com/assets/7408823/2865708/06f73644-d220-11e3-9fe9-7944786f1b11.png)

![screen shot 2014-05-01 at 8 30 59 pm](https://cloud.githubusercontent.com/assets/7408823/2865711/0ac97534-d220-11e3-9423-bae01898d270.png)

![screen shot 2014-05-01 at 8 31 09 pm](https://cloud.githubusercontent.com/assets/7408823/2865712/10c5b1a0-d220-11e3-8799-fd1b530b4f3f.png)

![screen shot 2014-05-01 at 8 31 54 pm](https://cloud.githubusercontent.com/assets/7408823/2865716/15b15732-d220-11e3-8ce1-dbd0556a94b2.png)

![screen shot 2014-05-01 at 8 32 41 pm](https://cloud.githubusercontent.com/assets/7408823/2865718/1cef216e-d220-11e3-85d3-91733a0733f7.png)

**Comment by DmitrysIF** [comment]
@Elenarussian это происходит при попытке создать сообщение для пользователя?

**Comment by Elenarussian** [comment]
Это произошло только один раз , при создании акаунта, потом создала доню, вишлист и пошла создавать пост . На пост вышла ошибка.

**Comment by DmitrysIF** [comment]
@Elenarussian Не могу воспроизвести ошибку

**Comment by DmitrysIF** [comment]
@Elenarussian Закрываю этот issue, если ошибка снова себя проявит - откроете.
