### ISSUE TITLE
Dollars amount wrong format

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#174]
![screen shot 2014-05-02 at 10 48 48 am](https://cloud.githubusercontent.com/assets/4335901/2865876/22ef89ee-d222-11e3-9cb2-bc7f9cd59b81.png)

**Comment by DeveloperRegistry** [comment]
Thank you. I will fix it ASAP. We changed how money were stored and handled. So, we may see some adverse effects.

**Comment by DeveloperRegistry** [comment]
Fixed.
