### ISSUE TITLE
Text: "Write new post about Tatiana Fedorova" - убрать "about Tatiana Fedorova"

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#175]
Text: "Write new post about Tatiana Fedorova" - убрать "about Tatiana Fedorova" - пусть пишут, что хотят.
http://gooddler.cloudapp.net/Profile/

![screen shot 2014-05-02 at 10 48 48 am](https://cloud.githubusercontent.com/assets/4335901/2865940/0c3e13e0-d223-11e3-8125-28b0c2edeb74.png)

**Comment by DmitrysIF** [comment]
@Fetati Убрано.
