### ISSUE TITLE
Main Page Posts: I can't see "read more" link

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#178]
http://gooddler.cloudapp.net/
Первый слева пост - я не вижу read more, и не могу зайти посомотреть что за пост

![screen shot 2014-05-02 at 11 04 56 am](https://cloud.githubusercontent.com/assets/4335901/2866092/6b4b776e-d224-11e3-8320-f8aa745b894c.png)

**Comment by Fetati** [comment]
1) На Main Page поле постов должно расширяться в зависимости от длины заголовка поста. 

2) И еще, по какой логике высвечивается оранжевый линк сверху? Это к какому Donee пост? Или от Donee?
Если я как юзер и представитель Donee создаю пост из профайла донора по линку Create New Post about, то не видно на главной странице о ком речь.

**Comment by DmitrysIF** [comment]
@Fetati Если пользователь написал пост другому пользователю через ссылку в профиле - ссылки на донейшен не будет, ибо его нет.
Оранжевая ссылка - это ссылка на донейшен, его не будет в случаях, если пост писался пользователю от пользователя минуя donation или если пользователь написал пост от своего имени не адресуя его никуда.

**Comment by DmitrysIF** [comment]
@Fetati То есть, оранжевая ссылка - это От какого Donee идет пост.
