### ISSUE TITLE
User profile: Eror - Donations of User

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#179]
http://gooddler.cloudapp.net/Profile/trina/Donations

1) жму Donations of Trina O
![screen shot 2014-05-02 at 12 03 16 pm](https://cloud.githubusercontent.com/assets/4335901/2866775/a165b582-d22c-11e3-8cfd-ac06c1e914ec.png)

Вижу вот такой экран (Chrome):
![screen shot 2014-05-02 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/4335901/2866783/b12e6040-d22c-11e3-9bc2-e304f6c6d5fe.png)

**Comment by DmitrysIF** [comment]
Исправлено
