### ISSUE TITLE
It would be nice to have colored FB, TW and Linked In icons in user profile

### ISSUE THREAD

**Issue by ghost** [Goodler/code#18]
Steps:
go to user's profile 
observe the FB,TW and IN icons

Note: would be nice to have it in color and make sure they follow the copyright specs of the copyright holders.
![icons social media](https://cloud.githubusercontent.com/assets/7193843/2627508/5be11146-be09-11e3-9b1b-1c1ac7060c87.png)

**Comment by DmitrysIF** [comment]
Добавлена возможность указания ссылок на свои аккаунты в социальных сетях.

**Comment by DmitrysIF** [comment]
Note: would be nice to have it in color and make sure they follow the copyright specs of the copyright holders.

Предоставите исходники для цветных иконок - поставим.
