### ISSUE TITLE
Wishlist: Add new item Eror 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#180]
![screen shot 2014-05-02 at 12 19 26 pm](https://cloud.githubusercontent.com/assets/4335901/2866943/ce2e2b9c-d22e-11e3-8b5b-a84574b18582.png)

**Comment by DeveloperRegistry** [comment]
Please provide full amazon link that crashed the server.

**Comment by Fetati** [comment]
http://www.amazon.com/Cuddl-Duds-Climatesmart-Essentials-Sleeve/dp/B007TL0X9Q/ref=cts_ap_2_fbt

Добавляю вот сюда: http://gooddler.cloudapp.net/Wishlist/Edit/30023

**Comment by DmitrysIF** [comment]
@Fetati Проблема в том, что амазон не дает по этому товару цены, есть предложение в таких случах выводить поп-ап окно с предложением вручную ввести стоимость товара.
