### ISSUE TITLE
My Cart: Wrong amount of $$

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#182]
http://gooddler.cloudapp.net/MyCart :

![screen shot 2014-05-02 at 1 14 26 pm](https://cloud.githubusercontent.com/assets/4335901/2867435/69a9aed2-d236-11e3-9b35-0651b5fc0b1e.png)

**Comment by Fetati** [comment]
Баг в итоговой сумме (Total) - Должно быть с шипингом 513, в надписи снизу (Your Total) правильная сумма, а в строке товара - почему-то на 3 доллара меньше.

И еще, меня смущает цифра за шипинг. Довольно confusing... По идее, тут не должна быть показана сумма шипинга за единицу товара. А должна быть итоговая за выбранное количество.
Ну и поля тогда должны быть наоборот - после выбора количества товара идет сумма шипинга.

**Comment by DeveloperRegistry** [comment]
This could be my latest changes. I will take a look.

**Comment by Fetati** [comment]
@DeveloperRegistry Антон, посмотри мой предыдущий комент про сумму шипинга. Можно это поправить как-то?

**Comment by DeveloperRegistry** [comment]
I think so. I will take a look.

**Comment by Fetati** [comment]
При смене количества товара едут итоговые суммы. Неправильно считается Total в строке товара.
![screen shot 2014-05-02 at 1 30 45 pm](https://cloud.githubusercontent.com/assets/4335901/2867744/b9f65c38-d23a-11e3-9a24-9ae545a0ba74.png)

**Comment by DeveloperRegistry** [comment]
I fixed the Total in Product Line. It was definitely a bug. 

The cost of shipping right now is shown per item. Technically, it makes sense. The more items items you buy, the higher is the shipping cost. I am sure that there is a formula where shipping for 1 item will not be the same as shipping for 10 items. However, we do not have this data at the moment. I suggest to move this to Release 2. We need to sign up for Amazon account to get accurate shipping  info.
