### ISSUE TITLE
Wording: My Cart - delete the items amount.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#183]
Сейчас YOUR TOTAL is $359.1 for 1 item. Убрать "for xx item" - потому что это не items, а группа товаров. В примере ниже - я покупаю 7 items а высвечивается один. 
Или сделать так, чтобы считалось реальное количество items корзины

![screen shot 2014-05-02 at 1 35 26 pm](https://cloud.githubusercontent.com/assets/4335901/2868122/00700a14-d241-11e3-99cb-65ebd86958c7.png)

**Comment by DmitrysIF** [comment]
Хорошо, поменяю на реальные Айтемы.

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно.
