### ISSUE TITLE
Слишком долго грузится страница - Separate Static Content

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#184]
Каждый раз, как я захожу заново в Goddler после перерыва, время ожидания первой загрузки страницы по пол минуты.

**Comment by DeveloperRegistry** [comment]
I think it is JavaScript and images loading. We are using very heavy JavaScript libraries. I talked to Nikita about this. Usually, static content (JavaScript, Images etc.) is hosted on a separate server. Not on IIS. We need to research how to do it on Azure.
