### ISSUE TITLE
View All Wishlist button doesn't work

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#185]
http://gooddler.cloudapp.net/Wishlists

![screen shot 2014-05-02 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/4335901/2868841/15dec930-d250-11e3-9a61-5364e19a690f.png)

**Comment by Fetati** [comment]
О, я сразу не заметила, меня выкинуло из эккаунта - см. на картинке, я не под своим именем, хотя была signed in.

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно.
