### ISSUE TITLE
Check out Page: change product line.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#186]
![check_out_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2869277/289696ae-d262-11e3-922a-fed067a93744.png)

1) исправить total items вверху и снизу страницы. Должно совпадать с реальным количеством выбранных товаров. В моем случае их 7, а не 1.
2) вообще сумма шипинга обычно пишется отдельно. Так как товары могут иметь разную сумму шипинга предлагаю сделать в каждой строке отдельную сумму шипинга всего выбранного по данной позиции товара
3) в строке с товаром сумма товара должна оставаться такой-же, как и на предыдущей странице (My Cart). Сейчас к цене за товар добавлена стоимость шипинга за единицу товара.

**Comment by DeveloperRegistry** [comment]
I can work on this.

**Comment by DeveloperRegistry** [comment]
Re-assigned to Dima. He is working on a similar issue.

**Comment by DeveloperRegistry** [comment]
Lets be consistent with Amazon:

![image](https://cloud.githubusercontent.com/assets/3822498/2872439/76b2df38-d360-11e3-93f8-561de4cab0e2.png)

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно.
