### ISSUE TITLE
My Cart: No links to Donee and Wishlist 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#187]
Из My Cart нет линка на wishlist and donee, куда я покупаю товар. Если я захотела купить другие товары из вишлиста, то очень проблематично отыскать этот вишлист. Нет его упоминания нигде.
Надо хотя бы Donee name сделать кликабельным.
http://gooddler.cloudapp.net/MyCart

![screen shot 2014-05-02 at 7 39 52 pm](https://cloud.githubusercontent.com/assets/4335901/2869404/684ab604-d26c-11e3-9a98-f1c4912d9213.png)

**Comment by DmitrysIF** [comment]
@Fetati сделаю Donee кликабельным - хотя я бы заменил Donee на Wishlist Name

**Comment by Fetati** [comment]
Да, давай wishlist. Спасибо!

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно.

**Comment by DmitrysIF** [comment]
Не ту ссылку поставил, не успел прочитать ваше сообщение о согласии на Wishlist-ссылку.

**Comment by DmitrysIF** [comment]
@Fetati Исправлено на ссылку вишлиста.
