### ISSUE TITLE
Wording: My Wishlists

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#189]
http://gooddler.cloudapp.net/Admin/Wishlists?doneeid=10034

Should say Wishlist is Empty (not wishlistS)
![screen shot 2014-05-03 at 10 49 51 am](https://cloud.githubusercontent.com/assets/7177944/2870967/56565456-d2eb-11e3-93a5-f346709a977d.png)

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно.
