### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#190]
Мне не нравится, что у нас Password reset на Stormpath. Это потому, что мы пока не перешли на платную версию? Будет возможность в платной версии настроить все в дизайне Gooddler?

![screen shot 2014-05-03 at 12 41 12 pm](https://cloud.githubusercontent.com/assets/4335901/2871211/215caf1a-d2fb-11e3-9953-51a32aa12561.png)

**Comment by DmitrysIF** [comment]
@DeveloperRegistry можешь исследовать этот вопрос?

**Comment by DeveloperRegistry** [comment]
Re-assigned to me for Research.

**Comment by DeveloperRegistry** [comment]
Closed as duplicate to Password reset is still at Stormpath #297 

We will work on the issue under Password reset is still at Stormpath #297
