### ISSUE TITLE
Wishlist: Add new Item Eror - quantity

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#191]
1) занесла товар, выбрала 10 штук
2) решила увеличить количество до 30, нажала apply, получила ошибку:

![screen shot 2014-05-03 at 12 52 47 pm](https://cloud.githubusercontent.com/assets/4335901/2871229/9e8e2012-d2fc-11e3-8c6b-972f9323f446.png)

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно. Протестируйте, пожалуйста.
