### ISSUE TITLE
Wording: Edit Wishlist

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#192]
Browser: Safari, http://gooddler.cloudapp.net/Wishlist/Edit/40038

1) В поле ввода количества товара заменить слово "Count" на "Quantity" 
2) В окне ошибки текст Count of goods must be more 0 заменить на
Quantity of goods must be greater than 0
3) Название полей списка товаров подвинуть правее, чтобы они были в точности над ячейками, которые они указывают

![screen shot 2014-05-03 at 12 52 47 pm](https://cloud.githubusercontent.com/assets/4335901/2871237/1f18abd0-d2fd-11e3-91ba-ecff1fe35763.png)

**Comment by DmitrysIF** [comment]
@Fetati Подвинуть заголовки ячеек таблицы? Они и так соответствуют своему левому краю колонки.

**Comment by Fetati** [comment]
Сделай их посередине тогда. 
Посмотри на колонку 1 и на колонку Quantity - сейчас заголовок сильно левее текста колонки.

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно.
