### ISSUE TITLE
Create Wishlist: shipping price issues

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#194]
Release 2?

Я вошла как обычный юзер. На Амазоне доставка товара $9.99, а у нас добавляется 1 доллар. 
В режиме администратора я могу отредактировать, конечно же. Но тогда мне надо бы быстро видеть кто что добавляет. 

![screen shot 2014-05-03 at 1 08 59 pm](https://cloud.githubusercontent.com/assets/4335901/2871268/387e0be0-d2ff-11e3-80fc-cd7f4d7f2e11.png)
![screen shot 2014-05-03 at 1 09 15 pm](https://cloud.githubusercontent.com/assets/4335901/2871269/387f2714-d2ff-11e3-8414-4a25a40a8df6.png)

**Comment by DeveloperRegistry** [comment]
Dima, do we have shipping information in Web Service Response?

**Comment by DmitrysIF** [comment]
@DeveloperRegistry  Я уже как-то говорил об этом, но мы не можем в текущем сервисе иметь возможность получения стоимости доставки!
Чтобы иметь эту возможность - нужно регистрировать партнерку Amazon, что было сопряжено со сложностями. Если вам необходима именно стоимость доставки, то нужно заводить аккаунт Amazon MWS и переписывать библиотеку взаимодействия с Amazon, так как там совсем другой API.

**Comment by DmitrysIF** [comment]
В данном вопросе можно было бы добавить e-mail оповещение админов гуддлера о добавлении товара в вишлист.

**Comment by DeveloperRegistry** [comment]
Tanya, suggesting to Move to Release 2. What do you think?

**Comment by DmitrysIF** [comment]
@DeveloperRegistry Вам понадобится вот это, если конкретнее (если хотите поменять апи)
https://developer.amazonservices.com/gp/mws/index.html/182-3880745-8902361

**Comment by Fetati** [comment]
Да, давайте в Релиз 2 это.

**Comment by DeveloperRegistry** [comment]
Tagged for Release 2
