### ISSUE TITLE
Wishlist Donation Items Amounts

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#196]
There are three issues with the Wishlist Donation Page:

1) The Web Page states "Needed". However, it is not clear to the User (donor) that this is the amount that will be donated. Proposing to make the field "Needed" Read Only and Add a new field (potentially, on a separate line in the center) allowing end users to pick amounts to be donated. The field can be named "Pick Donation Amount" or similar
2) Proposing to allow Donors to key in the amount or make the amount a drop down list. At the very least, users should not be able to clear the field.
3) We should not start with the highest donation amount. If we have 200 items that are needed, small donors will be intimidated if we propose to donate 200 items. We should start small. Probably, from one. 

Tanya and Galya, what do you think?

![image](https://cloud.githubusercontent.com/assets/3822498/2871881/e48dbbe2-d32c-11e3-886f-d6db9ac02220.png)

**Comment by DmitrysIF** [comment]
Я был бы против добавления еще одного поля в строку - разъедется вся верстка, нужно менять макет страницы для этого. Я согласен с тем, что стоит начать с 1pc.

**Comment by DeveloperRegistry** [comment]
Can we add a completely new line with "Select Item Amount" in the Middle?

**Comment by DmitrysIF** [comment]
@DeveloperRegistry Установил начало отсчета с 1pc, установил полный запрет на ручное редактирование полей.

**Comment by Fetati** [comment]
Исправь стрелочки выбора количества товара! Не кликаются - трудно попасть.

**Comment by DmitrysIF** [comment]
@Fetati Fixed, сделаны кроссплатформенные, самописные.
Проверьте во всех браузерах. по ссылке www.goddler.com.
Не забудьте очистить кэш браузера, чтобы у вам загрузились самые новые версии скриптов с сайтаю
