### ISSUE TITLE
Disable "Confirm and Pay" Button upon first click on Checkout Page

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#197]
To prevent double charging people, disable "Confirm and Pay" Button upon first click on Checkout Page.

Nice To Have:
1) Gray Out Button upon payment submission (change button style)
2) Add a warning to the Page "Please Click only once." or similar

![image](https://cloud.githubusercontent.com/assets/3822498/2871943/b4ee6b66-d331-11e3-8eb3-f4779b899db4.png)

**Comment by DmitrysIF** [comment]
Предлагаю вообще убирать кнопку и возвращать ее только если есть какая-нибудь ошибка в данных.

**Comment by DeveloperRegistry** [comment]
This will work.

**Comment by DmitrysIF** [comment]
@DeveloperRegistry Исправлено.
