### ISSUE TITLE
Profile page - Donations of user

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#199]
Зашла со страницы своего профайла на Donations of Ttt Fed, получила ошибку
http://gooddler.cloudapp.net/Profile/ttfed/Donations
У меня нет ни одного donation. Если в этом причина, то надо текст не Error.
An error occurred while processing your request.
Надо текст: You have not purchased any gifts yet. We encourage you to make someone happy today.

![screen shot 2014-05-03 at 9 26 24 pm](https://cloud.githubusercontent.com/assets/4335901/2872125/67ee7c58-d344-11e3-927c-864674a9fe48.png)

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно.

**Comment by DmitrysIF** [comment]
@Fetati Исправлено - в течении часа будет доступно.
