### ISSUE TITLE
Texts:  for Create Donee Page - replace "Enter Donee slug"

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#20]
Заменить "Enter Donee slug" по этому образцу:
![gooddler create donee issues](https://cloud.githubusercontent.com/assets/4335901/2640169/b9d5bf88-bede-11e3-9638-bdbf3ebe592c.jpg)

**Comment by Fetati** [comment]
Изменить слово Slug на Subdomain 
Вот это, к примеру:
 status message: Sorry, this "Donee slug" is exist. Please - enter unique slug-name

Заменить на 
Sorry, this Subdomain Name aready exists. Please enter the unique Subdomain Name.

**Comment by DmitrysIF** [comment]
Косметические правки применены.
