### ISSUE TITLE
Change wording, Error message on Create Donee page

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#200]
http://gooddler.cloudapp.net/Donee/Create

Replace: Error message:Sorry, this "Donee slug" is exist. Please - enter unique slug-name
With: Error message: Sorry, this subdomain has been taken already. Please, create a new subdomain. 

![screen shot 2014-05-04 at 5 52 38 pm](https://cloud.githubusercontent.com/assets/7177944/2874554/958d4936-d3ef-11e3-8fb9-996bd51de386.png)

**Comment by DmitrysIF** [comment]
@galinafed Исправлен текст ошибки.
