### ISSUE TITLE
Explaining of process on Create Wishlist page

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#201]
Is it  possible to add explanation that donee would have to create description of wishlist first and then go to edit it to add items?

Somewhere before Create Wishlist button, it would be nice to have something like that:

Note: Please, create your wishlist first. Then you will be able to add all the items by clicking on Edit Wishlist.

Or something like that, what do you think?

PLUS: Please, replace Published with Publish Wishlist

![screen shot 2014-05-04 at 6 08 52 pm](https://cloud.githubusercontent.com/assets/7177944/2874605/797d673c-d3f2-11e3-84cb-00273a07b6b9.png)

**Comment by DmitrysIF** [comment]
Я в принципе За, можете предоставить пример размещения на странице подобного сообщения?

**Comment by DmitrysIF** [comment]
@galinafed Прошу предоставить пример размещения сообщения :) 
И сам текст сообщения.

**Comment by galinafed** [comment]
Text: 
Note: Please, create your wishlist first. Then you will be able to add all the items by clicking on Edit Wishlist.

Placement:
Right above Create Wishlist button.

Plus, replace Published with Publish Wishlist.

**Comment by Fetati** [comment]
Вот так:
![create wishlist](https://cloud.githubusercontent.com/assets/4335901/2909882/53983ca6-d639-11e3-8f9d-5a116e77869a.jpg)

И замени Published на Publish Wishlist

**Comment by DmitrysIF** [comment]
@galinafed Fixed
