### ISSUE TITLE
after user edit "Post " he should be taken to "My Post"

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#202]
1. Edit Post 
2. Update Post

![screen shot 2014-05-05 at 11 21 22 am](https://cloud.githubusercontent.com/assets/7408823/2881348/184c8c14-d482-11e3-9924-69308d388218.png)

Right now after user click " Update Post " he stays on the same page.
It would be good to redirect him to the " My post ". Thank You.

**Comment by DmitrysIF** [comment]
@Elenarussian сделал перенаправление на страницу обновленного поста.
