### ISSUE TITLE
Item does not add correctly to the cart and does not appear in the column "Done".

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#203]
![cart2](https://cloud.githubusercontent.com/assets/7462589/2886122/eeead35c-d4dc-11e3-8988-3540967f7fb3.jpg)
Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Sigh in with valid data
3. Click on random scrolling picture
4. Choose an item which you want to donate and click "Donate"
Observe: Item does not add correctly to the cart and does not appear in the column "Done". 
Reproduced all the time when you add first item after sigh in when cart is empty.
Expected Result: Item add correctly to the cart and already visible in the column "Done".
Windows 8.1
Mozilla Firefox 27.0

**Comment by DeveloperRegistry** [comment]
Dima, I see it all the time as well. Can we just update it with JavaScript? Is it waiting for Ajax?

**Comment by DmitrysIF** [comment]
@projectnew Исправлен баг в скрипте.
