### ISSUE TITLE
Users can not see their charity 

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#206]
![orders](https://cloud.githubusercontent.com/assets/7462589/2886459/20049f64-d4e6-11e3-9310-665174017f7b.jpg)
Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Sigh in with valid data
3. Click on random scrolling picture
4. Choose an item which you want to donate and click "Donate"
5. Click "Check out"
6. Provide valid credit card data
7. Type valid Billing Information 
8. Click "Confirm and Pay"
9. Page appears -  "Thank you for your generosity! .... Save it as a receipt for your donation."
10. Click on your user name (upper right corner where "Hello, User! ")

Observe:
Users can not see their charity 

Reproduced all the time.

Expected Result: User can find all information about his charity (items, payments).

Windows 8.1
Mozilla Firefox 27.0

**Comment by DmitrysIF** [comment]
@projectnew  See link on a Profile page - "Donations of %name%"

**Comment by Fetati** [comment]
@DmitrysIF Дим, это означает, что кнопку, где можно посмотреть Donations, совсем не заметно. 
Давай поменяем местами "Write New Post" (вместе со значком) и "Donations of %name%" ? Это будет логичнее выглядеть.

И сделаем линк в выделенном на картинке куске на "2 items", который будет вести на страницу Donations http://gooddler.cloudapp.net/Profile/tatiana/Donations

**Comment by DmitrysIF** [comment]
Fixed
