### ISSUE TITLE
[Delete] link does not work (is not active)

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#208]
![delete does not work](https://cloud.githubusercontent.com/assets/7462589/2886583/3fe84670-d4e9-11e3-9d1a-798fd4dc3b55.jpg)
Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Sigh in with valid data
3. Click on 3x3-dot icon (My GOODdler)
4. In drop down menu click "My Posts"
5. Click "Create a New Post" button
6. Type valid "Title"
7. Type content 
8. Click [Select files]  link to upload a photo
9. After the photo was uploaded change you mind and click [Delete] link

Observe:
 [Delete] link does not work  (is not active)

Reproduced all the time.

Expected Result: User can delete previously uploaded photo

Windows 8.1
Mozilla Firefox 27.0

**Comment by DmitrysIF** [comment]
Fix
