### ISSUE TITLE
"Error message:Error. Please fill in all fields required." Required fields are not specified.

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#209]
![required fields](https://cloud.githubusercontent.com/assets/7462589/2886711/e1066f5c-d4ec-11e3-9e77-384c451b02db.jpg)
Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Sigh in with valid data
3. Click on 3x3-dot icon (My GOODdler)
4. In drop down menu click "My Donees"
5. Click "Create a New Donee" button
6. Type valid data in all fields (exept "Federal Tax ID" and "Use a Subdomain of gooddler.com" )
7. Click "Create" button.

Observe:  "Error message:Error. Please fill in all fields required." Required fields are not specified.

Reproduced all the time.

Expected Result: Observe "Error message:Error. Please fill in all fields required." All required fields must be marked with asterisk " \* ".

Windows 8.1
Mozilla Firefox 27.0

**Comment by DmitrysIF** [comment]
@projectnew fixed
