### ISSUE TITLE
Edit Donee Page: Не тот курсор при наведении на Safe Changes 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#21]
http://gooddler.cloudapp.net/Profile/Edit
Edit Donee Page: Не тот курсор при наведении на Safe Changes - сейчас палочка, как для редактирования. Надо ладошку с пальцем, как на кнопке Browse 

![goddler issues edit donee](https://cloud.githubusercontent.com/assets/4335901/2640208/24a708fc-bee0-11e3-8a6f-d52cdd706646.jpg)

**Comment by DmitrysIF** [comment]
В следующем обновлении.
