### ISSUE TITLE
User can not delete previously published post

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#210]
![delete button post](https://cloud.githubusercontent.com/assets/7462589/2886870/74e7fa9e-d4f0-11e3-8b91-40dd193882b5.jpg)

Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Sigh in with valid data
3. Click on 3x3-dot icon (My GOODdler)
4. In drop down menu click "My Posts"
5. In "Action" column click round "Delete" button for random post

Observe:
"Delete" button does not work (is not active)

Reproduced all the time.

Expected Result: User can delete previously published post

Windows 8.1
Mozilla Firefox 27.0

**Comment by DmitrysIF** [comment]
Fix
