### ISSUE TITLE
Check out page: Total Order - confusing numbers

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#211]
На мой взгляд, если показываем количество товара, то должна быть его цена за единицу перед количеством, потом общая стоимость, потом стоимость шипинга всего товара.
Второй вариант - можно сделать только общую стоимость товара по каждой позиции, и стоимость доставки.

![screen shot 2014-05-06 at 9 47 20 am](https://cloud.githubusercontent.com/assets/4335901/2892705/ee6127e8-d53f-11e3-8959-faffb1387f0f.png)

**Comment by DmitrysIF** [comment]
@Fetati посмотрите, пожалуйста.

**Comment by Fetati** [comment]
Все равно не понятно. Вот так надо:

![check_out_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2905308/f5774502-d603-11e3-88c0-01bb2682625a.png)

*перечеркнуто, так как цифры не совпадают со столбцами. Они нужны, но правильные.

Все суммы в столбцах должны быть отцентрированы. Сейчас прыгают.

**Comment by DmitrysIF** [comment]
Исправлено
