### ISSUE TITLE
Можно ли заменить "Edit this Whishlist "  на for example " Edit Whishlist 1" or something else ?

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#212]
![screen shot 2014-05-05 at 11 30 20 am](https://cloud.githubusercontent.com/assets/7408823/2893572/e3797394-d549-11e3-8453-d911a97034ea.png)

**Comment by DmitrysIF** [comment]
@Fetati Посмотрите.

**Comment by Fetati** [comment]
Можно просто убрать "this" - Edit Wishlist

**Comment by DmitrysIF** [comment]
@Elenarussian Fixed
