### ISSUE TITLE
user unable to delete a post ( Safari)

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#213]
1. create  " New post" 
2.  click button " Delete post " 

bug: right now after user click " Delete " it keeps him on the same page , and user unable to delete a post 

expectations : user should be able to delete post 

![screen shot 2014-05-06 at 11 18 29 am](https://cloud.githubusercontent.com/assets/7408823/2893692/f437b640-d54a-11e3-9415-5ca4ca50341e.png)

**Comment by DmitrysIF** [comment]
@Elenarussian уже должно работать.
