### ISSUE TITLE
maybe we should change title inside "My Cart " ( when cart is empty )?

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#215]
If user click " My cart " and it's empty he shouldn't see Button " Check Out " and shouldn't be able for check out too. And it would be better to redirect user to the main page or etc .....

![screen shot 2014-05-06 at 11 41 19 am](https://cloud.githubusercontent.com/assets/7408823/2893991/143b76f4-d54e-11e3-8b74-4bf5e08258f6.png)

For Example Amazon :

![screen shot 2014-05-06 at 11 40 53 am](https://cloud.githubusercontent.com/assets/7408823/2894103/6948d2a8-d54f-11e3-87bf-f7fe5b38df29.png)

**Comment by galinafed** [comment]
Let's say:

"Your Cart is empty. Make a difference by purchasing items from our wishlists."

and have a link to main page

**Comment by DmitrysIF** [comment]
@Elenarussian Fixed
