### ISSUE TITLE
user gets error when click " do "

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#216]
1. Go to " Wishlists " 
2. Choose wishlist " Wish 1 " or " My big wishlist " and etc 
3. Click button " Do "

bug : user gets error when click " Do " 

![screen shot 2014-05-06 at 12 36 06 pm](https://cloud.githubusercontent.com/assets/7408823/2894660/b4be68aa-d555-11e3-8cd4-7a9f23d8f287.png)

![screen shot 2014-05-06 at 12 32 19 pm](https://cloud.githubusercontent.com/assets/7408823/2894617/3d844c28-d555-11e3-824d-d3b91d794c77.png)

**Comment by DmitrysIF** [comment]
Ноги этого бага растут из #217 
Исправляется.

**Comment by DmitrysIF** [comment]
@Elenarussian fixed
