### ISSUE TITLE
user gets error when open " Wishlist "

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#217]
1.go to the " Wishlists "
2. choose wishlist
3. click on it 

bug : user gets error when open  " Wishlist "

![screen shot 2014-05-06 at 12 47 47 pm](https://cloud.githubusercontent.com/assets/7408823/2894755/53dc3510-d557-11e3-93cf-70275f85e195.png)

**Comment by DmitrysIF** [comment]
Конкретнее описывайте баги! 
Какой тип аккаунта - суперадминистратор или простой пользователь?
Был ли у аккаунта к этому вишлисту доступ как менеджера дони этого вишлиста?
Была ли у этого дони поставлена галочка Published?

**Comment by DmitrysIF** [comment]
@Elenarussian  Уже разобрались - баг исправляется, вы сумели увидеть в списке неопубликованный вишлист, что не является нормальной работой этой страницы. :)

**Comment by DmitrysIF** [comment]
@Elenarussian fixed
