### ISSUE TITLE
Wrong Cursor

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#219]
http://gooddler.cloudapp.net/Wishlist/40042
Курсор мыши при выборе количества товара опять не тот - сейчас как для ввода текста, а должен быть в виде стрелки. С таким курсором, как сейчас, довольно сложно попасть на стрелки прокрутки.
Мы уже это правили когда-то. Опять слетело.

**Comment by DmitrysIF** [comment]
@Fetati с новыми полями ввода со стрелками это уже не актуально, закрываю
