### ISSUE TITLE
My Donations page

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#220]
Нам остро необходима страница My Donations для доноров.
Это может быть таблица, как My Donees и пр. 
Разместить линк на нее нужно на странице User Profile

Данные таблицы должны быть: Donee, Wishlist, Items Donated, Donated ($), и еще снизу Total Donated ($)

**Comment by DeveloperRegistry** [comment]
Can we schedule this for Release 2?

**Comment by DmitrysIF** [comment]
@Fetati @DeveloperRegistry 
 У нас она вообще-то есть. В профиле пользователя Donations of %FirstLastName%.
Можно добавить ссылочку в My Gooddler.

**Comment by Fetati** [comment]
Проблема в том, что я там тоже вижу, что товар отправлен в donee, который был последним добавлен в вишлист.

![donations_of_tatiana_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2904861/9339e498-d5ff-11e3-9ea0-902e53ebdd6a.png)

На самом деле туда была куплена всего одна позиция на сумму $0.99, плюс $1 за доставку. А 7 пар ботинок на сумму 350 долларов (плюс $1.31x7 за доставку) в другой дони. А в отчетах я этого не вижу - ни на сайте, ни в имейле, который будет использоваться для tax deduction:

![wishlist_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2904952/46f96576-d600-11e3-8616-7dd46bd63a87.png)

**Comment by Fetati** [comment]
@DmitrysIF: Дим, да, давай добавим ссылочку в My Gooddler. И еще, как я писала в #206, давай поменяем местами в My Profile кнопки "Write New Post" (вместе со значком) и "Donations of %name%" ? Это будет логичнее выглядеть.

И сделаем линк в выделенном на картинке куске на "2 items", который будет вести на страницу Donations http://gooddler.cloudapp.net/Profile/tatiana/Donations

**Comment by DmitrysIF** [comment]
@Fetati Понятно, мы с этим разберемся! Антон уже работает над разделением писем для каждого дони отдельного.

**Comment by DmitrysIF** [comment]
Fixed
