### ISSUE TITLE
Wrong E-mail notification

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#221]
Я оплатила несколько позиций товара разным Donee, а получила e-mail от последнего Donee на всю сумму. Причем, общая сумма большая, а последняя сумма была копеечная - $0.99 за товар, и 1 доллар за доставку. 

Надо присылать имейлы от каждого Donee на их сумму. То есть, от одной оплаты может быть несколько имейлов. 

![screen shot 2014-05-06 at 2 25 11 pm](https://cloud.githubusercontent.com/assets/4335901/2895864/70b8e4f4-d565-11e3-8a52-847fafc8541b.png)

**Comment by DeveloperRegistry** [comment]
Release 1 or Release 2? How critical it is?

**Comment by Fetati** [comment]
Это очень критично - e-mail нужен для tax deduction. Получается, что charity получил реально товаров на 1 доллар, а в писме указано, что на 361! 
Будут проблемы с налоговой и у донора, и у charity и у нас.

Получив данный имейл, я решила посмотреть кому я еще покупала подарки, и не нашла на сайте. Поэтому и возникла вторая проблема, описанная в #220

**Comment by DeveloperRegistry** [comment]
OK, I will work on this.

**Comment by DeveloperRegistry** [comment]
Fixed and tested. Please test with multiple Donees. You should see multiple one email per donee.
