### ISSUE TITLE
Password Reset - confirmation email-wrong email sender

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#223]
![wrong email sender](https://cloud.githubusercontent.com/assets/7462589/2899619/e032f99c-d5b9-11e3-8f18-062d16dc3be0.jpg)
Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Click "Sigh in" button
3. Click "forgot password?" link
4. Type valid email address
5. Check your email box for "Password Reset" email

Observe: Sender of email - "Dmitry Shestialtynov dmitrys@ifface.com через sendgrid.info"  - is not formally related to GOODdler website

Reproduced all the time.

Expected Result: Receive email from: notify@gooddler.com or  noreply@gooddler.com

Windows 8.1
Mozilla Firefox 27.0

**Comment by DmitrysIF** [comment]
Это тестовый аккаунт stormpath. В релизе будет другой.
