### ISSUE TITLE
Different site and company which is not formally related to GOODdler website asking to reset password

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#224]
Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Click "Sigh in" button
3. Click "forgot password?" link
4. Type valid email address
5. Check your email box for "Password Reset" email.
6. Click Link in email to reset password.

Observe: During password reset a user is transferred to a different site and company, which is not formally related to GOODdler website and asked to reset password. After providing new password and password confirmation the user is not returned to the original location at GOODdler  website.

Reproduced all the time.

Expected Result: Password reset within GOODdler  website only.
![different site_company](https://cloud.githubusercontent.com/assets/7462589/2899824/5898a4e2-d5bd-11e3-8ca4-01aa1684f860.jpg)
![different site_company2](https://cloud.githubusercontent.com/assets/7462589/2899825/58a98302-d5bd-11e3-9a83-cad00d1b5e53.jpg)

Windows 8.1
Mozilla Firefox 27.0

**Comment by DmitrysIF** [comment]
У нас используется сторонний сервис для управления аккаунтами.
