### ISSUE TITLE
Confirmation email "Your password has been changed" is in the wrong format

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#225]
Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Click "Sigh in" button
3. Click "forgot password?" link
4. Type valid email address
5. Check your email box for "Password Reset" email.
6. Click Link in email to reset password.
7. Type new password and confirm password
8. Click "Submit"
9. After "Account Password Reset" message appear go to email box to check confirmation email "Your password has been changed"

Observe: 1. Sender of email - "Dmitry Shestialtynov dmitrys@ifface.com через sendgrid.info" - is not formally related to GOODdler website
2. "If your password was changed without your notice please contact dmitrys@ifface.com" - is not formally related to GOODdler website
3. "For general inquiries or to request support with your account, please email dmitrys@ifface.com" - is not formally related to GOODdler website
4. NOT A SINGLE WORD ABOUT GOODdler

Reproduced all the time.

Expected Result: 
1. Receive email from: support@gooddler.com or noreply@gooddler.com
2. "If your password was changed without your notice please contact support@gooddler.com" 
3. "For general inquiries or to request support with your account, please email support@gooddler.com" 
4. You can visit your GOODdler Account here:
http://gooddler.cloudapp.net/SignIn

Windows 8.1
Mozilla Firefox 27.0 
![wrong email sender2](https://cloud.githubusercontent.com/assets/7462589/2899873/9850409e-d5be-11e3-9362-2c0ca8dd4346.jpg)

**Comment by DmitrysIF** [comment]
Это тестовый аккаунт stormpath. В релизе будет другой.
