### ISSUE TITLE
Empty wishlist should not say 100% complete

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#226]
![screen shot 2014-05-07 at 4 20 23 pm](https://cloud.githubusercontent.com/assets/7177944/2910188/39967c1e-d63e-11e3-9088-e1ccf92fd177.png)
http://gooddler.cloudapp.net/Wishlist/40043

Between the time a wishlist created and items are added to it, we show that list is 100% completed. Can it be removed?

**Comment by galinafed** [comment]
I think it should say:

No items were added to this list. Please, click on Edit this Wishlist to add items.

**Comment by DeveloperRegistry** [comment]
Release 1 or Release 2. Please start stating if you need this for Go Live.

**Comment by DeveloperRegistry** [comment]
Dima, I know it is a big change. Can we create a common Util method for percentages and messages? Right now the same logic is duplicated in multiple CHTML pages.

**Comment by galinafed** [comment]
Sorry, i am a newbie here )) Release 2 is ok

**Comment by DmitrysIF** [comment]
@DeveloperRegistry 
_Dima, I know it is a big change. Can we create a common Util method for percentages and messages? Right now the same logic is duplicated in multiple CHTML pages._

Это довольно сложно будет, так как там используются разные источники для подсчета процентов.
