### ISSUE TITLE
Replace word Needed with Quantity

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#228]
![screen shot 2014-05-07 at 5 50 16 pm](https://cloud.githubusercontent.com/assets/7177944/2910737/b25b5618-d64a-11e3-84ef-c9138aaeb5f8.png)

The screen shows 1 on all wishlists, even though more is needed.

I suggest to replace word Needed with Quantity
what do you think?

**Comment by DeveloperRegistry** [comment]
I absolutely agree. "Needed" is very confusing. I vote for Release 1.  :+1:

**Comment by DmitrysIF** [comment]
@galinafed fixed
