### ISSUE TITLE
Grammar mistake. Adding administrator error message

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#229]
![screen shot 2014-05-07 at 7 00 16 pm](https://cloud.githubusercontent.com/assets/7177944/2911128/82aaf34c-d654-11e3-8c0b-ec6c734d20eb.png)

Should  say, ..... does not exist

Also, If there are no users added, is it possible not to have a box that says Username Action. I think it's confusing. It should appear only when admin is added.

Plus, correct this message "tatiana already has access for this donee" with ".... already has access to this donee"

![screen shot 2014-05-07 at 7 14 00 pm](https://cloud.githubusercontent.com/assets/7177944/2911206/6204e182-d656-11e3-9d5e-7867ced7b4f5.png)

**Comment by DmitrysIF** [comment]
@galinafed Fixed
