### ISSUE TITLE
Donee Page: Кнопка Donee’s wishlists битая

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#23]
При нажатии кнопки Donee’s wishlists выдает:

Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 
Requested URL: /blablablablab/

![screen shot 2014-04-07 at 10 44 44 pm](https://cloud.githubusercontent.com/assets/4335901/2640231/16ad6f6a-bee1-11e3-9a98-1d802f9e39ba.png)

**Comment by DmitrysIF** [comment]
Поправлено, будет в следующем обновлении.
