### ISSUE TITLE
Mismatch between (1) Donee donation amount in confirmation email and (2) the amount ("Money") for the Donee in User account on web site.

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#230]
![mismatch](https://cloud.githubusercontent.com/assets/7462589/2912153/e4a91d7c-d671-11e3-930e-b456f46cc9c0.jpg)
![mismatch2](https://cloud.githubusercontent.com/assets/7462589/2912154/e4a9946e-d671-11e3-84dd-362c44358dff.jpg)
![mismatch3](https://cloud.githubusercontent.com/assets/7462589/2912155/e4aa6baa-d671-11e3-8622-db54db619183.jpg)

Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Sigh in with valid data
3. Click on random scrolling picture
4. Choose an item, which you want to donate and click "Donate"
5. Click "Checkout" button
6. Type valid credit card data
7. Type valid "Billing Information" 
8. Click "Confirm and pay" button
9. Observe "Thank you for your generosity! ...... Save it as a receipt for your donation. "
10. Click link on <User name> in upper right corner.
11. Click "Donations of <User>" link
12. Observe all User donations (Money, Items, Donee Name ...)
13. Go to User email box and open confirmation email
14. Observe row "Total Donation Amount:     $" in email confirmation

Observe: Mismatch between (1) Donee donation amount in confirmation email and (2) the amount ("Money") for the Donee in User account on web site.

Expected Result: No mismatch between (1) Donee donation amount in confirmation email and (2) the amount ("Money") for the Donee in User account on web site.

Expected Result: 
Windows 8.1
Mozilla Firefox 27.0

**Comment by DeveloperRegistry** [comment]
It is a rounding issue. I will work on this,

**Comment by projectnew** [comment]
Thank you

**Comment by DeveloperRegistry** [comment]
Retested the defect. It is an old issue, which is now resolved. Closing as Not a Bug.
