### ISSUE TITLE
"Review" button doesn't work and not linked

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#233]
![review](https://cloud.githubusercontent.com/assets/7462589/2912753/060e7c10-d680-11e3-95cc-7903c7d01a92.jpg)

Steps:
1. Open web page http://gooddler.cloudapp.net/
2. Sigh in with valid data
3. Click on 3x3-dot icon (My GOODdler)
4. In drop down menu click "My Wishlist"
5. Click "Donation" button on random "Wishlist Name" 
6. Click "Review" button

Observe Error message "Server Error in '/' Application."

Expected Result: "Review" page to open correctly. User can review his donation. 

Reproduced all the time.

Windows 8.1
Mozilla Firefox 27.0

**Comment by DmitrysIF** [comment]
@Fetati Непонятно, что должна делать эта кнопка.

**Comment by DmitrysIF** [comment]
Hide Rewiew button
