### ISSUE TITLE
Mismatch in amounts for one Donee

### ISSUE THREAD

**Issue by projectnew** [Goodler/code#234]
![roses](https://cloud.githubusercontent.com/assets/7462589/2912788/a4fb90b0-d680-11e3-95ce-6a264bfea196.jpg)
![roses2](https://cloud.githubusercontent.com/assets/7462589/2912790/a516bb74-d680-11e3-9071-0a25daa28954.jpg)
![tulips](https://cloud.githubusercontent.com/assets/7462589/2912789/a50cd3b6-d680-11e3-9cd5-f6eef9d75a81.jpg)
![tulips2](https://cloud.githubusercontent.com/assets/7462589/2912792/a51ef3d4-d680-11e3-8ec8-2a08a916a7eb.jpg)
![tulips3](https://cloud.githubusercontent.com/assets/7462589/2912791/a51e9236-d680-11e3-9db1-2bdb52b0c236.jpg)

Mismatch among (all related to one Donee): 
1.  Total amount of purchases confirmed to User email.
2.  Total amount of  "Money" on page "Donation of User".
3. Total amount of  "Goal" on page "My Donees"
4. Total amount of  "Raised" on page "My Donees"

Reproduced 2 times.
Windows 8.1
Mozilla Firefox 27.0

**Comment by DeveloperRegistry** [comment]
Yes, valid issue.We will work on this under (#230)‏
