### ISSUE TITLE
items disappear from  " My cart " 

### ISSUE THREAD

**Issue by Elenarussian** [Goodler/code#236]
1. do not " Sing IN "
2. add items to " My cart "
3. go to Menu 
4. click " Sing Out "

bug : When click " Sing Out " all items disappear from " My cart "
expectations : user should be able to save items in " My Cart "
User shouldn't be able to do " Sing Out " if he doesn't " Sing IN " ?

![screen shot 2014-05-08 at 2 36 01 pm](https://cloud.githubusercontent.com/assets/7408823/2921815/e8bc33b8-d6f8-11e3-9ad6-02c8ac8ffc67.png)

**Comment by DmitrysIF** [comment]
Исправлено.
