### ISSUE TITLE
Wishlist statistics. Wrong?

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#239]
Что означает Items Donated? В данном вишлисте уже даже есть закрытая позиция на 30 items, то есть 42.38 % уже выполнено. Ошибка?

![screen shot 2014-05-10 at 10 43 15 am](https://cloud.githubusercontent.com/assets/4335901/2936682/a77255c2-d86a-11e3-98a6-9167a6b35114.png)

**Comment by DmitrysIF** [comment]
Да, ошибка выбора источника цифр, было непонятно тогда, что значит это поле.
Думаю, это требует к исправлению.

**Comment by DmitrysIF** [comment]
@Fetati исправлено
