### ISSUE TITLE
Как создавать посты?

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#24]

**Comment by DmitrysIF** [comment]
My Donee -> posts -> +posts;
My Wishlists -> +posts;

Есть проблемы с редактором, который позволяет кастомизировать текст дони, вишлиста и так далее. По-этому возможны ошибки при использовании кавычек и еще нескольких символов.
Исправляется.

**Comment by Fetati** [comment]
Не могу проверить, так как никак не могу завести Donee

**Comment by DmitrysIF** [comment]
Попробуйте сейчас завести дони.

**Comment by Fetati** [comment]
C Дони все в порядке, заводится. А вот пост выглядит криво: http://gooddler.cloudapp.net/Donee/10017

![screen shot 2014-04-09 at 9 40 36 am](https://cloud.githubusercontent.com/assets/4335901/2658237/f014bb62-c005-11e3-92c2-5daa23b3fe65.png)

**Comment by DmitrysIF** [comment]
Ага, хорошо - теперь тексты в превью будут чиститься от тегов и выводиться голым текстом. В следующем обновлении.

**Comment by DmitrysIF** [comment]
Проблема решена.
