### ISSUE TITLE
Error on My Donees Page - Needed for Go Live

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#240]
Steps to reproduce:

1) Delete all Donees (note: deleted through the database, not a logical delete)
2) Login to the Application
3) Select My Donees on the Menu

Error:
![image](https://cloud.githubusercontent.com/assets/3822498/2938112/52ec8e06-d8f0-11e3-9f96-49240808c79a.png)

**Comment by DmitrysIF** [comment]
Fixed
