### ISSUE TITLE
Arrows Dot not Work on IE

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#241]
Two issues:

1) Users can key in non-numeric data in the fields again
2) Arrows do not work on IE

To reproduce, go to any wishlist and try to donate on IE:

![image](https://cloud.githubusercontent.com/assets/3822498/2939748/354f943e-d958-11e3-9622-df76625cca86.png)

**Comment by DmitrysIF** [comment]
@DeveloperRegistry Fixed
