### ISSUE TITLE
Новый вишлист не появляется на главной странице

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#242]
Новый вишлист (http://gooddler.com/Wishlist/50047) не появляется на главной странице, хотя виден в списке вишлистов.
![screen shot 2014-05-11 at 8 57 48 pm](https://cloud.githubusercontent.com/assets/4335901/2940664/d341479c-d989-11e3-8daf-f18550b9d5fe.png)

вот он в списке вишлистов первый:
![screen shot 2014-05-11 at 8 57 53 pm](https://cloud.githubusercontent.com/assets/4335901/2940668/edbf02d0-d989-11e3-83b8-dafd0bad68fd.png)

**Comment by Fetati** [comment]
Нашла свою ошибку, и другой баг - я не выбрала Publish, поэтому лист не появился на главной странице.
Но тогда он не должен появляться и в общем списке вишлистов. А он там появился.

**Comment by DmitrysIF** [comment]
@Fetati Он там появляется только в том случае, если вы СуперАдминистратор или имеете права доступа к дони, которому принадлежит скрытый вишлист.

**Comment by DmitrysIF** [comment]
@Fetati закрыто :)
