### ISSUE TITLE
Make dates mm.dd.yyyy format

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#248]
In the US, dates are usually displayed in mm/dd/yyyy format. Please reverse Days and Months. Ideally, the year should be 4-digit.

16.05.14 should be 05.16.2014

Two places:

![image](https://cloud.githubusercontent.com/assets/3822498/3004252/9a5d24b0-dd89-11e3-98d2-75091ac8f671.png)

![image](https://cloud.githubusercontent.com/assets/3822498/3004300/c110abba-dd8c-11e3-874e-fbce29a797b9.png)

**Comment by DmitrysIF** [comment]
@DeveloperRegistry сделано - не деплоил.

**Comment by DmitrysIF** [comment]
Исправил.
