### ISSUE TITLE
Item Count on Donee and Wishlist Lists are Incorrect

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#249]
The total count of items should 20. However, currently we show only 6 items.

Also, On the Wishlist Items Should be Wishlist Total Items and Items Donated - the total of donated

![image](https://cloud.githubusercontent.com/assets/3822498/3004264/83cdf84a-dd8a-11e3-9169-b684332afda9.png)

![image](https://cloud.githubusercontent.com/assets/3822498/3004270/8b0c6eb0-dd8b-11e3-9049-9b5ebd905c98.png)

**Comment by DmitrysIF** [comment]
@DeveloperRegistry Fixed
