### ISSUE TITLE
UI: Дизайн ввода вишлиста поехал

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#250]
Browser - Chrome
http://gooddler.com/Wishlist/Edit/3
1) Поле ввода линка с Амазон - съехали стрелки прокрутки.
2) Названия полей поехали куда-то

![screen shot 2014-05-17 at 1 54 24 pm](https://cloud.githubusercontent.com/assets/4335901/3006052/9d0deff6-de05-11e3-92c5-4c2152efc48d.png)

**Comment by DmitrysIF** [comment]
@Fetati кнопки и таблицу поправил. Не забудьте очистить кэш.
