### ISSUE TITLE
UI: в вишлисте при добавлении товара таблица товаров сломана

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#251]
Добавила пятый item и таблица съехала (см. item 5):
![screen shot 2014-05-17 at 2 20 43 pm](https://cloud.githubusercontent.com/assets/4335901/3006093/34c7071c-de09-11e3-9dfd-f9ff738a9052.png)

**Comment by DmitrysIF** [comment]
@Fetati Исправил. Не забудьте почистить кэш.
