### ISSUE TITLE
UI: Post on the Main page - no "read more"

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#252]
Опять не видно Read More у постов на главной странице. Давайте или ограничим количество возможных знаков в заголовке, или давайте резать по этому определенному количеству.
Нормально помещается: We appreciate your generosity and commitment to animals. (около 50 знаков)

![screen shot 2014-05-17 at 3 27 20 pm](https://cloud.githubusercontent.com/assets/4335901/3006185/a5aa6baa-de12-11e3-8654-b88c84d2a741.png)

**Comment by DmitrysIF** [comment]
@Fetati сделал предварительную правку - теперь если текста много, то пост растягивается в высоту на главной странице.

**Comment by Fetati** [comment]
Было бы не плохо, если бы так было. Но я не вижу, что растягивается в высоту. Вижу read more, но обрывает текст на полуслове.
![screen shot 2014-05-17 at 10 23 48 pm](https://cloud.githubusercontent.com/assets/4335901/3006780/b8238c8c-de4c-11e3-9c84-ecbc5859a315.png)

**Comment by DmitrysIF** [comment]
Вернул количество символов обратно до 75,
сохранил растягивание высоты.
