### ISSUE TITLE
В мобильной версии не работает кнопка Menu

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#254]
В мобильной версии не работает кнопка Menu

**Comment by DmitrysIF** [comment]
Ну... она и не должна там работать - в сенсорниках нету курсора, который бы вызывал событие hover для значка.

**Comment by Fetati** [comment]
Сайт должень работать полноценно с любых устройств и браузеров. 

К примеру сайт svod.org - первая картинка как выглядит меню в мобильной версии, вторая - если нажать на значок меню:
![image](https://cloud.githubusercontent.com/assets/4335901/3007933/f001fcac-dea5-11e3-85c6-878d45e838d3.jpg)

**Comment by DeveloperRegistry** [comment]
I believe the issue is resolved. Please re-open the defect if I am not correct.
