### ISSUE TITLE
Donee page: посты криво выглядят

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#255]
Donee page: посты криво выглядят - read more находит на текст (Chrome и iPhone)
http://gooddler.com/Donee/4

![screen shot 2014-05-17 at 10 25 57 pm](https://cloud.githubusercontent.com/assets/4335901/3006784/188625a8-de4d-11e3-8276-5fda23e660d5.png)

**Comment by DmitrysIF** [comment]
Да, это последствия прошлой правки. Буду думать, как переделать.

**Comment by DmitrysIF** [comment]
Исправил.
