### ISSUE TITLE
Update Donee Fails with Status Message: Sorry, Error on a server

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#26]
Steps to Re-create:

1) Login into the application
2) Create Donee with description
3) Save Donee
4) Click on Donee to get to update page
5) Enter some additional text in the description text area and click Update Donee. Error message will be displayed next to View Donee:  Status Message: Sorry, Error on a server

**Comment by DeveloperRegistry** [comment]
Note: this was logged by Anton under Tanya's login. The issue was discovered with Chrome browser in local dev

**Comment by DmitrysIF** [comment]
Причина найдена - исправления будут в силе после следующего обновления.

**Comment by DmitrysIF** [comment]
Проверьте и закройте этот issue, если все нормально.
