### ISSUE TITLE
Wrong date

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#260]
Should be Pacific Time and in US format - mm/dd/yy

Post №2 was made 05/18/2014, but we can see it as May 19

http://gooddler.com/Admin/Posts

![screen shot 2014-05-18 at 6 30 44 pm](https://cloud.githubusercontent.com/assets/4335901/3009348/5bb850fa-def5-11e3-8803-5fdbd97ab3dc.png)

**Comment by DeveloperRegistry** [comment]
Closed as a duplicate. See #296
