### ISSUE TITLE
My Cart: после sign out вишлист обнуляется

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#261]
До sign out:
![screen shot 2014-05-18 at 6 58 31 pm](https://cloud.githubusercontent.com/assets/4335901/3009429/4f490752-def9-11e3-9f5e-941c576520e0.png)

После того, как я signed out, а потом опять signed in, корзина оказалась пустая:

![screen shot 2014-05-18 at 6 59 01 pm](https://cloud.githubusercontent.com/assets/4335901/3009433/7188967a-def9-11e3-81f0-13798615c973.png)

Все отложенные товары должны сохраняться.

**Comment by DeveloperRegistry** [comment]
Disabled logic for clearing shopping cart during sign out. It can be enabled if needed. Passed unit test.
