### ISSUE TITLE
When entering credit card information month does not let you enter double digit starting with 0

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#263]
When you are purchasing item and entering credit card expiration date, i was not able to enter 05, or any other number starting with 0. It was changing that number to 01.
Only when i entered 5, it took it and changed it to 05.
We can change MM to M, giving customers instruction to only enter 1 digit, or we have to fix the issue.

**Comment by DeveloperRegistry** [comment]
It is a big deal. I will do my best to fix it ASAP. Hopefully, tonight.

**Comment by DeveloperRegistry** [comment]
Traced the issue to JavaScript. Corrected the problem. Passed unit test. Deploying to Prod.
