### ISSUE TITLE
Edit Profile Hints: Change social media hints

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#266]
http://gooddler.com/Profile/Edit?welcome=1
Facebook hint Давайте поменяем Васю Пупкина на кого-то не русского :)
Например, https://www.facebook.com/BillGates
![screen shot 2014-05-23 at 1 23 41 pm](https://cloud.githubusercontent.com/assets/4335901/3071487/44d593fe-e2b8-11e3-89bb-1e114c422a2b.png)

LinkedIn Hint:
Подсказка наезжает на текст ниже. 
И заменить линк на www.linkedin.com/pub/frederic-descamps/0/84/423
![screen shot 2014-05-23 at 1 24 55 pm](https://cloud.githubusercontent.com/assets/4335901/3071546/f3b81c02-e2b8-11e3-8328-ab0ef5f96bdf.png)

**Comment by Denastus** [comment]
Done
