### ISSUE TITLE
During check out, if a person is not logged in, automatically forward to the Login/Sign Up page 

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#269]
During check out, if a person is not logged in, automatically forward to the Login/Sign Up page rather then enter credit card info. When login/signup is completed, return to the checkout page.

![image](https://cloud.githubusercontent.com/assets/3822498/3073761/886770c6-e306-11e3-9560-f438b7aa1759.png)

**Comment by DeveloperRegistry** [comment]
Tanya, I need your input on the following UI change.

Test Scenario: I am a brand new user. I selected an item in a wishlist and clicked Check Out. The system automatically forwarded me to this page where I am asked to Sign Up. Upon Sign Up/Sign In  completion I will be forwarded back to the Check Out Page where I can complete the purchase.

Proposed UI Change to the Sign In page: add Sign Up button or Hyperlink. Options: 1) Could be a large button 2) Could be a small hyperlink similar to the Forgot Password. Please let me know what you think.

![image](https://cloud.githubusercontent.com/assets/3822498/3101387/518cc832-e633-11e3-8111-7660476b9227.png)

**Comment by Fetati** [comment]
Я думаю, что надо отделить кнопку от полей sign in. 
Например, текстом: 
Don't have Gooddler account? Sign Up here
и ниже кнопка, как на картинке.

**Comment by DeveloperRegistry** [comment]
Sounds good. Will do.

**Comment by DeveloperRegistry** [comment]
Implemented the change. Tested the functionality. To make the feature to work correctly, we need to quickly fix this:
https://github.com/Goodler/code/issues/278
