### ISSUE TITLE
Сделать разные e-mails letters for tax deductible donations and not tax dedactible

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#271]
У нас есть donees, которые не имеют статуса, необходимого для tax deduction. 
Можно ли сделать другое письмо для имейл рассылки при покупке товаров для них? (я пришлю в почту образец письма)

**Comment by DeveloperRegistry** [comment]
It can be done. It could be a slightly larger change. I propose to add an indicator to each Donee telling us if they have a Tax Deductible status. The indicator can be displayed on the Donee Create/Edit page. Initially, I can set the indicator to Yes for everybody. You can set the indicator to No for the ones who are not qualified. Based on the indicator I can select a different email template.

What do you think?

**Comment by Fetati** [comment]
Да, отлично!!!

**Comment by Fetati** [comment]
Галя подготовила письмо для не tax-deductible charities. Расшерит в гуглдок.

**Comment by DeveloperRegistry** [comment]
Added a new template for charities, which are not tax-deductible. Implemented an indicator on Create/Edit donee page identifying tax donee tax-deductible status. Added new images to the View Wishlist page showing donee status.
