### ISSUE TITLE
Post: убрать заголовок Post 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#272]
Убрать заголовок "Post" из всех постов
http://gooddler.com/Blog/Post/10006

**Comment by Fetati** [comment]
Убрать заголовок Post во всех постах и Author в автоматических постах
![screen shot 2014-06-22 at 4 04 17 pm](https://cloud.githubusercontent.com/assets/4335901/3352866/9a62f300-fa61-11e3-9a20-4aac4e22278e.png)

**Comment by DeveloperRegistry** [comment]
Implemented under 
Delete "Post" word from every post #301
