### ISSUE TITLE
Posts: old title again

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#290]
Опять старый заголовок у постов. Что-то слетело:
![screen shot 2014-06-13 at 1 16 22 pm](https://cloud.githubusercontent.com/assets/4335901/3275110/c104134e-f337-11e3-9e7e-e920fffe91b4.png)

**Comment by DeveloperRegistry** [comment]
The titles were not implemented. The "Big Thank's" title was hard-coded for all posts. Added titles from the provided above document. Passed unit test: made several purchases and correct titles were displayed. The issue is resolved.
