### ISSUE TITLE
Urgent: Impossible to add admin by email address

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#291]
can't add admin by email address. Box says email/username, but email doesn't work. Have to have username. 

![screen shot 2014-06-17 at 4 28 09 pm](https://cloud.githubusercontent.com/assets/4335901/3344044/86e78258-f8a6-11e3-987f-67c29242b230.png)

Мы обязательно должны иметь возможность добавлять имейлами. Потому что никогда не знаешь, какой юзернейм люди используют.

**Comment by DeveloperRegistry** [comment]
Rejecting defect as Not a Bug. I confirmed that the functionality of adding by Email coded and works in Test. I also went to Prod, deleted ayen@sfspca.org user from access and added him back by email address. The functionality works. Rejecting defect. We may need to follow up with user ayen@sfspca.org and ask to ignore extra notification email.
