### ISSUE TITLE
На странице Donee должны быть все поля, которые они заносили в режиме администратора

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#293]
На странице Donee должны быть все поля, которые они заносили в режиме администратора:
Address, e-mail, phone number, website.

По образцу, как я сделала вручную тут:
![screen shot 2014-06-23 at 8 52 25 pm](https://cloud.githubusercontent.com/assets/4335901/3367054/d846bd12-fb53-11e3-8e6f-be518610a8a8.png)

**Comment by DeveloperRegistry** [comment]
Sounds good. 
Note: this appears to be an enhancement
