### ISSUE TITLE
Boy Scouts of America, Pacific Skyline Council - отредактировать стиль названия вишлиста

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#294]
Название и текст в вишлисте Boy Scouts of America, Pacific Skyline Council выглядит очень не красиво. Надо отцентрировать по левому краю. 
Солидная организация, им не понравится, как мы сделали страницу для них. Надо поправить.
![screen shot 2014-06-23 at 9 24 45 pm](https://cloud.githubusercontent.com/assets/4335901/3367166/e73790e0-fb57-11e3-97b9-cbce6eaa8607.png)

**Comment by DeveloperRegistry** [comment]
Sounds good. We will fix it.

**Comment by Denastus** [comment]
Done
