### ISSUE TITLE
URGENT: change titles of automatic posts

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#295]
У нас начались покупки на вишлистах, а там все блоги с заголовками с орфографическими ошибками. Надо СРОЧНО исправить!

![screen shot 2014-06-24 at 5 15 25 pm](https://cloud.githubusercontent.com/assets/4335901/3380235/4b4d60a6-fc01-11e3-8c17-86ecfc0fe721.png)

**Comment by DeveloperRegistry** [comment]
Please provide examples so I could find it.

**Comment by Fetati** [comment]
Я уже исправила, чтобы никто не видел ошибки)) Было Big THANK'S! 
А надо, как в этом документе:
https://docs.google.com/document/d/1DERMk0TvAgGpQwnZIWLL4IXPXdpbmU2lrNqjYwoULQw/edit

К каждому посту свой заголовок.
Мы как-то это уже меняли, и работало. Опять слетело.

**Comment by DeveloperRegistry** [comment]
Implemented under Posts: old title again #290
