### ISSUE TITLE
What time we use? 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#296]
Уже идут продажи от 25 июня, хотя у нас еще пока 24-е. Надо сделать PST
![screen shot 2014-06-24 at 5 47 36 pm](https://cloud.githubusercontent.com/assets/4335901/3380294/6de252ba-fc02-11e3-9a33-23b0fe60cf93.png)

**Comment by DeveloperRegistry** [comment]
I think we have some sort of Russian time. Will change as needed.

**Comment by Fetati** [comment]
Duplicate issue 260 (assigned to Max Fridman)

**Comment by DeveloperRegistry** [comment]
I will need to change the time in the database. Also, we potentially need to convert all persisted timestamps to PST. Re-assigned to me.

**Comment by DeveloperRegistry** [comment]
The time is presently stored in UTC format in the database. Modified the application to convert all dates from UTC to PST when data is pulled from the database. Tested with accounts referenced in the defect. Confirmed that 7-hour offset is applied prior to displayed the data.
