### ISSUE TITLE
Password reset is still at Stormpath

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#297]
У нас до сих пор password reset не на gooddler, что выглядит довольно подозрительно. Я бы испугалась делать reset пароля, если бы увидела, что с меня пароль просит какой-то другой ресурс. Причем, там Gooddler нигде не указан. И нигде в форме не объяснено, почему левая контора просит пароль.

Надо поменять.

![screen shot 2014-06-26 at 10 55 06 am](https://cloud.githubusercontent.com/assets/4335901/3402379/4c4055a8-fd5b-11e3-9072-eee0c523815d.png)

**Comment by DeveloperRegistry** [comment]
Presently, our security is managed by Stormpath. This is why users are taken to the Stormpath page for changing passwords. I have to research if it is even possible to do password changes on our page. I also need to research if we need to keep to Stormpath or start storing encrypted password locally. We pay for Stormpath; however, their functionality is somewhat limited. 

In any case we need to create a design of our own Password Changing page.
