### ISSUE TITLE
Main page: scale of donations - make round to the whole numbers

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#305]
Should be 20%, 11%, 3% 
![screen shot 2014-06-29 at 1 30 44 pm](https://cloud.githubusercontent.com/assets/4335901/3424368/80e2ef0a-ffcc-11e3-8bd7-cc704a084884.png)

**Comment by DeveloperRegistry** [comment]
Assigned to me. Should be simple rounding change.

**Comment by DeveloperRegistry** [comment]
Changed Main Page, All Wishlists, My Wishlist, View Donee and View Wishlist pages. Will be deployed with the next release.
