### ISSUE TITLE
SEO: change Meta Description and Title

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#307]
Title: DO GOOD, donate gifts, be GOODdler

Meta Description: GOODdler - donate gifts as a donation! GOODdler is social enterprise committed to creating a more generous world by tapping into the growing market of online giving and focusing on younger generation that seeks concrete results from its gifts. Our international platform allows charities to post specific items needed to achieve organization’s goals for supporters to purchase. Items will be delivered by local distributors and received directly by charity without any monetary exchange and administrative costs.

Keywords: donate gifts, donating gifts, donating gifts to charity, donating gifts to children, donating gifts to pets, charitable giving, donating gifts to homeless shelters, donating gifts to seniors

**Comment by DeveloperRegistry** [comment]
The change is implemented and deployed to Prod. Ran the check on http://www.seocentro.com/tools/search-engines/metatag-analyzer.html

Results:
Meta tags report for: http://www.gooddler.com
meta tag    length  value
Title:   34 DO GOOD, donate gifts, be GOODdler
Description:     512    GOODdler - donate gifts as a donation! GOODdler is social enterprise committed to creating a more generous world by tapping into the growing market of online giving and focusing on younger generation that seeks concrete results from its gifts. Our international platform allows charities to post specific items needed to achieve organization’s goals for supporters to purchase. Items will be delivered by local distributors and received directly by charity without any monetary exchange and administrative costs.

Meta tags analysis.
Title:  Title contains no errors.
This tag contains 34 characters.
Title relevancy to page content is very good.
The Title relevancy to page content is 83%.
Description:    Description meta tag is too long.
This tag contains 512 characters. This is too many for what we would consider a 'robot friendly' description. The maximum number of characters we recommend for this tag is 200.
Description meta tag relevancy to page content is fair.
The Description meta tag relevancy to page content is 51%.

Web page analysis.
The size of the web page.
The size of the web page is 22214 bytes.
The web page load time.
The web page load time is 1 seconds.

Your site displayed on a search engine page.
DO GOOD, donate gifts, be GOODdler
GOODdler - donate gifts as a donation! GOODdler is social enterprise committed to creating a more generous world by tapping into the growing market of online ...
http://www.gooddler.com

Keywords found in the Anchor tags: Keyword - Times Found.
These are text links on your web page (include the 'alt' text from images in the links). These become more important by many search engines (for best results try to name them after your primary keywords).
read more - 20
humane society of truckee-tahoe - 9
mothers group of kashin russia - 7
do - 6
16 jun 2014 - 3
28 jun 2014 - 3
san francisco spca - 3
24 jun 2014 - 3
26 jun 2014 - 3
my cart - 2
friends for youth - 2
boy scouts of america pacific skyline council - 2
1 jun 2014 - 1
my donations - 1
getting ready for school donate gifts to children in need - 1
pet socialization program - 1
facebook - 1
about - 1
17 jun 2014 - 1
gooddler - 1
my wishlists - 1
my profile - 1
changing lives through camp activities - 1
my donees - 1
google+ - 1
my posts - 1
20 jun 2014 - 1
donate toys to pets - 1
twitter - 1
terms - 1
5 jun 2014 - 1
sign up - 1
help - 1
sign in - 1
blog - 1
checkout - 1
2 jul 2014 - 1
25 jun 2014 - 1
youtube - 1
12 jun 2014 - 1
sf spca foster program - 1
30 jun 2014 - 1
donate gifts to academic support and life skills workshops friends for youth - 1
how it works - 1

Keywords found in the IMG Alt tags: Keyword - Times Found.
This is text found in the 'alt' tag from the images. For web pages with a lot of images those tags are important (for best results try to name them after your primary keywords).
gooddler - 1
view all wishlists - 1

Keywords found on page: Keyword - Times Found - Keyword Density.
These are keywords found on the web page. These are the keywords where the web page is target for (probably contain the most searches for this web page one of these keywords).
more - 20 - 3.58%
read - 20 - 3.58%
2014 - 20 - 3.58%
jun - 19 - 3.41%
group - 10 - 1.79%
help - 10 - 1.79%
humane - 9 - 1.61%
my - 9 - 1.61%
kashin - 9 - 1.61%
thank - 9 - 1.61%
mothers - 9 - 1.61%
truckee-tahoe - 9 - 1.61%
society - 9 - 1.61%
we - 8 - 1.43%
russia - 7 - 1.25%
need - 7 - 1.25%
mission - 6 - 1.08%
do - 6 - 1.08%
spca - 4 - 0.72%
gifts - 4 - 0.72%
thanks - 3 - 0.54%
16 - 3 - 0.54%
donate - 3 - 0.54%
super - 3 - 0.54%
francisco - 3 - 0.54%
24 - 3 - 0.54%
support - 3 - 0.54%
san - 3 - 0.54%
big - 3 - 0.54%
26 - 3 - 0.54%
youth - 3 - 0.54%
friends - 3 - 0.54%
28 - 3 - 0.54%
cart - 3 - 0.54%
pets - 2 - 0.36%
program - 2 - 0.36%
donation - 2 - 0.36%
ecstatic - 2 - 0.36%
every - 2 - 0.36%
appreciated - 2 - 0.36%
$0 - 2 - 0.36%
council - 2 - 0.36%
scouts - 2 - 0.36%
us - 2 - 0.36%
getting - 2 - 0.36%
america - 2 - 0.36%
boy - 2 - 0.36%
2013 - 2 - 0.36%
day - 2 - 0.36%
sign - 2 - 0.36%
skyline - 2 - 0.36%
generous - 2 - 0.36%
item - 2 - 0.36%
gooddler - 2 - 0.36%
grateful - 2 - 0.36%
pacific - 2 - 0.36%
world - 2 - 0.36%
changing - 1 - 0.18%
sf - 1 - 0.18%
facebook - 1 - 0.18%
socialization - 1 - 0.18%
daria - 1 - 0.18%
life - 1 - 0.18%
immensely - 1 - 0.18%
interest - 1 - 0.18%
goods - 1 - 0.18%
20 - 1 - 0.18%
alex - 1 - 0.18%
story - 1 - 0.18%
heal - 1 - 0.18%
foster - 1 - 0.18%
activities - 1 - 0.18%
found - 1 - 0.18%
gesture - 1 - 0.18%
donees - 1 - 0.18%
checkout - 1 - 0.18%
dog - 1 - 0.18%
donations - 1 - 0.18%
toys - 1 - 0.18%
profile - 1 - 0.18%
way - 1 - 0.18%
17 - 1 - 0.18%
ho - 1 - 0.18%
like - 1 - 0.18%
special - 1 - 0.18%
refugee - 1 - 0.18%
workshops - 1 - 0.18%
camp - 1 - 0.18%
friendship - 1 - 0.18%
very - 1 - 0.18%
toward - 1 - 0.18%
total - 1 - 0.18%
google+ - 1 - 0.18%
3.44% - 1 - 0.18%
goal - 1 - 0.18%
receive - 1 - 0.18%
achieving - 1 - 0.18%
ready - 1 - 0.18%
1.42% - 1 - 0.18%
twitter - 1 - 0.18%
excited - 1 - 0.18%
terms - 1 - 0.18%
thrilled - 1 - 0.18%
works - 1 - 0.18%
cool - 1 - 0.18%
share - 1 - 0.18%
get - 1 - 0.18%
through - 1 - 0.18%
jeanne - 1 - 0.18%
happy - 1 - 0.18%
international - 1 - 0.18%
spent - 1 - 0.18%
highly - 1 - 0.18%
know - 1 - 0.18%
skills - 1 - 0.18%
not - 1 - 0.18%
children - 1 - 0.18%
supporter - 1 - 0.18%
kim - 1 - 0.18%
2.61% - 1 - 0.18%
posts - 1 - 0.18%
list - 1 - 0.18%
celebrate - 1 - 0.18%
difference - 1 - 0.18%
people - 1 - 0.18%
love - 1 - 0.18%
achieve - 1 - 0.18%
inc - 1 - 0.18%
did - 1 - 0.18%
goes - 1 - 0.18%
donating - 1 - 0.18%
making - 1 - 0.18%
school - 1 - 0.18%
20th - 1 - 0.18%
able - 1 - 0.18%
wishlists - 1 - 0.18%
academic - 1 - 0.18%
west - 1 - 0.18%
purchase - 1 - 0.18%
12 - 1 - 0.18%
greatly - 1 - 0.18%
exciting - 1 - 0.18%
kardashian - 1 - 0.18%
30 - 1 - 0.18%
51.2 - 1 - 0.18%
jul - 1 - 0.18%
25 - 1 - 0.18%
promote - 1 - 0.18%
end - 1 - 0.18%
helped - 1 - 0.18%
8.56% - 1 - 0.18%
penny - 1 - 0.18%
best - 1 - 0.18%
kanye - 1 - 0.18%
up - 1 - 0.18%
needed - 1 - 0.18%
chloe’s - 1 - 0.18%
loving - 1 - 0.18%
great - 1 - 0.18%
20.00% - 1 - 0.18%
blog - 1 - 0.18%
picked - 1 - 0.18%
lives - 1 - 0.18%
pet - 1 - 0.18%
youtube - 1 - 0.18%
june - 1 - 0.18%
items - 1 - 0.18%
11.41% - 1 - 0.18%
read more - 20 - 3.58%
jun 2014 - 19 - 3.41%
mothers group - 9 - 1.61%
humane society - 9 - 1.61%
2014 humane - 8 - 1.43%
kashin russia - 7 - 1.25%
mission do - 6 - 1.08%
2014 mothers - 6 - 1.08%
francisco spca - 3 - 0.54%
28 jun - 3 - 0.54%
16 jun - 3 - 0.54%
big thanks - 3 - 0.54%
26 jun - 3 - 0.54%
truckee-tahoe we - 3 - 0.54%
san francisco - 3 - 0.54%
truckee-tahoe thank - 3 - 0.54%
more 24 - 3 - 0.54%
more 26 - 3 - 0.54%
more 28 - 3 - 0.54%
24 jun - 3 - 0.54%
more 16 - 3 - 0.54%
support read - 2 - 0.36%
help read - 2 - 0.36%
do donate - 2 - 0.36%
donate gifts - 2 - 0.36%
america pacific - 2 - 0.36%
pacific skyline - 2 - 0.36%
russia we - 2 - 0.36%
my cart - 2 - 0.36%
skyline council - 2 - 0.36%
russia big - 2 - 0.36%
boy scouts - 2 - 0.36%
gifts read - 2 - 0.36%
appreciated read - 2 - 0.36%
my donations - 1 - 0.18%
day read - 1 - 0.18%
2.61% need - 1 - 0.18%
camp activities - 1 - 0.18%
spca 1.42% - 1 - 0.18%
works 20.00% - 1 - 0.18%
my posts - 1 - 0.18%
$0 checkout - 1 - 0.18%
thanks daria - 1 - 0.18%
promote donating - 1 - 0.18%
$0 sign - 1 - 0.18%
life skills - 1 - 0.18%
through camp - 1 - 0.18%
17 jun - 1 - 0.18%
1.42% need - 1 - 0.18%
2014 san - 1 - 0.18%
daria pets - 1 - 0.18%
pet socialization - 1 - 0.18%
special dog - 1 - 0.18%
skills workshops - 1 - 0.18%
people read - 1 - 0.18%
25 jun - 1 - 0.18%
ho read - 1 - 0.18%
30 jun - 1 - 0.18%
refugee day - 1 - 0.18%
world refugee - 1 - 0.18%
more 25 - 1 - 0.18%
russia 11.41% - 1 - 0.18%
more 17 - 1 - 0.18%
council thank - 1 - 0.18%
2014 kim - 1 - 0.18%
highly appreciated - 1 - 0.18%
do pet - 1 - 0.18%
greatly appreciated - 1 - 0.18%
foster program - 1 - 0.18%
2014 chloe’s - 1 - 0.18%
gooddler inc - 1 - 0.18%
west promote - 1 - 0.18%
goods goes - 1 - 0.18%
pets san - 1 - 0.18%
cart my - 1 - 0.18%
youth friends - 1 - 0.18%
51.2 read - 1 - 0.18%
socialization program - 1 - 0.18%
2014 june - 1 - 0.18%
super excited - 1 - 0.18%
inc facebook - 1 - 0.18%
ecstatic every - 1 - 0.18%
my gooddler - 1 - 0.18%
need mothers - 1 - 0.18%
2013 gooddler - 1 - 0.18%
donate toys - 1 - 0.18%
my wishlists - 1 - 0.18%
my donees - 1 - 0.18%
program san - 1 - 0.18%
more 12 - 1 - 0.18%
found us - 1 - 0.18%
spca foster - 1 - 0.18%
sf spca - 1 - 0.18%
school donate - 1 - 0.18%
do getting - 1 - 0.18%
2014 friends - 1 - 0.18%
2014 boy - 1 - 0.18%
council 8.56% - 1 - 0.18%
june 20th - 1 - 0.18%
program humane - 1 - 0.18%
lives through - 1 - 0.18%
gooddler my - 1 - 0.18%
get help - 1 - 0.18%
my profile - 1 - 0.18%
every penny - 1 - 0.18%
day did - 1 - 0.18%
generous donation - 1 - 0.18%
russia thank - 1 - 0.18%
super exciting - 1 - 0.18%
more 20 - 1 - 0.18%
jul 2014 - 1 - 0.18%
goes toward - 1 - 0.18%
posts my - 1 - 0.18%
kim kardashian - 1 - 0.18%
cart total - 1 - 0.18%
youtube google+ - 1 - 0.18%
toward achieving - 1 - 0.18%
super needed - 1 - 0.18%
difference thank - 1 - 0.18%
12 jun - 1 - 0.18%
more 30 - 1 - 0.18%
donation read - 1 - 0.18%
11.41% need - 1 - 0.18%
20.00% need - 1 - 0.18%
twitter youtube - 1 - 0.18%
loving group - 1 - 0.18%
celebrate international - 1 - 0.18%
donations my - 1 - 0.18%
3.44% need - 1 - 0.18%
getting ready - 1 - 0.18%
us read - 1 - 0.18%
youth heal - 1 - 0.18%
best way - 1 - 0.18%
blog help - 1 - 0.18%
changing lives - 1 - 0.18%
academic support - 1 - 0.18%
truckee-tahoe 2.61% - 1 - 0.18%
ecstatic thank - 1 - 0.18%
alex super - 1 - 0.18%
sign up - 1 - 0.18%
2013 51.2 - 1 - 0.18%
more 2013 - 1 - 0.18%
wishlists my - 1 - 0.18%
youth 3.44% - 1 - 0.18%
activities boy - 1 - 0.18%
chloe’s story - 1 - 0.18%
do sf - 1 - 0.18%
profile my - 1 - 0.18%
do changing - 1 - 0.18%
immensely grateful - 1 - 0.18%
20 jun - 1 - 0.18%
donees my - 1 - 0.18%
kanye west - 1 - 0.18%
total $0 - 1 - 0.18%
facebook twitter - 1 - 0.18%
dog helped - 1 - 0.18%
terms blog - 1 - 0.18%
international day - 1 - 0.18%
picked us - 1 - 0.18%
workshops friends - 1 - 0.18%
spca every - 1 - 0.18%
kashin we - 1 - 0.18%
8.56% need - 1 - 0.18%
very special - 1 - 0.18%
every item - 1 - 0.18%
donating gifts - 1 - 0.18%
generous gesture - 1 - 0.18%
truckee-tahoe big - 1 - 0.18%
jun 2014 humane - 8 - 1.43%
2014 humane society - 8 - 1.43%
2014 mothers group - 6 - 1.08%
jun 2014 mothers - 6 - 1.08%
read more 24 - 3 - 0.54%
san francisco spca - 3 - 0.54%
more 28 jun - 3 - 0.54%
more 24 jun - 3 - 0.54%
28 jun 2014 - 3 - 0.54%
26 jun 2014 - 3 - 0.54%
read more 28 - 3 - 0.54%
read more 26 - 3 - 0.54%
24 jun 2014 - 3 - 0.54%
more 16 jun - 3 - 0.54%
read more 16 - 3 - 0.54%
16 jun 2014 - 3 - 0.54%
more 26 jun - 3 - 0.54%
america pacific skyline - 2 - 0.36%
gifts read more - 2 - 0.36%
help read more - 2 - 0.36%
kashin russia we - 2 - 0.36%
russia big thanks - 2 - 0.36%
kashin russia big - 2 - 0.36%
pacific skyline council - 2 - 0.36%
mission do donate - 2 - 0.36%
appreciated read more - 2 - 0.36%
support read more - 2 - 0.36%
through camp activities - 1 - 0.18%
kashin russia 11.41% - 1 - 0.18%
highly appreciated read - 1 - 0.18%
read more 30 - 1 - 0.18%
program humane society - 1 - 0.18%
francisco spca every - 1 - 0.18%
west promote donating - 1 - 0.18%
read more 17 - 1 - 0.18%
read more 2013 - 1 - 0.18%
special dog helped - 1 - 0.18%
do sf spca - 1 - 0.18%
my wishlists my - 1 - 0.18%
gooddler my donees - 1 - 0.18%
pets san francisco - 1 - 0.18%
kashin russia thank - 1 - 0.18%
17 jun 2014 - 1 - 0.18%
more 20 jun - 1 - 0.18%
skills workshops friends - 1 - 0.18%
my posts my - 1 - 0.18%
generous donation read - 1 - 0.18%
youth 3.44% need - 1 - 0.18%
my profile my - 1 - 0.18%
truckee-tahoe big thanks - 1 - 0.18%
more 2013 gooddler - 1 - 0.18%
inc facebook twitter - 1 - 0.18%
kanye west promote - 1 - 0.18%
my cart total - 1 - 0.18%
jun 2014 friends - 1 - 0.18%
read more 25 - 1 - 0.18%
2013 gooddler inc - 1 - 0.18%
20 jun 2014 - 1 - 0.18%
total $0 sign - 1 - 0.18%
gooddler inc facebook - 1 - 0.18%
ecstatic every penny - 1 - 0.18%
international day read - 1 - 0.18%
donations my profile - 1 - 0.18%
socialization program humane - 1 - 0.18%
12 jun 2014 - 1 - 0.18%
do changing lives - 1 - 0.18%
people read more - 1 - 0.18%
2014 chloe’s story - 1 - 0.18%
day read more - 1 - 0.18%
do donate gifts - 1 - 0.18%
jul 2014 kim - 1 - 0.18%
profile my cart - 1 - 0.18%
skyline council thank - 1 - 0.18%
mission do changing - 1 - 0.18%
do pet socialization - 1 - 0.18%
my donees my - 1 - 0.18%
program san francisco - 1 - 0.18%
donating gifts read - 1 - 0.18%
my gooddler my - 1 - 0.18%
read more 12 - 1 - 0.18%
2014 kim kardashian - 1 - 0.18%
thanks daria pets - 1 - 0.18%
russia 11.41% need - 1 - 0.18%
spca every item - 1 - 0.18%
alex super exciting - 1 - 0.18%
25 jun 2014 - 1 - 0.18%
mission do getting - 1 - 0.18%
2014 june 20th - 1 - 0.18%
francisco spca 1.42% - 1 - 0.18%
us read more - 1 - 0.18%
2014 boy scouts - 1 - 0.18%
pet socialization program - 1 - 0.18%
more 30 jun - 1 - 0.18%
big thanks daria - 1 - 0.18%
world refugee day - 1 - 0.18%
ho read more - 1 - 0.18%
goes toward achieving - 1 - 0.18%
2014 san francisco - 1 - 0.18%
jun 2014 chloe’s - 1 - 0.18%
jun 2014 boy - 1 - 0.18%
spca foster program - 1 - 0.18%
camp activities boy - 1 - 0.18%
spca 1.42% need - 1 - 0.18%
30 jun 2014 - 1 - 0.18%
goods goes toward - 1 - 0.18%
cart my cart - 1 - 0.18%
school donate gifts - 1 - 0.18%
more 17 jun - 1 - 0.18%
donation read more - 1 - 0.18%
my cart my - 1 - 0.18%
skyline council 8.56% - 1 - 0.18%
truckee-tahoe 2.61% need - 1 - 0.18%
works 20.00% need - 1 - 0.18%
51.2 read more - 1 - 0.18%
greatly appreciated read - 1 - 0.18%
mission do pet - 1 - 0.18%
posts my donations - 1 - 0.18%
donees my wishlists - 1 - 0.18%
foster program san - 1 - 0.18%
facebook twitter youtube - 1 - 0.18%
refugee day did - 1 - 0.18%
more 12 jun - 1 - 0.18%
council 8.56% need - 1 - 0.18%
terms blog help - 1 - 0.18%
promote donating gifts - 1 - 0.18%
sf spca foster - 1 - 0.18%
do donate toys - 1 - 0.18%
jun 2014 june - 1 - 0.18%
wishlists my posts - 1 - 0.18%
life skills workshops - 1 - 0.18%
very special dog - 1 - 0.18%
2013 51.2 read - 1 - 0.18%
read more 20 - 1 - 0.18%
do getting ready - 1 - 0.18%
changing lives through - 1 - 0.18%
my donations my - 1 - 0.18%
celebrate international day - 1 - 0.18%
jun 2014 san - 1 - 0.18%
found us read - 1 - 0.18%
twitter youtube google+ - 1 - 0.18%
mission do sf - 1 - 0.18%
more 25 jun - 1 - 0.18%
cart total $0 - 1 - 0.18%
need mothers group - 1 - 0.18%
lives through camp - 1 - 0.18%
activities boy scouts - 1 - 0.18%

URLs found in the page: URL - Times Found
Found 83 urls from where 56 unique.
http://www.gooddler.com/Donee/7 - 9
http://www.gooddler.com/Donee/10001 - 7
http://www.gooddler.com/MyCart - 3
http://www.gooddler.com/Donee/4 - 3
http://www.gooddler.com/Donee/5 - 2
http://www.gooddler.com/Wishlist/4 - 2
http://www.gooddler.com/Wishlist/3 - 2
http://www.gooddler.com/Donee/6 - 2
http://www.gooddler.com/Wishlist/6 - 2
http://www.gooddler.com/Wishlist/7 - 2
http://www.gooddler.com/ - 2
http://www.gooddler.com/Wishlist/10001 - 2
http://www.gooddler.com/Wishlist/5 - 2
http://www.gooddler.com/Profile - 1
http://www.gooddler.com/Admin/Posts - 1
http://www.gooddler.com/SignIn/ - 1
http://www.gooddler.com/Blog/Post/30014 - 1
http://www.gooddler.com/Blog/Post/10010 - 1
http://www.gooddler.com/Content/css/base.css - 1
http://www.gooddler.com/Blog/Post/30022 - 1
http://www.gooddler.com/Content/css/layout.css - 1
http://www.gooddler.com/Blog/Post/30013 - 1
http://www.gooddler.com/SignUp/ - 1
http://www.gooddler.com/Blog/Post/30017 - 1
http://www.gooddler.com/Help - 1
http://www.gooddler.com/Blog/Post/20011 - 1
http://www.gooddler.com/Admin/Wishlists - 1
http://www.gooddler.com/Blog/Post/30015 - 1
http://gooddler.wordpress.com/ - 1
http://www.gooddler.com/ConditionsOfUse - 1
http://www.gooddler.com/HowItWorks - 1
http://www.gooddler.com/Wishlists - 1
http://twitter.com/GOODDler - 1
http://plus.google.com/+Gooddler/ - 1
http://www.gooddler.com/Content/css/normalize-2.1.3.css - 1
http://www.gooddler.com/Blog/Post/20013 - 1
http://www.gooddler.com/Blog/Post/30011 - 1
http://www.gooddler.com/Blog/Post/30016 - 1
http://www.facebook.com/gooddler - 1
http://www.gooddler.com/Blog/Post/30019 - 1
http://www.gooddler.com/Blog/Post/30021 - 1
http://www.gooddler.com/Blog/Post/20010 - 1
http://www.gooddler.com/Blog/Post/10009 - 1
http://www.gooddler.com/Admin/Donees - 1
http://www.gooddler.com/Blog/Post/30018 - 1
http://www.youtube.com/user/gooddler - 1
http://www.gooddler.com/CheckOut/ - 1
http://www.gooddler.com/Content/css/carousel.css - 1
http://www.gooddler.com/Blog/Post/30012 - 1
http://www.gooddler.com/About - 1
http://www.gooddler.com/Blog/Post/30020 - 1
http://www.gooddler.com/Blog/Post/20012 - 1
http://www.gooddler.com/Blog/Post/30010 - 1
http://www.gooddler.com/Profile/MyDonations - 1
http://www.gooddler.com/Blog/Posts - 1
http://www.gooddler.com/Blog/Post/20009 - 1

Headers returned from: http://www.gooddler.com
 connection:     close
 set-cookie:     x-sids-g=z062d918f92e0a41db8e933ef20eaac8a66936dd83f524a4c4d614728be7551c15a19b767; domain=.gooddler.com; expires=Fri, 03-Jul-2015 06:50:01 GMT; path=/; HttpOnly
 cache-control:      private
 date:   Thu, 03 Jul 2014 06:50:03 GMT
 client-peer:    191.236.101.25:80
 client-date:    Thu, 03 Jul 2014 06:54:42 GMT
 x-aspnetmvc-version:    5.1
 content-type:   text/html; charset=utf-8
 server:     nginx/1.6.0
 x-meta-description:     GOODdler - donate gifts as a donation! GOODdler is social enterprise committed to creating a more generous world by tapping into the growing market of online giving and focusing on younger generation that seeks concrete results from its gifts. Our international platform allows charities to post specific items needed to achieve organization’s goals for supporters to purchase. Items will be delivered by local distributors and received directly by charity without any monetary exchange and administrative costs.
 x-powered-by:   ASP.NET
 client-response-num:    1
 x-meta-charset:     utf-8
 content-length:     22214
 x-aspnet-version:   4.0.30319
 title:      DO GOOD, donate gifts, be GOODdler
