### ISSUE TITLE
SEO Main Page: change link from "read more" to something with our keywords

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#308]
SEO: change links from "read more" to something with our keywords

**Comment by Fetati** [comment]
Delete "read more". 
Make a title of post as a link.

**Comment by DeveloperRegistry** [comment]
Re-assigned to me

**Comment by DeveloperRegistry** [comment]
Changed hyperlinks from Read More to the current title. Please re-open this defect if additional changes are needed.
