### ISSUE TITLE
Change wording on the main page (scale field) 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#310]
Change wording on the main page's scales: - delete all words and leave "complete"
Example: 20% complete
![screen shot 2014-07-03 at 11 56 18 am](https://cloud.githubusercontent.com/assets/4335901/3474427/cadc89c6-02e3-11e4-93e3-74b3d6e80e7b.png)

**Comment by DeveloperRegistry** [comment]
Clarification Question: we have similar percentage bars on several pages. Should we update them all or just the front page?

**Comment by Fetati** [comment]
all of them

**Comment by DeveloperRegistry** [comment]
Replaced all messages (there were four different messages depending on % complete) with the word "complete". It will be deployed with the next release.
