### ISSUE TITLE
Post: format text

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#311]
1) increase amount of signs to 500 (at least)
2) leave some space right - text is too close to the border

![screen shot 2014-07-03 at 4 14 42 pm](https://cloud.githubusercontent.com/assets/4335901/3476817/1d93fb9e-0308-11e4-811e-ae4462a43376.png)

**Comment by DeveloperRegistry** [comment]
1) increased the amount of signs to 500 
2) Added 15px padding to the right border
