### ISSUE TITLE
Meta Title: add "GOODdler" 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#313]
Should be:
GOODdler | DO GOOD, donate gifts, be GOODdler

![screen shot 2014-07-03 at 8 45 58 pm](https://cloud.githubusercontent.com/assets/4335901/3478128/f536437a-032d-11e4-815b-d21e3cf53336.png)

**Comment by DeveloperRegistry** [comment]
Assigned to Max

**Comment by Denastus** [comment]
Changed title. Done.
