### ISSUE TITLE
Post hyperlink: don't cut words

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#315]
Post hyperlink: don't cut words (look at the right post). Better to stop at full word and add dots (like left post)

![screen shot 2014-07-06 at 12 51 04 am](https://cloud.githubusercontent.com/assets/4335901/3488453/9be3e30a-04e4-11e4-882d-7446142c4683.png)

**Comment by DeveloperRegistry** [comment]
Implemented a universal method to ensure that words are longer cut. The method can be re-used for other texts as well. The change will be deployed with the next release.
