### ISSUE TITLE
SMM: Share my donations on Facebook and other Social media

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#322]
Share my donation on Facebook (вот какой я добрый - пожертвовал деньги, но главное здесь может быть вирусный эффект)

Facebook, Twitter, LinkedIn

**Comment by Fetati** [comment]
http://www.huffingtonpost.com/robert-rubinstein/millennial-recruitment-impact-investing_b_5691544.html?utm_hp_ref=business&ir=Business
вот тут неплохо реализовано

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
Актуален ли этот issues?
