### ISSUE TITLE
UX: Update your cart option should be added to the flow

### ISSUE THREAD

**Issue by ghost** [Goodler/code#34]
Must have:
Steps:
1. add 3-4 items to your cart
2. go to cart and delete 1 item
3. observe the cart and total amount $ on the screen and amount of items

Bug/Improvement: have update your cart btn to refresh the page with all necessary updates associated with it ( number of items, amount, cart, order of items and etc)
![items amount](https://cloud.githubusercontent.com/assets/7193843/2646216/241dde50-bf3b-11e3-9753-4268c076490c.png)

**Comment by DmitrysIF** [comment]
Fixed.
