### ISSUE TITLE
Design: Change "..." to "[...]" everywhere

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#342]
Please change "..." to [...]
Example:
1) main page, post: http://gooddler.com/
Inspiring Partnership Announcement: Toyota is an official automotive partner [...]

2) Posts http://gooddler.com/Blog/Posts:
![posts_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/3694518/1f2ddf3a-1373-11e4-98f8-6bad1183836d.png)

**Comment by DeveloperRegistry** [comment]
Implemented the change. Deployed to Prod.
