### ISSUE TITLE
Main Page UX: It would be nice to have a carousel for images instead of backward and forward option

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#344]
We need to make slow auto rotation of our wishlists on the main page.

**Comment by DeveloperRegistry** [comment]
Great idea. Sounds good.

**Comment by DeveloperRegistry** [comment]
Implemented the following:

1) Auto-rotation every 5 seconds (can be changed if needed)
2) On PC/MAC (not mobile) selected wishlist will be high-lighted (border raised)
3) When user's mouse if over the wishlist, the auto-rotation gets paused

Deployed to Prod.

**Comment by Fetati** [comment]
При вращении появляются 3 пустых места. Должен быть полный цикл, без пропусков. 
(Chrome и Safari)
![screen shot 2014-08-10 at 6 43 24 pm](https://cloud.githubusercontent.com/assets/4335901/3871388/423f46c4-20f9-11e4-964f-7b1341c1f740.png)
![screen shot 2014-08-10 at 6 43 29 pm](https://cloud.githubusercontent.com/assets/4335901/3871389/4246a82e-20f9-11e4-8676-31ee222cea5d.png)

**Comment by Fetati** [comment]
"On PC/MAC (not mobile) selected wishlist will be high-lighted (border raised)" - love it!!!

**Comment by DeveloperRegistry** [comment]
Fixed the issue. Please refresh (F5) prior to retesting the issue
