### ISSUE TITLE
Create New Post should be at the top of the page

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#348]
On "My Posts" page: "Create New Post" should be at the top of the page, so it's easy to see.
![screenshot 28](https://cloud.githubusercontent.com/assets/7177944/3785692/8fc41ab0-19c8-11e4-8e2e-c10a35ae463d.png)

**Comment by DeveloperRegistry** [comment]
Re-assigned to Max. Simple change - just relocate the Create New Post button. Alternatively, we can add one on top and keep the one on the bottom. Ask Galya and Tanya for input.

**Comment by galinafed** [comment]
Would be great to have on top and keep one at the bottom.

**Comment by Denastus** [comment]
Done and ready for review.
