### ISSUE TITLE
Donee Page: Add address and website 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#349]
Example here:
http://www.gooddler.com/Donee/7
We need:
- Address
- Phone
- Website

Except e-mail address.

**Comment by DeveloperRegistry** [comment]
We do not have a Website Attribute for Donee. Should we add it to the Create/Edit Donee page? If yes, Required or Optional?

**Comment by DeveloperRegistry** [comment]
Added Website Attribute to Create/Edit Donee. 

On View Donee page, added Address, Phone, Email (only for Admins) and Sub-Domain as per Tanya's Request
