### ISSUE TITLE
UI Wording: Delete the word "Donee" from Donee page, etc

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#351]
http://www.gooddler.com/Donee/7
1) "Edit Donee" - should be just "(Edit)"
2) "Edit" should be placed close to Donee name. Like here:
![donee_page_aug14](https://cloud.githubusercontent.com/assets/4335901/3802637/715006fc-1c11-11e4-9b17-d1118cbf7cf1.jpg)

3) Donee's wishlists - should be "Our Wishlists"

**Comment by DeveloperRegistry** [comment]
Implemented 1, 2 and 3.
