### ISSUE TITLE
Urgent: Wislist's completed articles should be locked!!! Closed articles should not be able to be modified.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#353]
Wislist's completed articles should be locked. Closed articles should not be able to be modified.

We have problem with that already - HSTT. They removed one that was completed and replaced it with a different one (metal gate and added 1 more tree to the tree that was completed. So on one they exchanged the item, on another they added. 

It's impossible to control everything.

**Comment by Fetati** [comment]
Если в позиции хотя бы один товар куплен, дони не должны иметь возможность удалить эту позицию. А только уменьшить количество необходимых товаров.

**Comment by DeveloperRegistry** [comment]
Added a check for modifying Shipping Cost and Quantity on Completed Items: "You cannot update completed Item. Please create a new Item".‏

Prevented users from deleting if at least one item purchased: "You cannot change shipping cost and quantity for completed".
