### ISSUE TITLE
Urgent: notification to us (administrators) if article completed

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#354]
Мы уже сейчас немного путаемся. Надо, чтобы когда закрыта позиция, мы получали уведомление, чтобы мы отправили товар. Сейчас это делаем вручную. И если товар похож, то приходится прилагать усилие, чтобы вспомнить какой товар был отправлен

**Comment by DeveloperRegistry** [comment]
Implemented two notifications: Article Completion and Wishlist Completion. Deployed to Prod.
