### ISSUE TITLE
Link to Donee website should be open in new tab

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#360]
Link to Donee website should be open in new tab. We can't take people away from our website.
![screen shot 2014-08-20 at 12 56 42 pm](https://cloud.githubusercontent.com/assets/4335901/3987317/5b0ecffa-28a4-11e4-803f-494ba79ce197.png)

**Comment by DeveloperRegistry** [comment]
Assigned to Max. Change ViewDonee.chtml only

**Comment by Denastus** [comment]
Done
