### ISSUE TITLE
Security issue: I can see our donors and amount they donated in google. Without Sign In.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#361]
![screen shot 2014-08-27 at 9 07 52 pm](https://cloud.githubusercontent.com/assets/4335901/4071040/f8485a88-2e68-11e4-88f1-cf6fc5ff28b5.png)

![screen shot 2014-08-27 at 9 08 06 pm](https://cloud.githubusercontent.com/assets/4335901/4071044/00a5e790-2e69-11e4-8f07-0c39220afd4b.png)

All admin's pages could be available without any protection and without signing in

![screen shot 2014-08-27 at 9 10 01 pm](https://cloud.githubusercontent.com/assets/4335901/4071057/3c0491a6-2e69-11e4-9154-5437f43228eb.png)

**Comment by DeveloperRegistry** [comment]
Started to hide dollar amounts line unless user is an Admin or the profile owner. Applied the same rule to the View Donation link. Deployed to Prod.
