### ISSUE TITLE
Urgent: Items in the cart have the link to Amazon

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#366]
Items in the cart have the link to Amazon (even the person is not signed in):
![screen shot 2014-09-15 at 12 14 20 pm](https://cloud.githubusercontent.com/assets/4335901/4277218/a3759630-3d0c-11e4-8a25-aa75c2b0a0eb.png)

А на Амазоне может быть цена, выше, чем указана на gooddler:
![screen shot 2014-09-15 at 12 14 32 pm](https://cloud.githubusercontent.com/assets/4335901/4277227/b2d72256-3d0c-11e4-9ea8-f4f13426ae54.png)

**Comment by DeveloperRegistry** [comment]
Removed the link from the cart for all users. The fix will be deployed shortly.
