### ISSUE TITLE
Donee page: Broken link to website

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#367]
URL link goes to http://www.gooddler.com/Donee/miriamskitchen.org
![screen shot 2014-09-22 at 1 10 41 pm](https://cloud.githubusercontent.com/assets/4335901/4363390/11f790bc-4295-11e4-9f68-bf94e1c1d75e.png)

**Comment by DeveloperRegistry** [comment]
Links need to pre-fixed with http://. Added the required format to the Edit Donee page: Website (Please use http://... format)
