### ISSUE TITLE
Missed one letter in "Gooddler" - L - ОЧЕПЯТКА

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#368]
http://  ________.goodder.com - add L letter
![screen shot 2014-09-22 at 2 28 47 pm](https://cloud.githubusercontent.com/assets/4335901/4364389/8a875076-429f-11e4-966f-e738c08f3ae5.png)

**Comment by DeveloperRegistry** [comment]
Corrected to gooddler.com
