### ISSUE TITLE
Create a Delete Button for Donees for Admin Users Only

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#37]
How can we delete donees?

**Comment by DmitrysIF** [comment]
На данный момент подобной функции в дизайнах нет.

**Comment by DeveloperRegistry** [comment]
Dima and Nikita, we discussed this with Tanya. We believe we need this functionality. I wonder if you could add it for Admin Users only? Another option, I can could code the change and ask Dima to Peer Review the change. Please let me know the best way to proceed. Thank you.

**Comment by DmitrysIF** [comment]
Антон занимается этим. Оказываю всяческую поддержку.

**Comment by DeveloperRegistry** [comment]
Coded new functionality: Delete Donee, Delete Wishlist and Delete Post. The delete buttons can be found on Edit Pages. Also, posts have Delete icon in the list view. Deleting Donee also deletes Wishlists and Posts.

Critical Note: we used Logical Delete approach. Data is marked in the database as Deleted but retained for records and potential restoration. Deleted records are hidden from users.
