### ISSUE TITLE
Facebook Share buttons

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#373]
Хорошо бы, чтобы название кнопок фейсбука были не share или like, a что-то типа invite friends.

1) Donee Page: Title - название Donee, текст - первое предложение из описания donee
2) Wishlist: заголовок и текст как сейчас при вставке линка на ФБ - из описания вишлиста
3) При завершении покупки pop-up с предложением расшерить на ФБ. Надо придумать хороший текст типа "я только что помог ___. Присоединяйся, твоя помощь необходима".. или что-то в духе. 
4) Posts - Обычные кнопки, как у блогов

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
Название сменить на invite friends на всех соцкнопок (G+, FB, LinkedIn, Twitter)? Или же для каждой кнопки своё?
Оцените, пожалуйста, актуальность этого issues. Есть/Нет в нем нужда, если есть - что изменилось.
