### ISSUE TITLE
Pre-approvals needed for publishing lists

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#378]
Since we set shipping costs manually, we need to establish a system of preapprovals of all new wishlists.  ASAP It is pretty important! We have to be notified that someone is trying to publish a list so we can adjust cost of shipping.

**Comment by DeveloperRegistry** [comment]
Please confirm. We just need an email to all Admins when a new Wishlist is created?

**Comment by galinafed** [comment]
first is notification, second it shouldn't go live until we approve it. because we have to manually adjust shipping. Thus, i would think it would be appropriate that when a list is created and charity is publishing it, a pop up notification will say: Thank you for creating a wishlist. It needs to be approved before it goes public. Please, allow 24 hours to see it live. Thank you for your patience! 
It means that we have to have some feature that says OK to publish, or something like that. Just for now, until we have affiliate partnership set up.

**Comment by DeveloperRegistry** [comment]
All requested features are implemented. Please note that Super Admins will not see a Pop Up about approval. Only regular users will see the Pop Up Message. Publishing by Super-Admins approves the wishlist by default. Please let me know if you have questions about approval process.
