### ISSUE TITLE
UX: Wording on some sections should be corrected

### ISSUE THREAD

**Issue by ghost** [Goodler/code#38]
Just go over every page and see where we used 2 words and make sure its capitalized 
![capial let](https://cloud.githubusercontent.com/assets/7193843/2652208/4d19cc00-bfa5-11e3-8e98-aa636363d2b5.png)
![spel](https://cloud.githubusercontent.com/assets/7193843/2652227/bc29f9e4-bfa5-11e3-8726-019bf6796da6.png)

**Comment by DmitrysIF** [comment]
Буквы поправил, будет в следующем обновлении.

**Comment by ghost** [comment]
Thank you. Don't see it now. will check later
