### ISSUE TITLE
Header: Color of the cart

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#381]
Color of the cart should be white, if the cart is empty. And it should be orrange, if there is something in the cart:
Now the color is white for small width (iphone, etc), and orrange for 1025 etc
![screen shot 2014-11-02 at 2 08 22 pm](https://cloud.githubusercontent.com/assets/4335901/4877245/5e1ac1ae-62e2-11e4-889b-2563dc8d5ffc.png)

![screen shot 2014-11-02 at 2 08 47 pm](https://cloud.githubusercontent.com/assets/4335901/4877246/62ed22da-62e2-11e4-9810-151568d39cd8.png)

**Comment by Fetati** [comment]
It's very important because if you add something in the cart nothing happens. It feels like you can't add stuff in the cart. You should go to the cart and check if your stuff is there. It is not intuitive.

**Comment by Fetati** [comment]
Can we do like this? Number of items in the cart
![screen shot 2014-11-12 at 7 29 27 pm](https://cloud.githubusercontent.com/assets/4335901/5022912/5c7cabce-6aa2-11e4-8176-2434d2141e6c.png)

**Comment by DeveloperRegistry** [comment]
Yes, but will require some coding changes. It is not a simple change. I will discuss with Anzhelo.
