### ISSUE TITLE
Can not verify server identity message

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#385]
On my phone: When I clicked on check out (I was not logged in), box appeared: 
![image](https://cloud.githubusercontent.com/assets/7177944/4981490/72ff538c-6909-11e4-94be-0c31c3b801c8.jpg)

**Comment by DeveloperRegistry** [comment]
Galina, what page are you testing? Please verify with me what pages are delivered before logging any defects. You can only test the Main Page and View Wishlist. Everything else is still under development.

**Comment by galinafed** [comment]
i was just trying to purchase an item on my phone, not testing any particular page.

**Comment by DeveloperRegistry** [comment]
We are not ready yet to test full flow. The My Cart and Checkout pages are currently under development. Please close the defect. These UIs will change. 

The Main Page and View Wishlist can be tested.
