### ISSUE TITLE
Notifications: Wishlist changes

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#389]
Notification:
- that the list was Updated (when a user pushes Update button)
- adding new Items, 
- changing amounts

Information:
Name of Charity
Name of wishlist
What happened: the list was Updated, added new items (можно указать какие?), changed amount (name of good)

**Comment by DeveloperRegistry** [comment]
Implemented the changes. Also, fixed the bug where non-admin user could un-approve already approved list.
