### ISSUE TITLE
Social sharing buttons: Facebook shows only a link, not text I write

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#399]
I wrote some text:
![screen shot 2014-11-24 at 12 03 14 pm](https://cloud.githubusercontent.com/assets/4335901/5172269/4447f1f0-73d3-11e4-86f4-ca0cbfd6fb1a.png)

This is what I see on FB:

![screen shot 2014-11-24 at 12 03 33 pm](https://cloud.githubusercontent.com/assets/4335901/5172305/868038a2-73d3-11e4-90d1-5e12171fac22.png)

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
Проверьте актуальность этого issues.
