### ISSUE TITLE
Форма ввода кредитной карты неюзабельна.

### ISSUE THREAD

**Issue by RealBerd** [Goodler/code#4]
Очень плохо сделан ввод номеров во всех полях.

После заполнения первых 4-х цифр нужно чтобы фокус переводился на следующее поле. Ограничть эти поля до 4-х символов максимум.

Для остальных полей тоже самое: где две цифры, должны быть только две цифры и желательно перескаивание фокуса тоже сделать.

http://i.imgur.com/yqODRrF.png

Плюс, почему-то не проходит тестовый платёж если ввести месяц Январь, Февраль или Март (не зависимо от года) оно ругется, что месяц слишком маленький.

**Comment by DmitrysIF** [comment]
Сделал.
