### ISSUE TITLE
If user pasted text into the field "About" (Edit Profile Flow) form Linked in, FB or any other sources, it gives an error 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#41]
Steps: 
1. goto profile
2. tap edit
3. in "About" add some copied text form lets say your Linked in profile

BUG: it gives you an error and does not save. if you type (not copy paste) it saves the changes

![error putting more info](https://cloud.githubusercontent.com/assets/7193843/2652303/203a9e14-bfa8-11e3-8d0e-90d85ef7e7b5.png)

**Comment by DmitrysIF** [comment]
Если вы находите ошибки, которые связаны со вводимыми данными - не забывайте так же приводить данные, которые вы вводили для вызова ошибки!
Проблемой может быть что угодно - от ошибки передачи данных до запрещенных символов в строке запроса, которое генерируется из введенных данных.

**Comment by ghost** [comment]
Good point. Will do.
In this particular case it was copied text from my Linked In Account.

**Comment by DmitrysIF** [comment]
Ошибка сейчас еще существует? Я недавно делал обновление, которое устраняло серьезную ошибку в визивиг-редакторе. Возможно - она и была причиной найденного вами бага.

**Comment by DmitrysIF** [comment]
?????????????.

2014-04-11 2:02 GMT+09:00 TShket notifications@github.com:

**Comment by ghost** [comment]
checking

**Comment by ghost** [comment]
Works fine:)) Thank you so much Dima
But have a couple questions, let me know if you want me to log in those issues  separately
1. can we make FB, TW , IN icons in color ( UX more recognizable among users) i think i had a ticket for that
2. can we use that empty space for ABOUT info? it will reduce the amount of space an scrolling- even though user will not put a lot of info but who knows:)
   ![user this area](https://cloud.githubusercontent.com/assets/7193843/2683059/adeabe8a-c1a4-11e3-8bd6-6ae45c259f54.png)
3. if enter a link into About can that be viewed as link? if not its fine, user can copy and paste.
   ![link](https://cloud.githubusercontent.com/assets/7193843/2683088/26c4d070-c1a5-11e3-9361-d1336410a5b0.png)
   ![user this area](https://cloud.githubusercontent.com/assets/7193843/2683089/26c4de6c-c1a5-11e3-96bb-f8ad93b1c8a3.png)

**Comment by DmitrysIF** [comment]
Чем заполнить пустое пространство - идей нету :)
Цветные иконки? Любые иконки можно поставить - исходники бы получить.
Сделать активными ссылки в тексте? Подумаем над этим вопросом.

**Comment by ghost** [comment]
Can we make a text space wider under the profile picture? Basically when text is posted we can display it in column first and then once the space gets bigger we allow text to go all the way to the left side.

**Comment by DmitrysIF** [comment]
Я заполнил пустое пространство. По поводу ссылок в тексте - это будет точно не сейчас.

**Comment by ghost** [comment]
well done. love it. thank you @DmitrysIF
