### ISSUE TITLE
Pop up needed to indicate that items were added to the cart

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#411]
I would like to see pop up saying "Added" every time someone adds an item to the cart. Otherwise, people are having a difficult time purchasing.
![screen shot 2014-12-14 at 11 19 56 am](https://cloud.githubusercontent.com/assets/7177944/5429792/53640d68-83af-11e4-8ae0-9b54139bc4a1.png)

**Comment by DeveloperRegistry** [comment]
Implemented. Tested the Web and Mobile. Pop Up colors, buttons and headers can be changed if needed. Please log a separate defect for Pop Up changes.
