### ISSUE TITLE
mobile wishlist: "To Cart" button is still active in the completed articles

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#414]
mobile wishlist: "To Cart" button is active in completed articles, and if i click on it, it shows "added", but it is not.
![wishlist bug](https://cloud.githubusercontent.com/assets/4335901/5449952/faffe50c-84b2-11e4-98a2-f96605f72acd.PNG)

**Comment by DeveloperRegistry** [comment]
Implemented the fix
