### ISSUE TITLE
Incorrect calculation of % complete

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#429]
Shows only partial completion even though it is 100% complete.
http://www.gooddler.com/Wishlist/10013
![screenshot 39](https://cloud.githubusercontent.com/assets/7177944/5769503/61173ab2-9cd1-11e4-8aaf-67cc577d029e.png)

**Comment by DeveloperRegistry** [comment]
Found numerous bugs across the application related to calculating totals. At least 12 wishlists were impacted.  Built centralized logic for recalculating wishlist totals. The logic is called during all core operations: Add, Delete, Update Price, Update Shipping, Update Quantity. Fixed totals for 12 wishlists as a part of the deployment.
