### ISSUE TITLE
После создания чего-то нового должна открываться страница этого нового

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#43]
После создания чего-то нового должна открываться страница этого нового, а не оставаться режим редактирования. А то кажется, что тебя не пускают дальше, так как есть какие-то ошибки.

Например, Create Donee или Create Post, etc

**Comment by DmitrysIF** [comment]
Вопрос - как это нужно реализовать? Просто перекидывать на страницу дони/поста/вишлиста/etc, как она есть и дальше пользователь должен будет принудительно кликнуть "редактировать", если что-то не понравится?

**Comment by Fetati** [comment]
Да. Это куда более логично и привычно, чем оставлять людей на странице редактирования.

**Comment by DmitrysIF** [comment]
Для дони, вишлиста перенаправление на созданную страницу реализовано.

**Comment by DmitrysIF** [comment]
Нужно еще сделать для поста?

**Comment by Fetati** [comment]
Да, для поста тоже надо.

**Comment by DmitrysIF** [comment]
Сделано :)
