### ISSUE TITLE
Can we have reports work with Raiser's Edge? (urgent)

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#431]
We have a large non-profit that we would LOVE to work with that uses Raiser's Edge. They write:
"we log all of our donations into our database, Raiser’s Edge. So any reports of donations for the week, month, etc., would need to be imported into the database. Can you send me a sample of a report, so I can see the fields and determine if the data can be imported easily?"
https://www.blackbaud.com/fundraising-and-relationship-management/raisers-edge-nxt?gclid=Cj0KEQiAiuOlBRCU-8D6idaPz_UBEiQAzTagNCrISYSKH41ClkKC0XVvrMSB2CBLPfQt4fw9XIaK9CgaAmpE8P8HAQ

**Comment by DeveloperRegistry** [comment]
We could try to create a custom extract for them in Excel or CSV format. I need to see a sample report with the fields they expect. You can forward them one of our Excel reports that we previously generated. Please remove private and  sensitive data.

**Comment by galinafed** [comment]
Yes, that's what i was told. I called Raiser's Edge, they said. It is Excel spreadsheet with CSV file extension. Then charity can call once and set up a template.
