### ISSUE TITLE
Social media buttons - FB doesn't work

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#434]
Impossible to share. Nothing happened if you share on FB.

If I post a link, it looks like a link, no preview.

This is how it looks like - I see a notification about post, but the post is not available
![screen shot 2015-02-04 at 2 23 22 pm](https://cloud.githubusercontent.com/assets/4335901/6051053/885909d6-ac79-11e4-8f4a-92c6d4e4d4a5.png)

Twitter button should give a text and link, and gooddler twitter link and hashtag: 
@gooddler #gooddler 

Let's use existing solutions, like https://www.addthis.com/get/sharing-buttons for example

**Comment by DmitrysIF** [comment]
Запрос актуален?

**Comment by DmitrysIF** [comment]
Спасибо!
