### ISSUE TITLE
Delete pop-up "Item Added" from web

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#435]
Delete pop-up "Item Added" from web. It doesn't look good.

![screen shot 2015-03-09 at 10 38 41 am](https://cloud.githubusercontent.com/assets/4335901/6560601/a3dd3202-c648-11e4-9366-9537cd001d1a.png)

**Comment by DeveloperRegistry** [comment]
Implemented the change. The dialog is displayed only for Mobile version.
