### ISSUE TITLE
Post: Из поста не понятно, как вернуться обратно. Ошибка в заголовке.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#44]
Из поста не понятно, как вернуться обратно, и не понятно где ты. Хорошо бы указать, к чему этот пост имеет отношения на странице поста

![screen shot 2014-04-09 at 9 45 05 am](https://cloud.githubusercontent.com/assets/4335901/2658270/724ffccc-c006-11e3-9db0-6872f46c1347.png)

**Comment by Fetati** [comment]
Серый текст с серым логотипом Goddler - это формат Donee name, а не заголовок поста. Надо сюда вставить линк имя дони. А заголовок должен быть просто текстом ниже.

**Comment by DmitrysIF** [comment]
Так, я сделал обновления - мне бы очень хотелось получить набросок того, что мы ожидаем увидеть в итоге на странице поста.

**Comment by DmitrysIF** [comment]
Повторюсь :)
Что хотим получить в итоге? Текущий вариант устраивает?

**Comment by Fetati** [comment]
отлично. Закрываю.
