### ISSUE TITLE
Wrong financial information: AllDonations page

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#440]
![screen shot 2015-04-20 at 2 23 24 pm](https://cloud.githubusercontent.com/assets/4335901/7240888/64f212aa-e769-11e4-95f5-c71f641f0ec4.png)

First person spent $16.84 total in 3 charities. 
Second person - $22.06 in 2 charities and $22.92 in another, total $44.98. Not 22.06x2 + 22.92, as shown in the table.
As we can see, the system counts total sum for each charity. It means, 3 times more than it is in reality.

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
В изучении.

**Comment by DmitrysIF** [comment]
Исправлено, ошибки в базе данных нет, была только ошибка в выборе источника данных для страницы списка пожертвований -  ранее данные брались из ChargeLog, изменил источник данных на DonationLog, так что теперь верные суммы будут показываться для всех пожертвований. Так же внёс небольшие косметические изменения, вроде нумерации строк и панель перехода по номерам страниц.
