### ISSUE TITLE
How to change an address on a wishlist?

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#443]
I am unable to uncheck the box to change it.
Any trick?
![screenshot 42](https://cloud.githubusercontent.com/assets/7177944/7499028/e3521a7e-f3d9-11e4-92f0-1cfae5919d71.png)

**Comment by galinafed** [comment]
:) of course, makes sense.

**Comment by galinafed** [comment]
Need to come up with an easy way to tell charities how to add more addresses. One of my charities also tried to look for it on Wishlist page. May be we can do: Edit Address link. Ideas?

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
Идея такая - мы рядом со списком адресов ставим пометку note со ссылкой, что-то вроде "Если вы хотите добавить адрес - пойдите сюда и добавьте", можно придумать еще автоматическое прокручивание страницы до блока адресов, если пользователь пришел по ссылке с Create/Edit Wishlist. Или же эту "ноту" разместить в блоке с "?".

**Comment by DmitrysIF** [comment]
@galinafed, @Fetati  Взгляните, пожалуйста.

**Comment by galinafed** [comment]
Yes, i would say: 
To change/add address click HERE:

Longer version could be:
To change this address or add a new one click HERE:

I think that shorter version will do the trick.

**Comment by DmitrysIF** [comment]
@galinafed, @Fetati - check it, please!
Возможно, потребуется подкорректировать текст tooltip.

**Comment by DmitrysIF** [comment]
Закрою тогда тогда этот Issues. Если что - можно будет открыть вновь.

**Comment by galinafed** [comment]
it looks good

Galina Fedorova

2015-06-11 12:41 GMT-07:00 DmitrysIF notifications@github.com:
