### ISSUE TITLE
Add note to Access List

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#446]
We need to make sure that charities know that a person they are adding to manage their page has a personal profile on Gooddler.
I suggest that we add the following to the message that shows when scroll over "?"  next to the Access List:

Note: This person should have a personal account on Gooddler. To sign up go to....

or something like that.

Plus, we only allow for username and email to add, so it would be a good idea to replace the word "name" with "username" in the message.

It reads now: Enter name or email of the person who will receive all rights to manage support and edit a page of this donee.
Should read: Enter username......

![screenshot 43](https://cloud.githubusercontent.com/assets/7177944/7619926/e1fe3742-f970-11e4-898c-6e88c7d6a47e.png)

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
@galinafed 
_Should read: Enter username......_
Не согласен - зачем нам несколько раз повторять Enter Username? Эта фраза уже написана у нас возле поля ввода Username.

**Comment by Fetati** [comment]
@DmitrysIF Подсказка должна отражать суть происходящего, а не запутывать. Name и Username это совершенно разные вещи. Если человек введет Name, то он не сможет добавить еще одного юзера.  К примеру в моем случае Name - Tatiana Fedorova, а Username - Fetati. В подсказке должно быть Enter username...

**Comment by DmitrysIF** [comment]
@Fetati А, всё понял. Я не сразу понял, что имеется в виду только исправление в тексте Enter Name на Enter Username. Мои извинения. :)

**Comment by DmitrysIF** [comment]
![image](https://cloud.githubusercontent.com/assets/7186861/7771333/3073f754-00c9-11e5-86b8-63aefd51fa08.png)
Вот как это сейчас выглядит. (еще не в продакшене)

**Comment by DmitrysIF** [comment]
Check it, please.

**Comment by galinafed** [comment]
I would switch places. First goes our main message and then Note.
My suggestion on Note:
Note: This person should have a personal account on Gooddler. Sign up HERE
or..... Click HERE to sign up

**Comment by DmitrysIF** [comment]
@Fetati Какие будут у тебя мысли по предложению Гали?

**Comment by Fetati** [comment]
Согласна с Галей.

**Comment by DmitrysIF** [comment]
Fixed
