### ISSUE TITLE
International Phone Number issues at Charity Page

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#448]
Our phone number field works for US numbers only.
I can't add Nepal phone number +977-9803023528. If I add this number, it looks like that: 
![screen shot 2015-05-19 at 1 58 54 pm](https://cloud.githubusercontent.com/assets/4335901/7713849/47d7a9fa-fe2f-11e4-984e-227cfc954eda.png)

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
Принято - изменю шаблон.

**Comment by DmitrysIF** [comment]
Вопрос - нужна поддержка обоих шаблонов?

**Comment by DmitrysIF** [comment]
Или же вообще убрать какой-либо шаблон, просто оставить рекомендации по заполнению поля с номером телефона?

**Comment by Fetati** [comment]
да, рекомендаций достаточно, думаю.

**Comment by DmitrysIF** [comment]
@Fetati, @galinafed - check it, please!

**Comment by Fetati** [comment]
Great! Thank you!
