### ISSUE TITLE
Post: На главной странице новый пост криво выглядит

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#45]
На главной странице мой новый пост (самый первый слева) криво выглядит - не видно текст поста и заголовок, а также не возможно кликнуть на read more

![screen shot 2014-04-09 at 10 02 21 am](https://cloud.githubusercontent.com/assets/4335901/2658477/ffd00b9e-c008-11e3-9ed6-1c2a9d8e7d21.png)

**Comment by DmitrysIF** [comment]
Fixed.

**Comment by DmitrysIF** [comment]
Вопрос следующий - обязателен ли показ заголовка поста? Как быть, если длина заголовка поста очень большая?

**Comment by Fetati** [comment]
Сейчас в заголовок поста на главную страницу попадает не заголовок реально, а кусок текста. А заголовка поста нет вообще.
Вот к примеру пост:
![screen shot 2014-04-11 at 10 08 01 am](https://cloud.githubusercontent.com/assets/4335901/2682499/ed033006-c19b-11e3-994e-fd5a226eb121.png)

Вот, что видно на главной странице (это кусок текста, а не заголовок)
![screen shot 2014-04-11 at 10 08 12 am](https://cloud.githubusercontent.com/assets/4335901/2682507/06015ff6-c19c-11e3-9e21-50ddb221b11c.png)

Длину заголовка на главной странице можно ограничить в 70-75 знаков, а дальше read more..

**Comment by DmitrysIF** [comment]
Fixed
