### ISSUE TITLE
Hide Donor information from posts

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#450]
Hide the name of donors from posts (for all users, except super administrators)
![screen shot 2015-05-19 at 3 56 28 pm](https://cloud.githubusercontent.com/assets/4335901/7715764/c6cd048e-fe3f-11e4-8363-38c5affff9cc.png)

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
Принято.

**Comment by DmitrysIF** [comment]
Изменения в исходники внесены. Проверить можно будет после очередного деплоя в продакшен.

**Comment by DmitrysIF** [comment]
![image](https://cloud.githubusercontent.com/assets/7186861/7771304/fbe08692-00c8-11e5-98ed-39fa94eb306e.png)
Вот как это выглядит сейчас (еще не задеплоено).

**Comment by DmitrysIF** [comment]
Check it, please

**Comment by Fetati** [comment]
Great! Thank you!
