### ISSUE TITLE
Main Page post: click at blog post and go to strange place

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#451]
1. I signed in, 
2. From main page http://gooddler.com/ I clicked to blog post (May 7, 2015 Art therapy for children going through life transitions)
   ![screen shot 2015-05-19 at 4 03 42 pm](https://cloud.githubusercontent.com/assets/4335901/7715832/bc2302bc-fe40-11e4-8810-45873bf6c3c5.png)
   Result: I went to http://gooddler.com/Blog/Post/70190 - see error and that i don't singed in

![screen shot 2015-05-19 at 4 03 56 pm](https://cloud.githubusercontent.com/assets/4335901/7715865/2d6ca4f0-fe41-11e4-81ed-bd6c420beeb3.png)

When I click to the logo, I signed in again.

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
Принято.

**Comment by DmitrysIF** [comment]
Проблема локализована. Исправляется.

**Comment by DmitrysIF** [comment]
Исправлено. Будет применено в следующем обновлении сервиса.

**Comment by DmitrysIF** [comment]
Please - check it.

**Comment by Fetati** [comment]
Thanks!
