### ISSUE TITLE
Order of goods in a wish list: to move goods up and down very unintuitive and inconvenient

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#454]
Сейчас при перемещении товара, кликая на стрелочку, надо мышку перетаскивать за товаром. Если не перемещать, то под курсором оказывается следующий товар. Должно быть, чтобы лист двигался под курсором, не двигая его (страница прокручивалась) - чтобы можно было сделать несколько кликов быстро, если передвигаешь на несколько позиций.
Сейчас надо быть в фокусе, и помнить, какой товар перемещаешь.

**Comment by DmitrysIF** [comment]
Fixed
