### ISSUE TITLE
Web wishlist: impossible add more items

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#456]
Click Donate, и когда появилась added, невозможно добавить еще этот же товар.

**Comment by DmitrysIF** [comment]
Можно сделать задержку в несколько секунд при показе added, потом возвращать обратно Donate. Как такой вариант?

**Comment by Fetati** [comment]
Давай. 1-2 сек, не больше.

**Comment by DmitrysIF** [comment]
Хорошо. По возможности - я сразу реализую это.

**Comment by DmitrysIF** [comment]
Сделано, проверьте, пожалуйста.

**Comment by DmitrysIF** [comment]
Не забудьте почистить историю, чтобы загрузились обновлённые скрипты сайта в браузер.

**Comment by DmitrysIF** [comment]
Closed
