### ISSUE TITLE
Post: Битая ссылка заголовка поста.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#46]
Битая ссылка заголовка поста. При нажатии на название поста, выдается ошибка: http://gooddler.cloudapp.net/Admin/Posts?doneeid=10017
![screen shot 2014-04-09 at 1 54 21 pm](https://cloud.githubusercontent.com/assets/4335901/2661199/f20ce114-c029-11e3-95b0-bcb99665040c.png)

**Comment by DmitrysIF** [comment]
Поправлено - ожидать в следующем обновлении.
