### ISSUE TITLE
Thank you letter: Address line is not correct

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#461]
Thank you letter: Address line is not correct - "stub stub stub"

![screen shot 2015-06-24 at 7 02 00 pm](https://cloud.githubusercontent.com/assets/4335901/8345548/791aa926-1aa5-11e5-92ff-6be391234929.png)

**Comment by DmitrysIF** [comment]
Как повторить эту ошибку?

**Comment by DmitrysIF** [comment]
Нашёл возможную причину, изучаю.
В каком случае появляется этот "адрес"? Это поможет сузить круг поисков.

**Comment by DmitrysIF** [comment]
Я полагаю, что это какой-то сторонний инструмент? Запускается отдельно от нашего сайта, но использует базы данных нашего сайта?

**Comment by DmitrysIF** [comment]
Ошибка локализована. Исправляем.

**Comment by DmitrysIF** [comment]
@Fetati, какой адрес там у нас должен показываться для письма Checkout? Primary адрес дони?

**Comment by DmitrysIF** [comment]
Исправлено.
