### ISSUE TITLE
Main Page: delete or edit the frame

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#463]
При подведении мыши к вишлисту на главной странице появляется рамка. Она в большинстве случаев проходит прям посередине названия чарити. И кусок ее заходит на соседний вишлист. Давайте ее удалим совсем.
![screen shot 2015-06-29 at 2 55 52 pm](https://cloud.githubusercontent.com/assets/4335901/8419525/38dd4968-1e6f-11e5-8271-93b2f50dd1ce.png)

**Comment by DmitrysIF** [comment]
Please, check it.

**Comment by Fetati** [comment]
Yes! Thank you!
