### ISSUE TITLE
Post: Как добавить пост к юзеру?

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#47]
![profile_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2661273/058a1e9a-c02b-11e3-93ae-16abc290f65b.png)

**Comment by DmitrysIF** [comment]
Найти список донейшенов в своей админке, нажать кнопку "+пост" возле нужного пожертвования. Созданный пост будет адресован пользователю, который сделал выбранное нами пожертвование.
Я решил, что так будет целесообразнее - пост о пользователе можно сделать только тогда, когда он сделал что-то для дони. Так же можно создать посты, которые адресуются вишлисту или дони.

**Comment by Fetati** [comment]
Пока не понимаю, как это будет работать. Чуть позже вернемся к этому вопросу.

**Comment by DmitrysIF** [comment]
Добавил в профиль ссылку "написать пост об этом человеке"
