### ISSUE TITLE
Investigate a performance problem: Main page: All Wishlist and All Blogs buttons

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#478]
При нажатии на кнопок  All Wishlist and All Blogs с главной страницы, реакция довольно длинная. Все остальные линки работают нормально, но эти 2 кнопки приходится ждать до 8 секунд.

MacBookPro, Chrome
iPhone5, Safari

**Comment by DmitrysIF** [comment]
Здесь нужна будет оптимизация, работа достаточно объёмная. Вернёмся к ней после релиза конструкторов.
