### ISSUE TITLE
Mobile: TO CART button disappears after click on it.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#479]
Кнопка TO CART исчезает после нажатия в мобильных версиях Apple devices. 
Протестированы:
iPhone5 (iOS 9.0.2), Chrome and Safari 
iPad (old version of iOS - 8.4.1), Chrome and Safari

Ошибка замечена после того, как донор сделал 3 одинаковых транзакции в течении 3 минут.

**Comment by DmitrysIF** [comment]
@Fetati перепроверьте, пожалуйста, актуальность этой темы.
