### ISSUE TITLE
CharityConstructor: Слетает процесс

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#481]
Second Card - После внесения адреса и нажатия кнопки Save and Next, все слетело:

![screen shot 2015-11-05 at 10 36 32 am](https://cloud.githubusercontent.com/assets/4335901/10978005/6cc8bf10-83a9-11e5-86b2-d087c6e538cd.png)

После возвращения на предыдущую страницу, адрес не сохранился, но при занесении по второму разу адреса, ошибка не повторилась.

**Comment by Fetati** [comment]
Ошибка повторилась на карте 5.
![screen shot 2015-11-05 at 10 50 02 am](https://cloud.githubusercontent.com/assets/4335901/10978315/1a4f6390-83ab-11e5-8ac0-421a7d03a574.png)

Но при возвращения назад все внесенные данные сохранились, что хорошо.
![screen shot 2015-11-05 at 10 51 33 am](https://cloud.githubusercontent.com/assets/4335901/10978346/475dc8ae-83ab-11e5-9a25-9e6af541f3c9.png)

К сожалению на этом процесс прервался. Не могу идти дальше. Нажатие всех кнопок Save and Go Back,  Save and Next и Exit with save дают одинаковый результат - ошибку. Дальше процесс не идет.

**Comment by DmitrysIF** [comment]
Ага, отлично! Я проверю!

**Comment by DmitrysIF** [comment]
@Fetati Попробуй в последнем шаге удалить необязательные поля по очереди. Скорее всего какое-то поле ломает всё. Будет проще, если будет известно - какое именно поле. :)

**Comment by DmitrysIF** [comment]
По первому багу - это ошибка в шаблоне страницы, когда он пытается вывести ошибку, которая пришла от сервера при валидации адреса. Правлю.

**Comment by DmitrysIF** [comment]
Ошибки исправлены, сейчас залью новую версию

**Comment by DmitrysIF** [comment]
@Fetati новая версия загружена! Можно продолжать работу.
