### ISSUE TITLE
SFSPCA recommendations

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#489]
1)  Web: put the text under the “Wishlists of San Francisco SPCA”:  “Pick an SF SPCA program to buy gifts for. Your gifts will be sent to animals in need.”
Add the title and description in mobile version: 
Title: Wishlists of San Francisco SPCA 
Smaller fonts: Choose a program to buy gifts for animals. Items will be delivered to help animals in need!

2) Switch page’s url (http://gooddler.com/Wishlists?doneeid=4) and the other url (http://sfspca.gooddler.com/). 

URL (http://sfspca.gooddler.com/) - should link to http://gooddler.com/Wishlists?doneeid=4

SFSPCA: "At some future time, I’d love for this page to be embedded into our sfspca.com website."

**Comment by galinafed** [comment]
1. Change "Tax Deduction" on all lists to "Tax Deductible". This message shows up on main page of mobile version.
