### ISSUE TITLE
Create Account problem: warning message that the information was going through an unencrypted site 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#496]
From HSTT donor: 
"Just wanted to let you know that I placed an order via Amazon.com for a number of the items you had listed on Steve’s Wish List for dogs.  I used Amazon because when I went to create an account in Gooddler I received a warning message that the information was going through an unencrypted site and others might be able to view logon details (yikes!).  Anyway, they have the same items on Amazon."

**Comment by DeveloperRegistry** [comment]
The warning is specific to the browser. It is highly unlikely that anybody would intercept Login and Password information. Yet, it is a good practice to force users to use HTTPS (secure) protocol to access SIGN IN and SIGN UP pages.

Resolution: forced HTTPS protocol for /SignIn and /SignUp pages by changing NGINX configuration on two front end servers. Tested the changes.
