### ISSUE TITLE
Wishlist bug: can't move goods down

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#497]
Невозможно передвинуть заполненные товары вниз страницы: http://www.gooddler.com/Wishlist/10039

**Comment by DmitrysIF** [comment]
Какой товар не получается передвинуть вниз?

**Comment by Fetati** [comment]
Там 2 товара, которые completed, и которые посередине листа. Надо их сдвинуть в низ, где все купленные товары, чтобы они не разрывали некупленный лист.
Начало названий:  Leegoal Cute Soft Sponge и OurPets Play-N-Squeak at Night ...

**Comment by DmitrysIF** [comment]
Хм, думаю надо добавить новый issue - "Сдвигать завершённые товары в конец"

**Comment by Fetati** [comment]
Сейчас достаточно, что вручную отодвигается, когда не ломается. 
Надо исправить этот конкретный случай. В остальных листах пока все работает.

Такую функцию надо будет добавить, но только после того, как будет ERP. Сейчас мы отодвигаем доставленные товары. Если сейчас будет автоматически, то будет путаница, что доставлено, а что нет. 

В issue #498 указано, как хорошо бы сделать передвижение товаров.

**Comment by DmitrysIF** [comment]
_Начало названий: Leegoal Cute Soft Sponge и OurPets Play-N-Squeak at Night ..._
Хорошо, сейчас проверю - что не так. По логам сообщается, что генерируется какая-то ошибка при передвижении элемента по списку.

**Comment by DmitrysIF** [comment]
@Fetati починил! :)
