### ISSUE TITLE
Wishlists: Make moving goods easier

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#498]
Прокрутка товаров вниз-вверх очень неудобно реализована.
1) в режиме edit должно быть видно сколько товаров куплено (поле Done, как в режиме просмотра листа) 
2) передвигаться товар должен перетаскиванием, или стрелками. Но в случае стрелок, курсор мыши должен быть прилеплен к товару. Сейчас товар "уходит" из под курсора.

**Comment by DmitrysIF** [comment]
Это будет реализовано в WishlistConstructor.

**Comment by DmitrysIF** [comment]
Added
