### ISSUE TITLE
Тексты для тултипов. Их нет. Они нужны

### ISSUE THREAD

**Issue by RealBerd** [Goodler/code#5]
http://i.imgur.com/CLxHrdw.jpg

Все тултипы на "вопросики" сейчас не заполнены.

Тултипы есть на формах создания и редактирования Донии, Вишлиста и Поста

**Comment by Fetati** [comment]
Текстами занимается Галя.

**Comment by Fetati** [comment]
см. Issue - Texts: Create Donee page - To change fields 
Там описано создание Donee, поля адреса и пр.

**Comment by galinafed** [comment]
anything else on this one?

**Comment by DmitrysIF** [comment]
Думаю, пустых тултипов больше нет
