### ISSUE TITLE
"Do" icon is cut on the last item on the list

### ISSUE THREAD

**Issue by ghost** [Goodler/code#50]
Steps:
tap an arrow that allows you to slide projects and observe the last "Do" icon

Bug: Cut (but tappable:)
![do cut](https://cloud.githubusercontent.com/assets/7193843/2663750/1ae6f078-c063-11e3-8f48-d088001f03cd.png)

**Comment by DmitrysIF** [comment]
Разрешение экрана какое?

**Comment by ghost** [comment]
Thank you
