### ISSUE TITLE
Edit Donee constuctor: Apply changes button 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#508]
Надо придумать не прогонять юзера через все шаги во время редактирования Чарити. 
Может сделать возможность кликать на нужный Step, и предлагать Apply changes?

**Comment by DmitrysIF** [comment]
В какой момент он должен иметь возможность кликать на нужный шаг? И в какой момент должна появляться кнопка Apply Changes?

**Comment by galinafed** [comment]
Step by step option should only be available when someone is  creating a new donee. When editing an existing donee, an admin should be able to click on any of the 7 steps we offer, without starting at step 1

**Comment by Fetati** [comment]
Кнопка Apply Changes должна появляться на каждом этапе, где вносятся изменения. 
Цель, не прогонять людей через все шаги. Иногда надо просто поставить запятую в описании, а приходится проходить через все шаги

**Comment by DmitrysIF** [comment]
Это возможно реализовать. Было бы здорово получить дизайны с этой кнопкой, это самое важное. Именно в двух вариантах - как будет выглядеть на мобильном телефоне и на настольном пк.

**Comment by DmitrysIF** [comment]
Fixed
