### ISSUE TITLE
Wording on  "privacy notice" and "conditions of use" needs to be corrected 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#51]
Steps
Do not sign in
tap any project and add items and check out
tap the links at the very bottom  "privacy notice" and "conditions of use"

Improvement
separate words
move word a lit bit right so its not all the way to the border of the screen
could we add some text (a lot:) so i can tst scroll option
![wording](https://cloud.githubusercontent.com/assets/7193843/2663833/65dc77da-c066-11e3-8124-dbff0195e584.png)

.

**Comment by DmitrysIF** [comment]
Как будет готов текст для этой страницы - приведем в порядок. Сейчас тут стоит заглушка - пустой шаблон.

**Comment by Fetati** [comment]
Дима, Никита, тексты были высланы на почту дней пять назад. Могу продублировть, если не получили.

**Comment by DmitrysIF** [comment]
Тексты получил (12-го числа). Верстка будет через несколько обновлений.

**Comment by DmitrysIF** [comment]
Выполнено.

**Comment by DmitrysIF** [comment]
Нет текстов для Privace Notice

**Comment by Fetati** [comment]
Сделаем. Пришлю в почту.

**Comment by DmitrysIF** [comment]
Таск завершен.
