### ISSUE TITLE
Charity Constructor: Edit step 7 - Photo gallery

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#513]
Карточка 7 не открывается в режиме Edit http://gooddler.com/Charity/Constructor/s6

Заходила из http://gooddler.com/Admin/Donees
Работает нормально, если заходить со страницы чарити

**Comment by DmitrysIF** [comment]
На первый взгляд всё работает. Ошибка повторяется? Какой именно проект пытаемся продолжить редактировать?
