### ISSUE TITLE
Charity Page: Completed Wishlist

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#516]
Надо перемещать закрытые вишлисты в конец списка вишлистов у каждого чарити. 
Возможно, что лучше сделать отдельную рубрику для них на той же странице ниже: Completed Wishlists (или что-то типа). 
И сделать возможность прятать листы, если люди не хотят их видеть в списке своих вишлистов.

(по мотивам работы с SFSPCA)

**Comment by DmitrysIF** [comment]
Предлагаю остановиться на рублике "Завершённые", это быстро и просто реализовать.

**Comment by Fetati** [comment]
отлично
