### ISSUE TITLE
Wishlist: changing the order of goods - new items put in the first line

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#517]
SFSPCA: "All new Amazon URL items are added at the bottom of the list and there is no way to quickly change order, so if I add something new and want it at the top, I have to click the up arrow 30 times to get it there and sometimes the AJAX coding stops responding so I have to wait or possibly reload the page and start over."

1) надо сделать добавление товаров в начало списка!
2) сделать возможность перетаскивания товаров

**Comment by DmitrysIF** [comment]
оба пункта реализованы в полном объёме
