### ISSUE TITLE
New charity/wishlist: Create wishlist

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#523]
когда дохожу до конца создания вишлиста, и жму последнюю стрелку вниз, все верхние поля выдают ошибку, как будто они не заполнены. При нажатии на Edit - вся информация на месте:

![screen shot 2016-04-16 at 8 23 08 pm](https://cloud.githubusercontent.com/assets/4335901/14584865/ce742e00-0411-11e6-88cc-126befc1515b.png)

![screen shot 2016-04-15 at 8 50 17 pm](https://cloud.githubusercontent.com/assets/4335901/14584868/e0a1abb6-0411-11e6-999c-8cef6e817bb2.png)

**Comment by DmitrysIF** [comment]
Принято.

**Comment by DmitrysIF** [comment]
Был сделан деплой. Проверьте актуальность этого бага.
