### ISSUE TITLE
Edit Charity: the information disappears

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#524]
Во время редактирования чарити исчезает информация в первых карточках. 
Ошибка произошла после того, как я прошлась по шагам, ничего не меняя. Нажала на Х - Save and Exit, и появился вот такой экран:

![screen shot 2016-04-26 at 8 08 36 pm](https://cloud.githubusercontent.com/assets/4335901/14840681/4a1b8400-0beb-11e6-9855-38dadb9d8a0b.png)

После нажатия Edit, все оказалось на месте:

![screen shot 2016-04-26 at 8 08 59 pm](https://cloud.githubusercontent.com/assets/4335901/14840702/76743312-0beb-11e6-87b5-85a12a618782.png)

Повторно нажимаю Save and Exit, и все в порядке.

**Comment by DmitrysIF** [comment]
Fixed
