### ISSUE TITLE
Shipping address message

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#525]
Please, change accuracy notice to:
Accuracy: Make sure you get your stuff! If the address is not entered correctly, your package may be returned as undeliverable. Save time and avoid frustration by entering the address information in the appropriate boxes and double-checking for typos and other errors. Need Help? info@gooddler.com
I removed a sentence about ordering again and corrected one small typo.

![screenshot 2](https://cloud.githubusercontent.com/assets/7177944/14970196/ecdb0280-107b-11e6-96f0-6a2aaf466ddb.png)

**Comment by DmitrysIF** [comment]
Данная надпись в WishlistConstructor StepThree "Goods" исправлена. Изменения в продакшене.
