### ISSUE TITLE
Edit wishlist

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#526]
Edit wishlist button takes me to our new constructor: Step 1.
We had pretty good set up before it should take directly to the list: Step 3 
Can we just use the same set up we had before? This way is way too confusing

**Comment by Fetati** [comment]
1) Я думаю, что надо убрать слова Step 1,2,3,etc в редакторе вишлистов. Steps имеют смысл только при создании листа. При редактировании другая логика.
2) после нажатия на Edit Wishlist должно вести на /s3 - например, http://gooddler.com/Wishlist/Constructor/s3
3) на карточке 3 надо сделать кнопку Update Wishlist снизу карточки, нажатие на которую возвращает на страницу вишлиста. 
4) Перенести вверх карточки Add New Goods. Или просто добавить такое же поле вверх карточки.
5) В поле внесения товара, должно быть слово Quantity вместо Count
6) поле добавленных товаров должно быть такое же, как в старом редакторе - все поля должны быть видны. Сейчас стало ужасно неудобно. Надо вот так:
![screen shot 2016-05-02 at 6 26 09 pm](https://cloud.githubusercontent.com/assets/4335901/14972700/81a1e836-1093-11e6-8089-b3ae3197820d.png)

7) в самом конце редактора вишлиста вставить кнопки, как в старом редакторе
![screen shot 2016-05-02 at 6 30 34 pm](https://cloud.githubusercontent.com/assets/4335901/14972734/1250ba56-1094-11e6-92d7-bbfb759bd40f.png)

**Comment by DmitrysIF** [comment]
Давайте соберём побольше замечаний, а потом обсудим все пункты на встрече во вторник, согласны?

**Comment by DeveloperRegistry** [comment]
Mozhno v sredu?
Date: Mon, 2 May 2016 22:55:43 -0700

**Comment by DmitrysIF** [comment]
Fixed
