### ISSUE TITLE
Create Donee: Step 5 Contact Address. Change Website Validation 

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#529]
Presently, entering the website with HTTP://  causes the validation to fail. Example: http://www.sspca.org

We need to change the validation to allow both types of website information: http://www.sspca.org  and www.sspca.org. Data can be normalized before saving into the database.

The present validation is annoying to users as most people will copy the URL from the browser. It contains HTTP://

**Comment by DeveloperRegistry** [comment]
Dima please take a look.

**Comment by DmitrysIF** [comment]
Хорошо, проверю.

**Comment by DmitrysIF** [comment]
Fixed and deployed.
