### ISSUE TITLE
Check out flow: revise the payment info ; use icons instead of words

### ISSUE THREAD

**Issue by ghost** [Goodler/code#53]
![credit](https://cloud.githubusercontent.com/assets/7193843/2664020/0c8661c2-c06c-11e3-81d3-c644d9968983.png)
![credit cards](https://cloud.githubusercontent.com/assets/7193843/2664019/0c690ad2-c06c-11e3-8817-c8e3320c7581.png)

**Comment by DmitrysIF** [comment]
Иконки платежных систем должны быть статичными и находиться неким списком над формой ввода данных кредитной карты?

**Comment by Fetati** [comment]
Да, мне кажется, что именно так. 

Тамара, что думаешь?

**Comment by ghost** [comment]
Totally agree. icons are static, but we have to make sure that we recognize the payment type once it is entered into a field, e.g Visa will have only 3 digit security code, where AmEx is 4 and we plan PayPall can be different flow.
Do we give the option to have multiple cards?

**Comment by DmitrysIF** [comment]
Do we give the option to have multiple cards?
Сейчас нет.

**Comment by DmitrysIF** [comment]
Картинки card-services вставлены.

**Comment by ghost** [comment]
@Fetati are those the only payments types you will use?
