### ISSUE TITLE
New charity/wishlist: Edit wishlist 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#530]
1) Увеличить размер шрифта Update Wishlist до 22-24px (должен быть точно такой же размер, как Add New Goods)
2) Уменьшить размер шрифта Delete Wishlist до 14px
3) Поменять местами Update Wishlist и Delete Wishlist кнопки. 
4) Кнопка Update должна быть ближе к центру. 
5) Кнопку Delete Wishlist сделать 50% прозрачности
6) Update Wishlist сделать жирным
7) убрать опечатку в Delete Wishllist (два L в слове Wishlist)

**Comment by DmitrysIF** [comment]
Сделано.
