### ISSUE TITLE
Change About Us page

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#537]
Поменять первый абзац в About Us http://gooddler.com/About на вот этот текст:

GOODdler is an enterprise software for public and private organizations working on aid, sustainability and development to collect and manage goods donations. It digitizes supply chains of local retailers and farmers, enabling local NGOs to create wishlists utilizing their inventory and providing international communities with an easy way to contribute by purchasing requested goods directly from local retailers. It minimizes challenges of unsolicited bilateral donations by giving organizations tools to accept goods donations from supporters on the terms that support, not overwhelm the recipient.

GOODdler strengthens communications in humanitarian emergencies by connecting NGOs and affected communities with supporters around the world in a way that collective action leads to collective intelligence. Local actors become first responders to humanitarian crisis.

<img width="1356" alt="screen shot 2017-06-01 at 9 47 00 pm" src="https://cloud.githubusercontent.com/assets/4335901/26711438/1ec48ea8-4715-11e7-968f-06ca5bab9bf6.png">

**Comment by DmitrysIF** [comment]
Text changed; see http://gooddler-stg.cloudapp.net/About
