### ISSUE TITLE
"Review your order" will have more user friendly look if all info will be more stretched across the page instead of column 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#54]
Tanusha its up to you , but the reason it will be better to have it stretched, because user can see more of the info without scrolling   ![review your order](https://cloud.githubusercontent.com/assets/7193843/2664032/8334e820-c06c-11e3-9cda-2434a3fef200.png)

**Comment by Fetati** [comment]
Согласна

**Comment by DmitrysIF** [comment]
Вы имеете в виду растянуть список "Total order" до состояния таблицы?

**Comment by ghost** [comment]
I want to say everything should be placed in wider range
Row one: Total, description of item, price, total
Row two; payments details with all credit card icons
row three: payments details and its ok to make it in row, like First name last name and etc.

its just 50% of page is unused

**Comment by DmitrysIF** [comment]
Я бы предложил это перенести на Release 2.
То что есть - вполне можно использовать.

**Comment by DmitrysIF** [comment]
расширил таблицу, добавил данных.
