### ISSUE TITLE
Initial Login while going to Checkout fails

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#540]
To reproduce:

1) Make sure you are not Signed In
2) Add one item to Cart
3) Click on Check Out
4) Enter Credentials
5) Upon Successful Login the Application fails  (error on the server)

**Comment by DmitrysIF** [comment]
Сделал, это проблема у нас была всегда, как оказалось. Эта проблема не относится к нашему обновлению, то есть, не из-за него возникла. Исправил конкретно для чекаута.
