### ISSUE TITLE
Unable to sign in to test site from my iPhone

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#542]
When i opened our test site http://gooddler-stg.cloudapp.net/ it had Anton's account. I logged out and tried to sign in under my name and password. The page doesn't open it sends me back to log in page, no error message. (i use correct user name and password). I also tried to open up the page by not copying the link, but typing it, same results.

**Comment by DmitrysIF** [comment]
Попробовал сымитировать айфон с помощью инструментов гуглхрома - да, проблема есть такая, проблема со входом в мобильной версии. Попробую починить.

**Comment by DmitrysIF** [comment]
Ребус, связанный с логином, решён - ничего фатального. Это всё из-за того, что релизная конфигурация сайта находится не на gooddler.com (есть жёсткая привязка к этому домену);

Я вернул на стейджинг тестовую базу данных
