### ISSUE TITLE
Wishlist: adding goods - error

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#544]
Пытаюсь добавить товары в вишлист. 
Сначала слишком медленно загружались Item Options, и при перелистывании страниц поиска товаров, следующая страница грузилась довольно долго.

Потом, когда я дошла до конца, и заполнила все, опубликовала лист, получиал ошибку:
<img width="1438" alt="screen shot 2017-06-08 at 7 02 19 pm" src="https://user-images.githubusercontent.com/4335901/26957999-353e0cfa-4c7d-11e7-9fd1-0442916da789.png">

Но при заходе на главную страницу, лист опубликовался.

**Comment by DmitrysIF** [comment]
Оу, надо перепроверить.

**Comment by DmitrysIF** [comment]
@Fetati  Не могу повторить ошибку. Пожалуйста, опишите все изменения, которые были внесены в вишлист.

**Comment by DmitrysIF** [comment]
@Fetati Попробуйте ещё раз вызвать эту ошибку.

**Comment by Fetati** [comment]
Занесла новый вишлист, прошлась по всем шагам с первого по последний. После нажатия Save & Exit выкидывает на ошибку. 
Ошибка повторяется. Работаю в Chrome, на Mac Book Pro, веб версия gooddler. 

<img width="1256" alt="screen shot 2017-06-09 at 2 19 19 pm" src="https://user-images.githubusercontent.com/4335901/26994935-f3c068de-4d1e-11e7-90e2-acfa86c4c8c7.png">
<img width="1234" alt="screen shot 2017-06-09 at 2 19 33 pm" src="https://user-images.githubusercontent.com/4335901/26994939-f7537b62-4d1e-11e7-850b-578e27e4a1c8.png">


Причем, заходя на главную страницу, вижу, что вишлист опубликован правильно.
http://gooddler-stg.cloudapp.net/Wishlist/70148 - New needs for Gooddler School

<img width="1249" alt="screen shot 2017-06-09 at 2 22 55 pm" src="https://user-images.githubusercontent.com/4335901/26994984-31b4263a-4d1f-11e7-8911-ca9e0df4244f.png">

**Comment by DmitrysIF** [comment]
Можете описать последовательность действий, чтобы я смог у себя такую же ошибку вызвать? Я никак не смог её вызвать у себя. Может вы какие-то особенные данные вносите? Или какие-то поля оставляете пустыми?

**Comment by DmitrysIF** [comment]
Я нашёл и решил проблему. Было очень сложно её поймать - ушёл весь день.
