### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#546]
I created a wishlist for SFSPCA but when i clicked on Save and Exit it showed error message and logged me out. http://gooddler-stg.cloudapp.net/Donee/10017

![screen shot 2017-06-08 at 7 39 20 pm](https://user-images.githubusercontent.com/7177944/26958956-571247d8-4c82-11e7-9bb2-b7c90d557273.png)
![screen shot 2017-06-08 at 7 39 43 pm](https://user-images.githubusercontent.com/7177944/26958960-5d1812d4-4c82-11e7-837e-309b1f543adf.png)

**Comment by DmitrysIF** [comment]
Я проверю

**Comment by DmitrysIF** [comment]
@galinafed Были ли в листе товары, которые не имели описания?

**Comment by DmitrysIF** [comment]
@galinafed  Я загрузил ваш драфт под своим аккаунтом и обнаружил, что там действительно есть товары без описания. Я исправлю ошибку, которая возникает при попытке добавить товары без описания.

**Comment by DmitrysIF** [comment]
@galinafed Исправлено

**Comment by galinafed** [comment]
I tried to create another list and getting a similar message
![screenshot 74](https://user-images.githubusercontent.com/7177944/26995360-128128ba-4d21-11e7-98e4-d12daff09506.png)

But in this case i am unable to go back at all. Pretty much i am out of gooddler site

**Comment by DmitrysIF** [comment]
Нет, это уже другая ошибка.  Писать сюда:
https://github.com/Goodler/code/issues/544
