### ISSUE TITLE
UX: "Done" btn is never at the top (sign up flow)

### ISSUE THREAD

**Issue by ghost** [Goodler/code#55]
![done is never at the top](https://cloud.githubusercontent.com/assets/7193843/2673848/50e415ee-c0f8-11e3-9d68-565856c08191.png)
steps:
Sing up for new account
after user is done s/he redirected to a profile page

Improvement: "Done" btn is never at the top of the page (just UX recommendation)

**Comment by DmitrysIF** [comment]
По началу там кнопки не было вообще - были требования установить ее для впервые зарегистрившихся, чтобы не вынуждать их крутить страницу вниз за кнопкой, если они не планируют сейчас заполнять профиль.

**Comment by ghost** [comment]
Dima, need your input on that. Can we remove DONE at the top? Move First and Last name in one row? Bring About higher? put Location. FB.TW and IN fields in two rows and two column? Place Photo fields under the Profile Picture square ( or kind like FB does having a photo icon (camera icon)  inside the area and once user clicks it has the option to choose the photo.) I would also reconsider the "?" marks if we make two columns, and if we have it then i would love to see them to be open without overlapping any area . Would all that fit? ARE there any other options for About field? becasue things like UNDO is mostly used with shortcuts nowdays if we move that away, remove formats because it seems to duplicate Formats above, and maybe (if Possible i know i am going crazy here with all I want ....:) bear with me guys) but maybe we can have about area that is small but once you click it, it will open wider screen.

**Comment by DmitrysIF** [comment]
Сделать можно все  - вопрос только в том, сколько на это уйдет времени и труда.

**Comment by ghost** [comment]
Sure. :))

**Comment by DmitrysIF** [comment]
Хочу ознакомиться с "хотелками" последней версии по этой странице.

**Comment by ghost** [comment]
1. Remove DOne at the top
2. Move First and Last name in one row - No ? marks needed - simple flow
3. About - bring it higher
4. The field Above can be much smaller and once user there expand- if not possible leave it
5. Put Location. FB.TW and IN fields in two rows and two column - Do not user the "?" for those fields- maybe have some text on side with sample or explanation. Let me know if you need text
6. Photo - move under the picture
7. Done btn

**Comment by ghost** [comment]
But i would ask Tania as well, i am just trying to make it user friendly with min scrolls, clicks, overlaps @Fetati you call

**Comment by DmitrysIF** [comment]
@TShket мне необходим текст примера для полей социальных сетей и приблизительное расположение на странице. Желательно скриншотом.

**Comment by ghost** [comment]
@DmitrysIF @Fetati  I would skip  info for Social fields for now. it is very obvious what needs to be added and very hard to explain in short sentence where to find link to FB, TW and etc.  
if we would like to add info about how to get link for FB then it should be a new screen with steps and  pictures.
@Fetati  you call Tanusha

**Comment by ghost** [comment]
the only thing that comes to my mind is to make a very light gray text inside the FB, TW, IN field with words
e.g. https://www.facebook.com/Vasia.Pugovkin
e.g. https://www.linkedin.com/profile/view?id=54524169&trk=spm_pic  (for linked In)
e.g. https://twitter.com/Smulean

as an hint for users
