### ISSUE TITLE
Error: Create New Wishlist for a new members

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#550]
Я попыталась смоделировать поведение новых юзеров. Вот по шагам:

1) зашла на How It Works и нажала Create New Wishlist:
<img width="1120" alt="screen shot 2017-06-21 at 12 10 07 pm" src="https://user-images.githubusercontent.com/4335901/27402258-eaf212ba-567a-11e7-8d08-1696cce26412.png">

2) Мне система предложила залогиниться
<img width="1199" alt="screen shot 2017-06-21 at 12 10 33 pm" src="https://user-images.githubusercontent.com/4335901/27402286-04dd1be8-567b-11e7-9541-515ecf57926f.png">

3) Я нажала log in и получила ошибку:
<img width="1127" alt="screen shot 2017-06-21 at 12 10 44 pm" src="https://user-images.githubusercontent.com/4335901/27402309-1de44e9a-567b-11e7-8b15-09cf78e07d74.png">

**Comment by DmitrysIF** [comment]
Это нехорошая ошибка, спасибо, что нашли её! Взгляну на неё.

**Comment by DmitrysIF** [comment]
Исправлено, в работе.
