### ISSUE TITLE
Misspelled word "Looking"

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#552]
При добавлении товаров ошибка в слове Loking - должно быть с двумя О - Looking
<img width="1076" alt="screen shot 2017-06-28 at 9 57 03 am" src="https://user-images.githubusercontent.com/4335901/27656582-56b4ce38-5bfe-11e7-9800-8c7d41e3ac9e.png">

**Comment by DmitrysIF** [comment]
fixed
