### ISSUE TITLE
Ship Each Item and ERP

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#554]
Is it possible to make sure that items that are selected to "ship each item" would end up in our ERP when someone purchases them? Also, the number of items would get lowered reflecting the change.

**Comment by DeveloperRegistry** [comment]
This is the way it was coded?  Do you have a case where this functionality did not work? If yes, please provided additional details: wishlist name, good info etc.

**Comment by galinafed** [comment]
http://gooddler.com/Wishlist/10157

Item: Pampers Swaddlers Diapers, Size N, Giant Pack, 128 Count (Packaging May Vary) $37.22

**Comment by DeveloperRegistry** [comment]
I recreated the exact Purchase completed by the Customer. There were 4 items total (2 with Ship Each Item and 2 Without). In my test, both items with Ship Each Items were successfully moved to ERP. 
So the question to Galina: did you update the Items to Ship Each Item to Yes AFTER the Customer Purchase? As of right now the defect cannot be reproduced.
Note: the expectation that items will be moved to ERP upon setting Ship Each Item to Yes is not valid.  Setting the flag should be done before purchases.

**Comment by galinafed** [comment]
Got it. Will keep observing that list. Thank you
