### ISSUE TITLE
Unable to "complete" an item

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#555]
We have an organization that chose "ship each item". To avoid a problem of me forgetting i wanted to use my old trick to "completing" the item first and then adding it again with a lower number of requested items. When i tried it, it gave an error message saying that min number of items is 5. http://gooddler.com/Wishlist/Constructor/s3
![screenshot 81](https://user-images.githubusercontent.com/7177944/27774210-3d52a734-5f42-11e7-95ee-4c6f8e978610.png)

**Comment by DmitrysIF** [comment]
@galinafed дайте подробную инструкцию - я не совсем понимаю фокус хака, который вы разработали :)

**Comment by galinafed** [comment]
sorry, basically, i can not lower the number of items to 1 so it will show that line as "completed"

**Comment by DmitrysIF** [comment]
Давайте по пунктам - как воспроизвести эту "ошибку", я не совсем понимаю - как добиться такого же
