### ISSUE TITLE
A button "View All Blogs" at a Charity Page doesn't work

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#556]
Жму на оранжевую кнопку (см стрелку). Ожидаю, что увижу все блог посты по этому чарити. ![screen-shot-2017-07-04-at-1 29 10-pm](https://user-images.githubusercontent.com/4335901/27842341-22dfbbc6-60be-11e7-9c30-2c2200afb721.png)

Получаю вот такой экран:

<img width="1169" alt="screen shot 2017-07-04 at 1 28 54 pm" src="https://user-images.githubusercontent.com/4335901/27842361-42309d38-60be-11e7-9964-18b9333d8c58.png">

Проверила на других чаритис, везде та же проблема.

**Comment by DmitrysIF** [comment]
Fixed and Deployed
