### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#559]
Apparently, we are missing contact information on our website. Can we have info@gooddler.com listed on every page as well as on our Help Page. There i think we can even provide my phone number.

How about right below the video we write:

Please, reach out to us if you have any questions or comments: info@gooddler.com
If you need to talk to us, call: 415-518-0204

**Comment by DeveloperRegistry** [comment]
Assigned to Dima

**Comment by DmitrysIF** [comment]
в каком месте страницы разместить это? Со скриншотом было бы вообще здорово.

**Comment by DmitrysIF** [comment]
И знаете - надо полностью переделать страницу Help, там устаревшая информация!

**Comment by Fetati** [comment]
Я предлагаю разместить 
1) в футере 
<img width="1104" alt="screen shot 2017-07-14 at 9 10 57 am" src="https://user-images.githubusercontent.com/4335901/28220475-70a30e18-6874-11e7-8f15-92bb36989c61.png">

2) на странице About под всем текстом: http://gooddler.com/About

Please, reach out to us if you have any questions or comments: info@gooddler.com
If you need to talk to us, call: 415-518-0204

**Comment by galinafed** [comment]
sounds great

Galina

**Comment by galinafed** [comment]
Yes!

Galina

**Comment by DmitrysIF** [comment]
fixed with footer
