### ISSUE TITLE
Wishlist: Переворачивается фотка

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#56]
При создании вишлиста добавляю фотографию. Она автоматически поворачивается горизонтально, хотя картинка вертикальная. Можно исправить? 

![screen shot 2014-04-10 at 6 46 54 pm](https://cloud.githubusercontent.com/assets/4335901/2675523/63917c18-c11b-11e3-80f3-bad3583c17bb.png)

**Comment by DmitrysIF** [comment]
Прошу переслать мне файл, который вы загружали, по почте.

**Comment by DmitrysIF** [comment]
Мои тесты проходят без ошибок - картинки загружаются перевернутыми, если они на компьютере были уже перевернутыми. Если вы переворачивали картинку до нормального положения - вы ее могли не сохранить перед загрузкой.

Попробуйте еще раз загрузить картинку, предварительно ее развернув на компьютере и сохранить изменения, чтобы если открыть картинку на компьютере - она не разворачивалась в старое положение.

**Comment by Fetati** [comment]
Комп (в моем случае Мак) автоматически при просмотре поворачивает фотку так, как надо. Я ее вижу в обычном виде, не перевернутую. И при загрузке на Фейсбук или в другие соцсети фотка автоматически переворачивается в нормальный вид. Люди привыкли к этому. Я уже очень давно не сталкивалась с таким при загрузке фотографий. Можно сделать так, как везде? Чтобы не ломать голову как и в чем  фотку повернуть, чтобы она встала нормально на gooddler.

Вижу на компе эту фотку так:
![screen shot 2014-04-11 at 9 34 26 am](https://cloud.githubusercontent.com/assets/4335901/2682191/515b8b02-c197-11e3-91d4-7af148aac551.png)

Вставляю на Фейсбук:
![screen shot 2014-04-11 at 9 32 39 am](https://cloud.githubusercontent.com/assets/4335901/2682198/6210668e-c197-11e3-8fbf-c110a9ba0f96.png)

Вот так вставляется на gooddler:
![screen shot 2014-04-11 at 9 39 06 am](https://cloud.githubusercontent.com/assets/4335901/2682238/de007b94-c197-11e3-9c3b-e7e549e39b69.png)

**Comment by DmitrysIF** [comment]
Думаю - вам стоит это обсудить с Никитой.

**Comment by DmitrysIF** [comment]
Я предлагаю эту доработку оставить на  Release 2.

**Comment by Fetati** [comment]
Хорошо, давайте оставим.
