### ISSUE TITLE
My cart shows $$ and amount, even I signed out.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#561]
My cart значок на главной странице в header показывает, что там находится, даже если я signed out. Не пропадает даже после многократной перезагрузки страницы

<img width="1386" alt="screen shot 2017-07-25 at 11 21 13 am" src="https://user-images.githubusercontent.com/4335901/28587372-d237e01c-712b-11e7-863f-4ff406c2e753.png">

**Comment by DmitrysIF** [comment]
@Fetati А нужно разве очищать? Мы её нигде не сохраняем, только куках.

**Comment by DmitrysIF** [comment]
Проверьте. @Fetati
