### ISSUE TITLE
New Credit Card Processing Testing: Client Validation Error --> Card Exp. Date

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#566]
The application fails for a completely valid exp dates of either 02/21 or 02/18. Also, Java script creates extra spaces in this field.

![image](https://user-images.githubusercontent.com/3822498/29492748-29f6ce68-853a-11e7-833e-8581c753dd94.png)

**Comment by DmitrysIF** [comment]
Fixed. Deployed.
