### ISSUE TITLE
Design: Поля внесения товара в вишлист не соответствуют тексту под ними

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#57]
![screen shot 2014-04-10 at 6 53 50 pm](https://cloud.githubusercontent.com/assets/4335901/2675548/4e0e35ec-c11c-11e3-90b6-9b1889495e6d.png)

Галина напишет тексты как должно быть.

**Comment by DmitrysIF** [comment]
"Поля внесения товара в вишлист не соответствуют тексту" - текст принадлежит таблице.

**Comment by Fetati** [comment]
Тем более. Сейчас эти надписи просто болтаются, не понятно к чему. Должна быть или видна таблица, и что это к ней заголовки.  Или вообще не должно быть этих надписей, когда товаров нет.

**Comment by galinafed** [comment]
Add Items (?): Find your desired item online (we only use Amazon.com at the moment). Copy the link and paste it into the slot below. Adjust the quantity. Click ADD to add it to the list.

**Comment by DmitrysIF** [comment]
Теперь таблица скрывается, если в ней нет записей.
Добавлен hint
