### ISSUE TITLE
New Credit Card Processing:  Items are not cleared from the cart

### ISSUE THREAD

**Issue by DeveloperRegistry** [Goodler/code#571]
In staging environment, shopping cart is not cleared after successful credit card processing.

**Comment by DmitrysIF** [comment]
Подтверждаю, ошибка воспроизведена.

**Comment by DmitrysIF** [comment]
Это не ошибка, это из-за того, что в адресе содержится слово gooddler, он назначает из-за этого куки домену .gooddler.com.

В релизе работать будет.

**Comment by DmitrysIF** [comment]
Дополнил условие очистки кук - теперь там есть фильтрафия, что если адрес содержит cloudapp, то нет принудительной установки имени домена. Протестировано, развёрнуто на стейджинге. Исправлено.
