### ISSUE TITLE
Missing General Checkout Email from GOODdler

### ISSUE THREAD

**Issue by DmitrysIF** [Goodler/code#572]
Я заметил, что если пользователь совершает покупку у чарити, у которого выключена опция "Send Tax-Deductible receipts", то пользователь вообще никакого подтверждения не получает! Меня это обескуражило и я даже сначала думал, что у нас в системе баг (бага нет, это так было задумано). 

Я думаю, что нужно будет добавить ещё одно письмо от самого GOODdler, с сообщением чека на полную сумму покупки. Или что-то в этом роде, что могло быть подтверждением получения денег сервисом от пользователя. Тем более, что мы прямо пишем на Successful странице, что он должен получить емейл!

**Comment by galinafed** [comment]
We can do the same letter, just remove the line: PLEASE RETAIN THIS RECEIPT FOR YOUR TAX RECORDS
the rest would work as a receipt.

**Comment by DmitrysIF** [comment]
Сделано
