### ISSUE TITLE
Eror: can't open the link

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#574]
Выдает ошибку при попытке зайти в товар по линку

Лист: http://gooddler.com/Wishlist/10181

Захожу как администратор с лаптопа.

Последний товар в листе - при нажатии на линк, выдается ошибка.
<img width="1116" alt="screen shot 2017-09-22 at 3 29 45 pm" src="https://user-images.githubusercontent.com/4335901/30762127-b779329c-9fae-11e7-91cd-55c1a1967896.png">

Кликаю на Edit, вижу описание товара, но линк опять выдает ошибку:

<img width="990" alt="screen shot 2017-09-22 at 3 30 10 pm" src="https://user-images.githubusercontent.com/4335901/30762139-c1aacfdc-9fae-11e7-9378-b20b7cc76c75.png">

Вот, что получается:

<img width="1041" alt="screen shot 2017-09-22 at 3 30 18 pm" src="https://user-images.githubusercontent.com/4335901/30762145-c9b4676a-9fae-11e7-90a7-b6257c7dd14e.png">

**Comment by DmitrysIF** [comment]
Сообщите название браузера, пожалуйста, в котором была обнаружена проблема. В хроме работает.

**Comment by Fetati** [comment]
Chrome, Version 60.0.3112.113
Захожу с Macbook Pro

**Comment by DmitrysIF** [comment]
Да, подтверждаю проблему на конкретном листе и конкретном товаре.

**Comment by DmitrysIF** [comment]
Разобрался в проблеме. Она появляется, если товар добавляется без http части в амазон-адресе с помощью Link Add. Я исправлю этот товар в базе данных и позже поправлю сам баг.
