### ISSUE TITLE
Create wishlist: Все пользователи видят Shipping cost поле?

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#58]
Все пользователи видят Shipping cost поле при создании вишлистов и их редактировании? Или только администратор? 
Должен видеть только администратор.

**Comment by DmitrysIF** [comment]
Не понимаю проблемы. Можно подробнее об этом рассказать?

**Comment by Fetati** [comment]
Когда заносишь линк амазона, добавляя товар в вишлист, я вижу поля: 1) для линка, 2) количество товара, 3) shipping cost. Поле shipping cost может видеть и редактировать ТОЛЬКО администратор, не представитель Donee. Это поле редактируется вручную администратором gooddler, в зависимости от стоимости шипинга на амазоне, и вручную раскидывает цену шипинга на каждый товар. Никита, все верно?

![edit_wishlist_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2676995/06c8f304-c147-11e3-8d28-3fc8b5e4a231.png)

**Comment by RealBerd** [comment]
Впервые об этом слышу (или впервые обратил на это внимание)
Мы сделали так, что любой имеющий доступ к редактированию вищлиста может править shipping cost.
Можешь объяснить больше? Зачем это нужно и как оно должно себя вести? Дело в том, что представитель донии имеет право опубликовать вищлист без вмешательства администратора.
В какой момент администратор вообще сможет отредактировать эти shipping cost?

**Comment by Fetati** [comment]
Никита, позвони мне, я тебе напомню, что мы обсуждали и что решили. Это была твоя идея :))

**Comment by RealBerd** [comment]
Напиши здесь. Письменно.
То что сейчас в релизе и была моей идеей. Это "правки на лету", которые не обсуждались чательно.
А цикл проверки администратором созданных вищлистов никогда не оговаривался.

**Comment by Fetati** [comment]
Проблема в том, что люди могут оплачивать одну вещь из списка. Весь товар по одной позиции листа будет отправлен один раз, когда все количество оплачено (по одной позиции). Это значит, что каждый, оплативший одну штуку товара не должен платить полную стоимость доставки. 
Я предлагала автоматически брать стоимость доставки данного товара с Амазона, делить его на количество выбранных дони товаров, и в зависимости от того, сколько единиц данного товара покупает донор, накручивать стоимость доставки за то количество товара, которое он покупает.
К примеру, доставка 10 мячиков стоит 10 долларов. Значит, что делим $10 на 10 мячиков, и накручиваем к цене каждого мячика по 1 доллару. Донор покупает 3 мячика, а значит, платит шипинг 3 доллара.

Никита, если ты помнишь, мы это тщательно обсуждали. И ты говорил, что это сложно сделать, и что лучше сделать так, что мы вручную САМИ выбираем сколько накрутить за шипинг к стоимости товара.

Сейчас сделано так, что Дони должен выбирать стоимость шипинга. Это абсурд! От дони требуется только ввести линк с товаром и его количество. Шипинг должен или автоматически считаться (как предлагала я), или вручную сотрудниками Gooddler (как предлагал Никита).
Так как мы сошлись на том, что вручную проще, давайте так и оставим.

Надо УБРАТЬ выбор стоимости шопинга при создании вишлиста представителями дони. Эта опция должна быть доступна ТОЛЬКО администраторам Gooddler.

**Comment by DmitrysIF** [comment]
Реализовано - теперь только админ имеет доступ к этим полям.
