### ISSUE TITLE
Check out: При оплате не понятно, прошла оплата или нет.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#59]
При оплате товаров нет никаких уведомлений, что проплата прошла. Надо перекидывать на другую страницу "Thank you for your payment" или что-то в этом духе.

**Comment by DeveloperRegistry** [comment]
Tanya, we need to come up with design for a Payment Success page. Ideally, it should be print-able  (receipt style)  since some donations are tax deductible.  

We can consider providing Charity Name, Address, Dollar Amount and agency type (e.g. 501 (c) (3) ).

What do you think?

**Comment by Fetati** [comment]
Да, согласна, it should be printable (receipt style).

Я уточню у Гали какие нужны поля в этой бумаге для налогов.

**Comment by DmitrysIF** [comment]
Предварительная версия странички "спасибо, все прошло здорово" готова, пока только 2 сообщения "оплата совершена" и "вернуться на главную".

**Comment by DmitrysIF** [comment]
Хотелось бы знать - что хотим получить в итоге.

**Comment by DmitrysIF** [comment]
Дублирование
