### ISSUE TITLE
Dashboard - misspeling

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#591]
Misspelled a word Charities everywhere.
Сейчас заголовок:
Most Recent Purchases
for your Charitys 
http://gooddler-stg.cloudapp.net/Dashboard/Charity
Wrong word - Charitys, change to - Charities (это множественное число от Charity)

**Comment by DmitrySLN** [comment]
Это мой новый аккаунт, теперь делайте подписку на него для вызова на Issues
