### ISSUE TITLE
UX: Having two ways to Sign Up is not necessary (Sign Up icon is good enough) 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#62]
1. I would remove the 'I want to sign up" link ( we have icon)
2. If we do "forgot username flow then the link should be under username field,if we don't "forgot password" should be moved under the  password field
   ![location of password retrive](https://cloud.githubusercontent.com/assets/7193843/2676313/190a876a-c135-11e3-94eb-b2eeccc88b13.png)

**Comment by DmitrysIF** [comment]
Fixed
