### ISSUE TITLE
How can I see donors?

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#64]
Как я могу видеть кто дал денег? И вообще, где можно найти доноров на сайте?

**Comment by DeveloperRegistry** [comment]
Dima, we talked with Tanya about this today. I think Admins need to be able Donors. Do we have any page like this?

**Comment by DmitrysIF** [comment]
_Как я могу видеть кто дал денег? И вообще, где можно найти доноров на сайте?_
Донейшены можно посмотреть в своей админке, там же и подписано - кто сколько дал.

**Comment by RealBerd** [comment]
Есть списки доноров по Донии. 
Эти списки доступны для администраторов и для менеджеров Донии.
Общего списка Донейшнов нет.

**Comment by DmitrysIF** [comment]
Доноров на сайте теперь можно посмотреть.
Есть список, доступный только для админов - показывает весь список донейшенов, которые когда либо были сделаны на этом сайте.
