### ISSUE TITLE
Покупка товаров из вишлиста: Сумма в корзине и надпись Added должны пояляться одновременно.

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#66]
При нажатии кнопки Donate сумма в корзине должна появляться одновременно с надписью Added в строке вишлиста, а не после обновления.

![screen shot 2014-04-13 at 7 51 06 pm](https://cloud.githubusercontent.com/assets/4335901/2691424/c9bd30a2-c37f-11e3-8d0a-88b31a6d5b66.png)

**Comment by DmitrysIF** [comment]
Такова механика сейчас. Все данные корзины хранятся в браузере у пользователя, Поэтому добавить товар в корзину быстро и легко. Далее, скрипты делают обновление данных корзины обращаясь к серверу - что соответственно занимает время.

**Comment by DmitrysIF** [comment]
По этому я склоняюсь к мнению, что это не баг - а издержки архитектуры. Или вы хотите усложнить процесс добавления товара в корзину, ну там поставить clockwise-spinner вместо сообщения и потом заменять его надписью Added в момент, когда придут новые данные о корзине?

**Comment by RealBerd** [comment]
Это решается. 
Таня, мы сделаем.

**Comment by DmitrysIF** [comment]
Общим консилиумом с Никитой было признано, что это не является багом.
