### ISSUE TITLE
Check the email ( support@stormpath.com.) - period has to be removed from HTML tag- user unable to send email

### ISSUE THREAD

**Issue by ghost** [Goodler/code#67]
forgot your password flow
email body

**Comment by DeveloperRegistry** [comment]
Dima, did you replace the latest API key for stormpath? If not, I can resend you. Tanya now has a new account. I may need some help with configuring email options.

**Comment by DmitrysIF** [comment]
Вы действительно хотите это сделать сейчас? Всех пользователей, которые есть на этой базе - придется удалить. Они завязаны на аккаунты стормпатча.

**Comment by DmitrysIF** [comment]
Check the email ( support@stormpath.com.) - period has to be removed from HTML tag- user unable to send email

Не могу понять эту фразу - в чем проблема?

**Comment by DmitrysIF** [comment]
Если вы о содержимом письма со ссылкой для смены пароля - то используется сервис stormpath. 
_This message was sent by Stormpath. Visit www.stormpath.com to learn more.
 If you received this email by mistake or believe it is spam, please forward it to support@stormpath.com._
Это футер письма, который дописывается сервисом автоматически - изменить никак нельзя.

**Comment by ghost** [comment]
once user click the email it does nothing , it does not work. if we cant change it now, but later it sfine. I would keep ticket open till we change it and then test
Let me know if you have more questions
