### ISSUE TITLE
User looses all upload when creating donees and filling the info incorrect

### ISSUE THREAD

**Issue by ghost** [Goodler/code#69]
Steps:
1. click create Donee
2. fill out info but leave address line 2 blank (what if people have home address as their business and have no suite # to indicate in Address Field #2 ?) Maybe we should allow to leave it blank?
3. Upload pictures for Donees
4. Click Done

Bug: user will lose all the uploads (photos) if he made a mistake in one of those fields
UX recommendations: we should be able to let user keep the uploads

**Comment by DmitrysIF** [comment]
Попробуйте повторить эту ошибку. Непонятна ваша проблема с показом загруженных картинок после неудачной попытки создания дони (я ее не обнаружил).
По поводу обязательности поля AddrLine2 - я убрал ее из required

**Comment by ghost** [comment]
will retest it once Select File will work
Thank you Dima for a quick fix for Line #2

**Comment by ghost** [comment]
Select File also does not work on Create Post page:) Dimochka mojesh glianut?

**Comment by DmitrysIF** [comment]
Починил :)

**Comment by DmitrysIF** [comment]
Все нормально? Ну тогда я закрываю.

**Comment by ghost** [comment]
All issues where address, separate bug for UX were filed. thank you Dima:)
