### ISSUE TITLE
Delete Edit Profile link

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#7]
Delete Edit Profile link from the menu. It should be under the user name link ("tatiana" in my case). Put Edit Profile button here http://gooddler.cloudapp.net/Profile/

![screen shot 2014-04-05 at 11 20 47 am](https://cloud.githubusercontent.com/assets/4335901/2623442/18fd833e-bcef-11e3-9d78-098f40f7b7b8.png)

**Comment by DmitrysIF** [comment]
Исправлено.

**Comment by DeveloperRegistry** [comment]
Tanya, please retest once the fix is deployed.

**Comment by Fetati** [comment]
Fixed.
Thank you!
