### ISSUE TITLE
Donee creation flow: user unable to delete uploaded photo

### ISSUE THREAD

**Issue by ghost** [Goodler/code#70]
create Donee and add photo (file) and click Upload and then try to delete it

No luck (at least in Chrome for now:)

**Comment by DmitrysIF** [comment]
Не совсем понимаю - все прекрасно удаляется после загрузки. В последних исправлениях я поставил автоматическую загрузку файла после выбора файлов в диалоге.

**Comment by ghost** [comment]
Dima i can't upload photos now. Select File does not work:(((

**Comment by Fetati** [comment]
Да, что-то сломалось. Я тоже не могу

**Comment by DmitrysIF** [comment]
Починил.
