### ISSUE TITLE
UX: can we change SLUG to something different?

### ISSUE THREAD

**Issue by ghost** [Goodler/code#71]
create Donee
and observe the first field 
UX: sounds very strange

![slug](https://cloud.githubusercontent.com/assets/7193843/2692044/b29fab86-c396-11e3-8a41-c63272e0b266.png)

**Comment by DmitrysIF** [comment]
Запись об этом пункте уже есть. Есть и пример в какую сторону исправлять. Работы идут.

**Comment by ghost** [comment]
i will close it since its  a duplicate
