### ISSUE TITLE
UX: can we have Upload File or Upload Photo and have a preview right away and edit option?

### ISSUE THREAD

**Issue by ghost** [Goodler/code#72]
try to create Donee and upload file
Select file and Upload file sounds fine, but logic can be more user friendly, e.g.
#1

Upload file-> immediate preview-> and edit btn next to it
#2

I would call it Create Photo Gallery instead of Edit Photo Gallery
under that i would have 
Upload file ( and have small thumbnails) and edit btn or delete btn (Delete better bcs we don't offer Editing tools for user)  
#3

![edit and upload](https://cloud.githubusercontent.com/assets/7193843/2692098/ab95dae8-c398-11e3-90ec-b76bcc86cdbf.png)

**Comment by DmitrysIF** [comment]
Думаю, этот вопрос больше не актуален - загрузка стартует автоматически, показывает превью загруженной картинки, которую можно удалить при необходимости из галереи.
