### ISSUE TITLE
Платёж завершён. Тексты и содержание страницы.

### ISSUE THREAD

**Issue by RealBerd** [Goodler/code#73]
Былили ли где-нибудь материалы для страницы "Оплата прошла, вы молодец" ?

Можно добавить туда ссылку на автосгенерированный пост, "спасибу" или ещё что-то?

http://i.imgur.com/nMDpwTa.png

**Comment by Fetati** [comment]
Текст пришлем сегодня в течение дня.

**Comment by Fetati** [comment]
Текст для страницы Оплата прошла:

Thank you for your generosity! Your transaction was successful. You will be receiving a confirmation email shortly. Save it as a receipt for your donation.

**Comment by RealBerd** [comment]
Тогда нужен ещё текст емейла.

**Comment by galinafed** [comment]
Shared doc with you.
