### ISSUE TITLE
Edit Donee: when user try to edit donee on the list it gives some fields that do not make sense 

### ISSUE THREAD

**Issue by ghost** [Goodler/code#74]
Create Donee ad try to edit the Donee
could someone explain what this field is for?
:) thank you
![edit donee](https://cloud.githubusercontent.com/assets/7193843/2703772/a3bee170-c45b-11e3-8bd7-bc2b96e99c48.png)

**Comment by DmitrysIF** [comment]
Это поле для того, чтобы раздавать права доступа к редактированию этого дони, созданию вишлистов от имени этого дони, в общем - это участники (не суперадмины), которые будут сопровождать и поддерживать дони. Нужно вводить имя пользователя, которому хотим дать возможность редактировать это.

**Comment by Fetati** [comment]
Это хорошая мысль для следующего релиза.
1) Надо сделать эту возможность доступной всем, кто заносит Donee (не только супер-администраторам). Потому что может занести Donee айтишник, а листы заносить и управлять потом другой человек. 
2) Сделать hint для этой функции

**Comment by DmitrysIF** [comment]
Если вы о возможности управлять доступом другими участниками дони - то это и так возможно. Это не является личной привилегией супер админа.
Нужен текст для hint

**Comment by DmitrysIF** [comment]
Мне нужен хинт для этой функции!

**Comment by galinafed** [comment]
Hint to Access list. "Enter a name of the person who will receive all rights to manage, support and edit a page of this Donee"

**Comment by DmitrysIF** [comment]
Хинт добавлен.
