### ISSUE TITLE
logic of this page (especially the use of Posts)

### ISSUE THREAD

**Issue by ghost** [Goodler/code#75]
Just a quick question regarding this page
creation of Donees? Posts, for whom it is intended? 
The logic of View and Highlighted Handle (Donne name) ? because for me it would be the same and should lead to a profile of Donee
![hmmm](https://cloud.githubusercontent.com/assets/7193843/2703845/8e6812b8-c45d-11e3-95b0-ca17aed09ffc.png)

**Comment by DmitrysIF** [comment]
В списках Дони этот параметр отвечает за количество постов, которые были написаны для для данного дони. В счет входит так же количество постов для вишлистов этого дони, количество постов донейшенов для этих вишлистов и тд. В общем считаются все посты, у которых заполнено поле "DoneeID"

**Comment by DmitrysIF** [comment]
Посты имеют идентификаторы, которые содержат в себе код дони, код вишлиста, код донейшена, код автора, код донора. Некоторые из этих полей могут быть пустыми.
