### ISSUE TITLE
Donee should be Capitalized throughout the web pages

### ISSUE THREAD

**Issue by ghost** [Goodler/code#76]
![donee](https://cloud.githubusercontent.com/assets/7193843/2703849/a6c547cc-c45d-11e3-9d58-1d63efe3eb62.png)

Is this the only option for words? can we consider Comments instead of Posts?

**Comment by DmitrysIF** [comment]
Комментарии? В нашей текущей модели нет возможности сейчас делать комментарии.

**Comment by DmitrysIF** [comment]
Сделал правки. Правки текста кнопки будут применены позже.
