### ISSUE TITLE
Форма ввода кредитной карты. Баги

### ISSUE THREAD

**Issue by RealBerd** [Goodler/code#77]
При попытке ввести месяц меньше чем 04 оно зачем-то автоматически правит на 04. Явно баг.
http://i.imgur.com/EyCVh4d.png

Так же, оно автоматически меняет фокус на соседнее поле если я пытаюсь отредактировать уже заполненное поле (месяц или год)

**Comment by DmitrysIF** [comment]
хорошо, поправлю. Удалю автоподстановку валидной даты и уберу автоматический переход на  соседние поля при редактирования месяцы - года.

**Comment by RealBerd** [comment]
лучше распознавай, что поле уже было заполненно полность и сейчас пользователь пытается отредактировать его. А автосмену фокуса оставь.
