### ISSUE TITLE
При создании вишлиста поехала страница

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#79]
Chrome
Видимо, надо сделать, чтобы заголовки товаров переносились на вторую строчку, чтобы страница не убегала: 

![screen shot 2014-04-15 at 12 49 42 am](https://cloud.githubusercontent.com/assets/4335901/2704737/98477200-c472-11e3-8ccb-5c32a2e5b3ab.png)

**Comment by DmitrysIF** [comment]
Может просто обрезать названия? А полное название показывать во всплывающей подсказке, которая появится при наведении на название. Такое реализовано в вишлисте и всплывающем окне корзины.

**Comment by DmitrysIF** [comment]
Если сделать просто перенос - может таблица сделаться некрасивой.

**Comment by Fetati** [comment]
Можно и обрезать. Только чтобы не нарушать логический смысл названия.
