### ISSUE TITLE
Wrong Main Page design 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#8]
This is our Main Page design:

![04_gooddler_home_new2-2](https://cloud.githubusercontent.com/assets/4335901/2623467/305621f6-bcf1-11e3-8441-452e21f627bd.jpg)

**Comment by RealBerd** [comment]
Финальная инструкция для вёрстки выглядила так:

![04_main_descriptions](https://cloud.githubusercontent.com/assets/2241165/2624146/bd77a4c8-bd24-11e3-8653-2bef40f16a7b.jpg)
![04_main_cleaned](https://cloud.githubusercontent.com/assets/2241165/2624147/bd79a4da-bd24-11e3-80c4-e59c7152c0a6.jpg)

Правки, которые были придуманы позже:
- Подпись "Menu" под иконкой меню добавлена, из-за того, что никто (включая разработчиков) не могли найти это меню долго. Надпись решила проблему.
- Прямоугольные картинки заменили на квадратные, из-за того, что мало картинок могут хорошо сомтреться в оригинальном формате и в квадратном и в прямоугольном. Гораздо проще подобрать картинку, которая смотрится хорошо в оригинальном размере и в квадратном, чем расчитывать на три формата. Так же, это технически проще.

Какие ошибки тут есть:
- Иконка меню не та, ошиблись и сверстали из друго шаблона. Можно заменить на любую.
- Ссылка "How it works" почему-то отсутстует. Вернём.
- Тултип "All wishlists" отсутствует. Или забылся, или не обсуждался. Какой сценарий его появления на сайте?

**Comment by Fetati** [comment]
Все верно. 
All wishlists сейчас есть, просто медленно появляется. Он появляется, когда подводишь мышь к значку. Можно сделать, чтобы появлялся быстрее? 

Еще голова у значка Gooddler обрезана в названии Donnees. Должен быть полноценный значок.

**Comment by Fetati** [comment]
Не забыли по поводу правильной версии дизайна?
И надо оставлять How It Works на всех страницах. Мы туда просто еще текста добавим. Типа Q&A

**Comment by DmitrysIF** [comment]
_И надо оставлять How It Works на всех страницах_
В целях совместимости дизайнов - How It Works не показывается для залогиненного пользователя.

**Comment by DmitrysIF** [comment]
_All wishlists сейчас есть, просто медленно появляется. Он появляется, когда подводишь мышь к значку. Можно сделать, чтобы появлялся быстрее?_
Хорошо, сделаем.

**Comment by DmitrysIF** [comment]
_All wishlists сейчас есть, просто медленно появляется. Он появляется, когда подводишь мышь к значку. Можно сделать, чтобы появлялся быстрее?_
Я думаю, что скорость появления достаточна высока. Закрою этот issue
