### ISSUE TITLE
На странице My Donees что-то сломалось -  cъехали значки. 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#80]
Chrome - http://gooddler.cloudapp.net/Admin/Donees

![screen shot 2014-04-15 at 10 29 24 am](https://cloud.githubusercontent.com/assets/4335901/2710612/8d974550-c4c3-11e3-81ef-23623cd6db62.png)

**Comment by DmitrysIF** [comment]
Они съехали по причине большого количества кнопок и слишком большого количества полей.
Нужно думать - все ли поля и кнопки нужны? Если нужны  - я могу попробовать увеличить максимальное ограничение ширины таблицы, это должно вернуть кнопки на родину.

**Comment by RealBerd** [comment]
Можно просто сделать таблицу чуть-чуть шире.

**Comment by DmitrysIF** [comment]
Сделал табличку чуть шире

**Comment by Fetati** [comment]
У меня все по-прежнему. Жду обновлений.

**Comment by DmitrysIF** [comment]
Сообщите о разрешении вашего экрана.

**Comment by Fetati** [comment]
1280x800, MacBook Pro 13'

**Comment by DmitrysIF** [comment]
??????? ?????? ????? ??????, ????? 15-20 ????? ????? ????? ????????????.
?????? ???? ???? ????????? ??????, ????? ?? ???????????? ???.

2014-04-19 2:24 GMT+09:00 Tatiana Fedorova notifications@github.com:

**Comment by DmitrysIF** [comment]
???????? ? ?????????????? - ????? ?????? ??????????.

19 ?????? 2014 ?., 3:03 ???????????? Dmitry Shestialtynov <
dmitrys@ifface.com> ???????:

**Comment by Fetati** [comment]
Дим, пришли зюки какие-то. Что это было?

**Comment by DmitrysIF** [comment]
ïÂÎÏ×ÌÅÎÉÅ ÚÁËÏÎÞÉÌÏÓØ. ðÒÉÍÅÎÉÌÉÓØ ÎÏ×ÙÅ ÐÒÁ×ËÉ.

2014-04-19 3:16 GMT+09:00 Tatiana Fedorova notifications@github.com:

**Comment by DmitrysIF** [comment]
Ну и гугл - исковеркал весь шрифт. Закончено обновление!
