### ISSUE TITLE
Post error: Broken Donee link

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#81]
Broken Donee links (both) http://gooddler.cloudapp.net/Blog/Post/20011
![screen shot 2014-04-15 at 12 00 19 pm](https://cloud.githubusercontent.com/assets/4335901/2711671/504d6794-c4d0-11e3-957f-ccd748a7a9eb.png)

![screen shot 2014-04-15 at 12 02 47 pm](https://cloud.githubusercontent.com/assets/4335901/2711707/ad74237c-c4d0-11e3-8811-56e5662eed91.png)

**Comment by DmitrysIF** [comment]
Поимка бага свершена - баг наказан :) 
(В следующем обновлении)

**Comment by Fetati** [comment]
Ура! Спасибо! Жду обновлений и закрываю.
