### ISSUE TITLE
Edit Profile: При редактировании юзера нет поля Username 

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#82]
Невозможно отредактировать username. - При редактировании юзера нет поля Username. Надо добавить.

**Comment by DmitrysIF** [comment]
Это важно? Хорошо.

**Comment by DmitrysIF** [comment]
Отложено в связи с зависимостью Аватарок от юзернейма.

**Comment by DmitrysIF** [comment]
Исправлено досрочно.
