### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#84]
Add Username and give it an ability to be changed. Add (?): username will be displayed for everyone to see

First name: Remove ?
Last name: Remove ?

Has to have auto correct/edit option in About section, like if you are writing in Word Document, or Google chat. It should show misspellings and give options to correct.

About (?) can say: Tell Gooddler community about yourself. It will help you to connect with others who have similar interests.

Location (?): Replace with Where do you live? 
It will allow us to remove (?), since it is a straightforward question.

Remove ?s from all Facebook link, Twitter link, LInkedIn link, since it's not taking you anywhere and not showing on your profile anyway.

Photo: Remove ?
I was unable to change my photo. If i click on empty slot, it takes me to browse my files. (same as clicking on Browse doess). I think it should have my current file link listed or say something like, click here to change picture. When i go to browse and pick a different picture, open file, link shows in a slot, then i click on edit profile but picture is not replaced.
So, i think a step is missing here.

**Comment by DmitrysIF** [comment]
Картинка меняется - но существует некоторая задержка обновления, поэтому картинка меняется некоторое время спустя и начинает показываться в правильном варианте (новая). Решаю этот вопрос с Никитой.

**Comment by galinafed** [comment]
Also, here is what i see in comments about me:

<p>Encouraging generosity</p>

It should just say: Encouraging generosity

**Comment by DmitrysIF** [comment]
*Encouraging generosity

It should just say: Encouraging generosity*

Не совсем понимаю - куда это нужно разместить.

**Comment by galinafed** [comment]
Description shows:

<p>Encouraging generosity</p>

with < and p on both sides.

**Comment by galinafed** [comment]
when posting here it's not showing, but that's how i see my profile. 
<p>

**Comment by DmitrysIF** [comment]
то есть, где-то отображаются html теги? Ссылку на пост. Или на профиль.

**Comment by galinafed** [comment]
Yes

**Comment by DmitrysIF** [comment]
Мне нужна ссылка на пост или профиль. Я не экстрасенс :)
Или еще лучше вместе со скриншотом.

**Comment by galinafed** [comment]
![screenshot 10](https://cloud.githubusercontent.com/assets/7177944/2746011/c691bc3c-c73e-11e3-8351-c4547e621a61.png)

on the right side, description that i wrote

**Comment by DmitrysIF** [comment]
по поводу  <p> тегов - вы должны зайти в режим редактирования профиля и удалить эти символы в редакторе. Они появились, когда еще были проблемы с визивиг-редактором.
Если удалить их вручную - они больше не должны появиться.

**Comment by galinafed** [comment]
fixed

**Comment by galinafed** [comment]
![screenshot 11](https://cloud.githubusercontent.com/assets/7177944/2746139/060bf358-c741-11e3-86ea-15051906b02c.png)

word "password" is misspelled

**Comment by galinafed** [comment]
![screenshot 12](https://cloud.githubusercontent.com/assets/7177944/2746154/4db3efd0-c741-11e3-9240-18bc2604d6cc.png)

Should say: "Your password has been changed successfully"

**Comment by DmitrysIF** [comment]
Опечатки убраны и исправлен текст сообщения. Через 20 минут изменения можно будет проверить.

**Comment by DmitrysIF** [comment]
Можно проверять.

**Comment by galinafed** [comment]
now is ok. I notice one more thing. Under my profile, it says post's not found, should say:
Posts not found. remove ' pls.

**Comment by DmitrysIF** [comment]
Хорошо, в следующем обновлении это исправление можно будет увидеть.

**Comment by DmitrysIF** [comment]
Сделано - через 20 минут будет доступно.

**Comment by DmitrysIF** [comment]
Так, проблемы с фотографией я исправил. Добавил возможность менять юзернейм. Правки текста сделал.
Закрываю.
