### ISSUE TITLE
Edit Donee: Не могу добавить юзера к Donee

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#85]
В режиме администратора пытаюсь передать права на мною созданного Donee другому пользователю. И не могу  - просит username. При вводе имейла, ругается, что "is't exist". Надо сделать возможность добавлять юзера по имейлу. Это куда надежнее, чем по username. 
Где искать как человек себя назвал в качестве username не понятно. А имейл есть в любом случае.

![screen shot 2014-04-15 at 1 16 53 pm](https://cloud.githubusercontent.com/assets/4335901/2712485/f509fb58-c4da-11e3-8cbb-849563ba7050.png)

**Comment by DmitrysIF** [comment]
Деплоится новая версия с реализованной поддержкой емейлов.
