### ISSUE TITLE
Add new user to Donee: Notifications

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#86]
Как юзер будет знать, что он получил права на управление Donee? Я попробовала дать права Гале, она не получила никаких уведомлений.

**Comment by RealBerd** [comment]
Пришли текст уведомления, пожалуйста.

**Comment by galinafed** [comment]
Email should say: "Tatiana Fedorova invited you to become a manager of Friends For Youth, Inc on Gooddler. As a manager you will be able to create, edit, delete wish lists, and more."

We can also add a button "Become manager" in the email to accept that role. Or we can just have a person added without their authorization. What do you think?

If we add it. Email should also say:
"To accept your role as a manager, please click on the link below."

**Comment by Fetati** [comment]
Вот пример, о чем пишет Галя:

![screen shot 2014-04-17 at 2 45 21 pm](https://cloud.githubusercontent.com/assets/4335901/2737325/a95370d6-c679-11e3-94e5-15c413dd55ee.png)

**Comment by DmitrysIF** [comment]
Инвайты не поддерживаются. Если админ назначил пользователю доступ - он получает этот доступ сразу.
Сообщение для емейла, которое должно информировать пользователя о получении доступа - пишется. Скоро будет.

**Comment by DmitrysIF** [comment]
Сделано - в следующем обновлении.
