### ISSUE TITLE
Wishlist: Done 3 of 2

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#89]
В вишлисте done 3 of 2. Как это возможно?

![screen shot 2014-04-17 at 2 33 54 pm](https://cloud.githubusercontent.com/assets/4335901/2737220/40203654-c678-11e3-87f3-e37633617698.png)

**Comment by DmitrysIF** [comment]
такое возможно - если отредактировать число гуддсов в айтеме вишлиста.
