### ISSUE TITLE
(UX) Wishlist: вываливающаяся подсказка с багом, и перекрывает текст

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#91]
1) Не должно быть пробелов в начале текста подсказок.
2) Прокрутка количества просвечивается на подсказке
3) Подвинуть подсказку выше, чтобы она была над знаком вопроса, и не перекрывала поля, которые планируется заполнять.

![screen shot 2014-04-17 at 2 36 54 pm](https://cloud.githubusercontent.com/assets/4335901/2737360/4d8165a0-c67a-11e3-8089-c7e922162338.png)

**Comment by DmitrysIF** [comment]
Исправлено.
