### ISSUE TITLE
Edit Donee: Почему 2 раза кнопка Update Donee?

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#94]
![screen shot 2014-04-17 at 3 09 58 pm](https://cloud.githubusercontent.com/assets/4335901/2737559/30c60b8e-c67d-11e3-9ae9-309226a53e75.png)

**Comment by DmitrysIF** [comment]
Вопрос к Никите.

**Comment by DmitrysIF** [comment]
Если конкретные разъяснения - то это сделано для удобства, что после проверки картин галереи пользователю не приходилось отматывать страницу наверх обратно, картин можно добавить очень много. И, соответственно, приходилось бы очень прокручивать страницу.

**Comment by DmitrysIF** [comment]
Вопрос еще актуален?

**Comment by Fetati** [comment]
Должно быть один раз. Две одинаковых кнопки на одной странице путают.

**Comment by DmitrysIF** [comment]
Удалить верхнюю или нижнюю?

**Comment by Fetati** [comment]
Удали верхнюю.

**Comment by DmitrysIF** [comment]
Сделано.
