### ISSUE TITLE
(UX) Donee: Пропущено краткое описание вишлистов на странице Donee

### ISSUE THREAD

**Issue by Fetati** [Goodler/code#95]
http://gooddler.cloudapp.net/Donee/10017

![donee_-_gooddler](https://cloud.githubusercontent.com/assets/4335901/2737636/7394385e-c67e-11e3-849e-1ff09684df26.png)

**Comment by DmitrysIF** [comment]
В шаблонах описание вишлистов на страницах дони не указано. Вы действительно считаете кусочек описания из 30-70 символов необходимым?

**Comment by DmitrysIF** [comment]
Вопрос еще актуален?

**Comment by Fetati** [comment]
Да, актуален вопрос. Добавь, пожалуйста.

Димочка, кнопка Create New Wishlist смотрится отлично. СПАСИБО!

**Comment by DmitrysIF** [comment]
Не за что :) 
Сделаю.
