### ISSUE TITLE
Create Donee Page

### ISSUE THREAD

**Issue by galinafed** [Goodler/code#96]
http://gooddler.cloudapp.net/Donee/Create
1. Stay consistent and use capital letters in every word:
   Enter Designation; Phone Number; Edit Photo Gallery; ect.
2. Spelling: Address Line 1 and Address Line 2
3. Remove Enter from ZIP line (to stay consistent)
4. Replace Add a new address with Add Shipping Address (i think add a new address would have been appropriate if we had an ability to enter multiple addresses). 

Should we also ask for donee's physical address? since it could be different from mailing.
1. Enter Description (capital letters) should have ? tab that says: Tell Gooddler audience about the organization, it will be displayed for all to see.

**Comment by DmitrysIF** [comment]
1. Cделано;
2. Сделано;
3. Сделано;
4. Сделано;

1.Сделано;
Следующее обновление :)

**Comment by galinafed** [comment]
i don't see changes

**Comment by DmitrysIF** [comment]
Следующее обновление - значит применю сделанные исправлении в следующем обновлении, которое будет через час максимум :)

**Comment by galinafed** [comment]
i still don't see all changes. Address (has to have two "s")

**Comment by DmitrysIF** [comment]
Oh, sorry!
Не заметил опечатку :)

**Comment by DmitrysIF** [comment]
Сейчас должно быть все в порядке - проверьте

**Comment by DmitrysIF** [comment]
Исправлено.
