### ISSUE TITLE
Change password link should be moved lower (creating user flow)

### ISSUE THREAD

**Issue by ghost** [Goodler/code#97]
create user
once transferred to a page to finish profile observe the "Change password" link

Bug: too close to a 
![change my password](https://cloud.githubusercontent.com/assets/7193843/2749567/b4279c40-c80d-11e3-862c-303bebc6b44b.png)
field

**Comment by DmitrysIF** [comment]
Куда его подвинуть? Лучше укажите на скриншоте - в какое место и что вообще в итоге должно быть.

**Comment by ghost** [comment]
if all fields stay in the same lay out and order then at least move it a little bit lower so it looks better. Spasibo Dimochka:)
