### ISSUE TITLE
What does  "p" mean:)))

### ISSUE THREAD

**Issue by ghost** [Goodler/code#98]
![what p does](https://cloud.githubusercontent.com/assets/7193843/2749568/c4e2175e-c80d-11e3-85fd-f563fad0dbd5.png)

**Comment by DeveloperRegistry** [comment]
I believe, since it is HTML (XHTML) editor, "P" refers to HTML Paragraph.  Dima, please correct me if I am wrong.

**Comment by DmitrysIF** [comment]
это хтмл тег для форматирования текста.

**Comment by ghost** [comment]
Does user need to see it? or use?
if not needs to be removed in time.
Thank you

**Comment by DmitrysIF** [comment]
Не думаю, что это можно удалить - редактор использует html теги для форматирования текста. В частности, тег p нужен для выделения абзацев.
Если про удаление визирования этого тега- тоже сомневаюсь.

**Comment by ghost** [comment]
Ok this is for Highlighting the text
We might know it, but users will not
Can we put icon, can we do anything about it?

**Comment by DmitrysIF** [comment]
Я не думаю, что пользователи вообще будут заморачиваться по этой иконке. Они просто будут писать.
К тому же, насколько я помню - это подпись снизу показывает вложенность тегов в позиции курсора набора текста.
Так что рекомендую не заморачиваться этим :)

**Comment by ghost** [comment]
sure:)
