### ISSUE TITLE
"edit profile" flow - should we have change password link?

### ISSUE THREAD

**Issue by ghost** [Goodler/code#99]
![forgot pass](https://cloud.githubusercontent.com/assets/7193843/2749579/bd9b9870-c80e-11e3-95cc-524eb0600392.png)
I know the flow is when user is logged in ( and we assume that he knows password),
But lets say i use Safari and it remembers my password, but i want to switch to Chrome, and being logged, doesn't necessary means i remember my password. "Change password " password link can have forgot password just for convenience

it might cost and take more time to implement it, but for the future can be there. File as a  Q.
Thank you

**Comment by DmitrysIF** [comment]
Можно удалить подтверждение смены пароля с помощью ввода старого пароля. Но тогда может пострадать безопасность.

**Comment by DmitrysIF** [comment]
Если вы имеете в виду автоподстановку пароля в поле - я не думаю, что это важно для первого этапа.

**Comment by ghost** [comment]
@DmitrysIF  agree
will close for now
